force-app/main/default/objects/Error_Event__e/fields/Error_Records__c.field-meta.xml
<CustomField>
    <fullName>Error_Records__c</fullName>
    <label>Error Records</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERROR-{00000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Error_Records__c.field-meta.xml
<CustomField>
    <fullName>Error_Records__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Records</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <description>to store record id which has thrown exception</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stack Trace</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLoggingSettings__c/ErrorLoggingSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Error Logging Settings</label>
</CustomObject>

force-app/main/default/objects/ErrorLoggingSettings__c/fields/Enable_Error_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Error_Logging__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Error Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ErrorEventTriggerHandler.cls
/**
 * Class Name  : ErrorEventTriggerHandler
 * Summary     : Helper class for the 'ErrorEventTrigger' trigger 
 * Method     :  createErrorLog     
 * @author       Simplus
   @Description: This class contains the logic for the insertion of record for ErroLog__c Object
 * @version      $Revision: 1.0 $, $Date: 20/July/2020 
 */
public class ErrorEventTriggerHandler
extends TriggerHandlerBase //extending the trigger framework
{
    public ErrorEventTriggerHandler(String triggerName) {
    	super(triggerName);
    }  

	public override void afterInsert(List<SObject> record, Map<ID, SObject> newRecordMap){
        //Check if the Custom Setting Enable Error Logging checkbox is checked
        ErrorLoggingSettings__c getCustSetting = ErrorLoggingSettings__c.getOrgDefaults();
        if(getCustSetting.Enable_Error_Logging__c == true){
            //Calls the Helper Class along with its method name
            ErrorEventTriggerHandler.createErrorLog(record);
        }        
    }    

    public static void createErrorLog(List<Error_Event__e> errEvents){
        try{
            //Holds the records to be inserted
            List<ErrorLog__c> errLogInsert = new List<ErrorLog__c>();
            //For each platform event (Error_Event__e) that is saved
            for(Error_Event__e evt : errEvents){
                //UserInfo.getName() = get the current user that triggered this
                errLogInsert.add(new ErrorLog__c(Apex_Class__c = evt.Apex_Class__c,
                                                Component_Type__c = evt.Component_Type__c,
                                                Error_Records__c = evt.Error_Records__c,
                                                Message__c = evt.Message__c,
                                                Method__c = evt.Method__c,
                                                Stack_Trace__c = evt.Stack_Trace__c,
                                                Type__c = evt.Type__c,
                                                User__c = evt.User__c,
                                                Record_ID__c = evt.Record_ID__c));
            }
            if(errLogInsert.size() > 0){
                insert errLogInsert;
            }
        } catch (Exception ex){
            System.debug('Error: ' + ex.getMessage());
        }
    }
}