force-app/main/default/objects/Campaign/fields/Event_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event End Date/Time (user timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Start Date/Time (user timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Static_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Static_End_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event End Date/Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Static_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Static_Start_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Start Date/Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Event Timezone (on location)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+07:00) Bangkok, Hanoi, Jakarta</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Kuala Lumpur, Singapore</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Taipei</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Perth</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Seoul</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Osaka, Sapporo, Tokyo</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Darwin</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Adelaide</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Canberra, Melbourne, Sydney</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Brisbane, Gold Coast</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Hobart</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Magadan, Solomon Islands, New Caledonia</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Fiji, Kamchatka, Marshall Is.</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Auckland, Wellington</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignTriggerHandler.cls
public class CampaignTriggerHandler extends TriggerHandlerBase //extending the trigger framework
{

    static final String APEXCLASSNAME = 'CampaignTriggerHandler';
    static final String COMPONENTTYPE = 'Apex Class';

    //new method which is required when we extend the TriggerHandlerBase class
    public CampaignTriggerHandler(String triggerName) {
    	super(triggerName);
    }

    //overriden methods from trigger framework base class
    public override void beforeInsert(List<SObject> tempNewCampaignList){


        List<Campaign> newCampaignList = (List<Campaign>)tempNewCampaignList;

        String timezone;
        for(Campaign camp: newCampaignList){
            if(camp.Event_Start_Date_Time__c != null && camp.Event_End_Date_Time__c != null){
                timezone = (camp.Timezone__c != null) ? camp.Timezone__c : '';
                camp.Static_Start_Date_Time__c = camp.Event_Start_Date_Time__c.format('dd/MM/yyyy h:mm a') + ' ' + timezone;
                camp.Static_End_Date_Time__c = camp.Event_End_Date_Time__c.format('dd/MM/yyyy h:mm a') + ' ' + timezone;
            }
        }
    }
    
    public override void beforeUpdate(List<SObject> tempOldCampaignList, List<SObject> tempNewCampaignList, Map<Id, SObject> tempOldCampMap, Map<Id, SObject> tempNewCampMap){
        String timezone;

        List<Campaign> newCampaignList = (List<Campaign>)tempNewCampaignList;
        Map<Id, Campaign> newCampMap = (Map<Id, Campaign>)tempNewCampMap;
        Map<Id, Campaign> oldCampMap = (Map<Id, Campaign>)tempOldCampMap;

        for(Campaign camp: newCampaignList){
            if(camp.Event_Start_Date_Time__c != null && camp.Event_End_Date_Time__c != null){
                timezone = (camp.Timezone__c != null) ? camp.Timezone__c : '';
                Datetime newStartDate = newCampMap.get(camp.Id).Event_Start_Date_Time__c;
                Datetime newEndDate = newCampMap.get(camp.Id).Event_End_Date_Time__c;
                String newTimezone = newCampMap.get(camp.Id).Timezone__c;
                
                Datetime oldStartDate = oldCampMap.get(camp.Id).Event_Start_Date_Time__c;
                Datetime oldEndDate = oldCampMap.get(camp.Id).Event_End_Date_Time__c;
                String oldTimezone = oldCampMap.get(camp.Id).Timezone__c;
                
                if(newStartDate != oldStartDate || newEndDate != oldEndDate || newTimezone != oldTimezone){
                    camp.Static_Start_Date_Time__c = newStartDate.format('dd/MM/yyyy h:mm a') + ' ' + timezone;
                    camp.Static_End_Date_Time__c = newEndDate.format('dd/MM/yyyy h:mm a') + ' ' + timezone;
                }
            }
        }
    }
}