force-app/main/default/objects/Preferences__c/Preferences__c.object-meta.xml
<CustomObject>
    <label>Preferences</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferences</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Preferences__c/fields/Dietary__c.field-meta.xml
<CustomField>
    <fullName>Dietary__c</fullName>
    <label>Dietary</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Celiac</fullName>
            </value>
            <value>
                <fullName>Dairy Free</fullName>
            </value>
            <value>
                <fullName>Fully Cooked Food</fullName>
            </value>
            <value>
                <fullName>Gluten Free</fullName>
            </value>
            <value>
                <fullName>Lactose Free</fullName>
            </value>
            <value>
                <fullName>No Beef</fullName>
            </value>
            <value>
                <fullName>No Chicken</fullName>
            </value>
            <value>
                <fullName>No Duck</fullName>
            </value>
            <value>
                <fullName>No Egg</fullName>
            </value>
            <value>
                <fullName>No Garlic</fullName>
            </value>
            <value>
                <fullName>No Mushroom</fullName>
            </value>
            <value>
                <fullName>No Onion</fullName>
            </value>
            <value>
                <fullName>No Pork</fullName>
            </value>
            <value>
                <fullName>No Preference</fullName>
            </value>
            <value>
                <fullName>No Raw Food</fullName>
            </value>
            <value>
                <fullName>No Sashimi</fullName>
            </value>
            <value>
                <fullName>No Seafood</fullName>
            </value>
            <value>
                <fullName>No Shellfish</fullName>
            </value>
            <value>
                <fullName>Pescatarian (only eat seafood and vegetarian)</fullName>
            </value>
            <value>
                <fullName>Sugar Free</fullName>
            </value>
            <value>
                <fullName>Vegan</fullName>
            </value>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Preferences__c/fields/Dining_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dining_Notes__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Dining Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Preferences__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>General_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Preferences__c/fields/Transportation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transportation Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Booking Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Dietary_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Dietary_Requirements__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dietary Requirements</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Dining_Notes__c.field-meta.xml
<CustomField>
    <fullName>Dining_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dining Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Preferences__c.field-meta.xml
<CustomField>
    <fullName>Preferences__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Car Type Preferences</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Limo</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/VIP_Booking__c.field-meta.xml
<CustomField>
    <fullName>VIP_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIP Booking</label>
    <referenceTo>VIP_Booking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/VIP_Booking__c.object-meta.xml
<CustomObject>
    <label>VIP Booking</label>
    <nameField>
        <displayFormat>VIPB-{0000}</displayFormat>
        <label>VIP Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIP Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIP_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VIP Bookings</relationshipLabel>
    <relationshipName>VIP_Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceService.cls
/* Description: Service class for Service__c object
 * Author: Simplus
 * Created: 31/5/22
 * History:
 * 31/05		Created
 */
public class ServiceService {
    
    public static void onBeforeInsert(List<Service__c> newServiceList){
		//updatePreference(newServiceList);
    }
    
    public static void updatePreference(List<Service__c> newServiceList){
        Id limoRTId = Schema.SObjectType.Service__c.getRecordTypeInfosByName().get('Limo Service Booking').getRecordTypeId();
        Id restoRTId = Schema.SObjectType.Service__c.getRecordTypeInfosByName().get('Restaurant Booking').getRecordTypeId();
        Set<Id> contactIdSet = new Set<Id>();
		Set<Id> vipBookingIdSet = new Set<Id>();
        List<Service__c> updateServiceList = new List<Service__c>();
        Map<Id, Id> vipBookingContactIdMap = new Map<Id, Id>();
        Map<Id, Preferences__c> contactPreferencesMap = new Map<Id, Preferences__c>();
        
        try{
            for(Service__c serviceObj : newServiceList){//loop through trigger.new
                vipBookingIdSet.add(serviceObj.VIP_Booking__c);//save booking ID to get the contact
                contactIdSet.add(serviceObj.Contact__c);
            }
            for(Preferences__c prefObj : [SELECT Id, Transportation_Notes__c, Dining_Notes__c, Dietary__c, Patron__c FROM Preferences__c WHERE Patron__c IN : contactIdSet]){
                //get child preference record of the VIP Booking's contact
                contactPreferencesMap.put(prefObj.Patron__c, prefObj);//save the transpo note. used a map to pair the appropriate values
            }
            for(Service__c serviceObj : newServiceList){//loop through trigger.new again to populate the field
                if(serviceObj.RecordTypeId == limoRTId){//if Record Type is Limo, populate Car Type Preference
                    serviceObj.Preferences__c = contactPreferencesMap.get(serviceObj.Contact__c).Transportation_Notes__c;
                }
                if(serviceObj.RecordTypeId == restoRTId){//if Record Type is Resto, populate Dining Notes and Dietary Reqts
                    serviceObj.Dining_Notes__c = contactPreferencesMap.get(serviceObj.Contact__c).Dining_Notes__c;
                    serviceObj.Dietary_Requirements__c = contactPreferencesMap.get(serviceObj.Contact__c).Dietary__c;
                }
                updateServiceList.add(serviceObj);
            }
            
            if(!updateServiceList.isEmpty()){
                Database.update(updateServiceList, TRUE);
            }

        }catch(Exception excp){
            System.debug('@@@Error: ' + excp.getMessage());
            System.debug('@@@Error: ' + excp.getStackTraceString());
        }
    }
}