force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/CasinoBalance__c.field-meta.xml
<CustomField>
    <fullName>CasinoBalance__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/CompBalance__c.field-meta.xml
<CustomField>
    <fullName>CompBalance__c</fullName>
    <label>Comp $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Last_Successful_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Successful Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_To_Next_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_To_Next_Tier__c</fullName>
    <label>Points To Next Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_to_Retain_Current_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_to_Retain_Current_Tier__c</fullName>
    <label>Points to Retain Current Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Balance__c.field-meta.xml
<CustomField>
    <fullName>Tier_Balance__c</fullName>
    <label>Tier Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Month__c</fullName>
    <label>Tier Points Earned This Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Week__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Week__c</fullName>
    <label>Tier Points Earned This Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_Today__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_Today__c</fullName>
    <label>Tier Points Earned Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Review_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LoyaltyHelper.cls
/* Description: Helper class that returns the Loyalty record for the component
 * Author: Simplus
 * Date Created: 12/5/2022
 * History:
 * 12/5				JPalmero			Created
 */
public class LoyaltyHelper {
    @AuraEnabled(cacheable=true)
    public static Loyalty__c getLoyaltyInfo(Id contactId){
        try{
            Loyalty__c childLoyalty = [SELECT Id, Name, Tier_Review_Date__c, Tier_Balance__c, Points_to_Retain_Current_Tier__c, Points_To_Next_Tier__c, Tier_Points_Earned_Today__c, 
                                       Tier_Points_Earned_This_Week__c, Tier_Points_Earned_This_Month__c, CasinoBalance__c, 
                                       CompBalance__c, Last_Successful_Update__c   
                                       FROM Loyalty__c WHERE Patron__c =: contactId LIMIT 1];
            return childLoyalty;
        }catch(QueryException qExcp){
            throw new AuraHandledException('No Loyalty record returned');
        }
    }
}