force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/CasinoBalance__c.field-meta.xml
<CustomField>
    <fullName>CasinoBalance__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/CompBalance__c.field-meta.xml
<CustomField>
    <fullName>CompBalance__c</fullName>
    <label>Comp $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactLookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty (ContactLookup)</relationshipLabel>
    <relationshipName>Loyalty2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/Sales_Comp__c.object-meta.xml
<CustomObject>
    <label>Sales Comp</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Comp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Comps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Comps</relationshipLabel>
    <relationshipName>Sales_Comps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/recordTypes/CD_CP.recordType-meta.xml
<RecordType>
    <fullName>CD_CP</fullName>
    <active>true</active>
    <label>CD/CP</label>
</RecordType>

force-app/main/default/objects/Sales_Comp__c/recordTypes/Gift.recordType-meta.xml
<RecordType>
    <fullName>Gift</fullName>
    <active>true</active>
    <label>Gift</label>
</RecordType>

force-app/main/default/objects/Sales_Comp__c/recordTypes/SPV_MPV.recordType-meta.xml
<RecordType>
    <fullName>SPV_MPV</fullName>
    <active>true</active>
    <label>SPV</label>
</RecordType>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Statuses</relationshipLabel>
    <relationshipName>Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesCompController.cls
/**
 * @description       : Controller class for salesCompLWC
 * @author            : Simplus
 * @group             : Simplus
 * @last modified on  : 22-08-2022
 * @last modified by  : Simplus
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   22-08-2022   Simplus                      Initial Version
 */
public with sharing class SalesCompController {
    static final String SALES_COMP_RECORD_TYPE_NAME_CD_CP = 'CD_CP';
    static final String SALES_COMP_RECORD_TYPE_NAME_SPV_MPV = 'SPV_MPV';
    static final String SALES_COMP_RECORD_TYPE_NAME_GIFT = 'Gift';    
    static final String SALES_COMP_STATUS_APPROVED = 'Approved';

    public class ContactRecordWrapper {
        @AuraEnabled public Decimal cdCPtotal { get; set; }
        @AuraEnabled public Decimal spvMPVtotal { get; set; }
        @AuraEnabled public Decimal giftTotal { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static Loyalty__c getLoyaltyRecord(String contactId) {
        Loyalty__c loyalty = new Loyalty__c();
        loyalty = [SELECT CasinoBalance__c, CompBalance__c
                   FROM Loyalty__c
                   WHERE Patron__c = :contactId
                   LIMIT 1];
        return loyalty;
    }

    @AuraEnabled(cacheable=true)
    public static ContactRecordWrapper getSalesCompsTotal(String contactId) {
        ContactRecordWrapper wrapper = new ContactRecordWrapper();
        for (AggregateResult ar: [SELECT Contact__c, RecordType.DeveloperName, SUM(Amount__c)
                                  FROM Sales_Comp__c
                                  WHERE (Status__c = :SALES_COMP_STATUS_APPROVED AND
                                         CreatedDate = THIS_MONTH AND
                                         Contact__c = :contactId)
                                  GROUP BY Contact__c, RecordType.DeveloperName]) {
            String apiName = String.valueOf(ar.get('DeveloperName'));
            Decimal total = (Decimal) ar.get('expr0');
            if (apiName == SALES_COMP_RECORD_TYPE_NAME_CD_CP) {
                wrapper.cdCPtotal = total;
            } else if (apiName == SALES_COMP_RECORD_TYPE_NAME_SPV_MPV) {
                wrapper.spvMPVtotal = total;
            } else if (apiName == SALES_COMP_RECORD_TYPE_NAME_GIFT){
                wrapper.giftTotal = total;
            }
        }
        return wrapper;
    }
}