force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/CasinoBalance__c.field-meta.xml
<CustomField>
    <fullName>CasinoBalance__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/CompBalance__c.field-meta.xml
<CustomField>
    <fullName>CompBalance__c</fullName>
    <label>Comp $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Last_Successful_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Successful Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Balance__c.field-meta.xml
<CustomField>
    <fullName>Tier_Balance__c</fullName>
    <label>Tier Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyLastSuccessfulUpdateBatch.cls
/**
* @File Name          : LoyaltyLastSuccessfulUpdateBatch.apxc
* @Description        : Batch Job that runs everyday to update 'Last Succesful Update' field of up to 70000 Loyalty records
* @Author             : Gil Panican
* @Group              : Simplus
* @Last Modified By   : Gil Panican
* @Last Modified On   : 03/08/22
**/
global class LoyaltyLastSuccessfulUpdateBatch implements Database.Batchable<sObject>,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT External_ID__c,last_successful_update__C,CasinoBalance__c,CompBalance__c,Tier_Balance__c, LastModifiedDate FROM Loyalty__c WHERE (CasinoBalance__c <= 0 OR CasinoBalance__c = NULL) AND (CompBalance__c <= 0 OR CompBalance__c = NULL) and (Tier_Balance__c <= 0 OR Tier_Balance__c = NULL) and last_successful_update__C = null LIMIT 70000';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Loyalty__c> loyaltyList){
        System.debug('***Batch Started***');
        for (Loyalty__c loyaltyRec : loyaltyList){
            loyaltyRec.Last_Successful_Update__c = loyaltyRec.LastModifiedDate.format('dd/MM/yyyy, hh:mm a', + 'Australia/Sydney');
        }
        update loyaltyList;
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('***Batch Finished***');
    }
    
    global void execute(SchedulableContext sc) {
        LoyaltyLastSuccessfulUpdateBatch b = new LoyaltyLastSuccessfulUpdateBatch();
        Database.executebatch(b);
    }
}