force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Expiry_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Expiry_DateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiry DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Issue_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Issue_DateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Patron_Id__c.field-meta.xml
<CustomField>
    <fullName>Patron_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Property Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Sub_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sub Type Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Type_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StatusSelector.cls
public With Sharing class StatusSelector {
    // Define the fields to be queried
    private static final List<String> FIELDS = new List<String>{
        'Id',
            'Name',
            'Type__c',
            'Type_Description__c',
            'Code__c',
            'Description__c',
            'Sub_Type_Description__c',
            'Issue_DateTime__c',
            'Expiry_DateTime__c',
            'Message__c',
            'Property_Id__c',
            'Patron_Id__c',
            'CreatedDate'
            };
                
                
                // Method to build the SOQL query string
                private static String buildQueryString(String objectAPI, String whereClause) {
                    return 'SELECT ' + String.join(FIELDS, ', ') + ' FROM ' + objectAPI + ' WHERE ' + whereClause;
                }
    
    // Method to get records using status, type, and stop code
    public static List<Status__c> getStatusUsingCode(Set<string> patronIdSet, String stopCodeStr, string typeStr) {
        if (patronIdSet.isEmpty()) return new List<Status__c>();
        
        String whereClause = 'Patron_Id__c IN: patronIdSet ';
        whereClause += buildWhereClause('Code__c', stopCodeStr);
        whereClause += buildWhereClause('Type__c', typeStr);
        whereClause += ' ORDER BY LastModifiedDate ';
        return executeQuery('Status__c', whereClause, patronIdSet);
    }


    // Method to get only applied records 
    public static List<Status__c> getStatusUsingCodeApplied(Set<string> patronIdSet, string typeStr, String codeStr, String descriptionStr) {
        if (patronIdSet.isEmpty()) return new List<Status__c>();
        
        String whereClause = 'Patron_Id__c IN: patronIdSet ';
        whereClause += buildWhereClause('Type__c', typeStr);
        whereClause += buildWhereClause('Code__c', codeStr);
        whereClause += buildWhereClause('Description__c', descriptionStr);          
        
        return executeQuery('Status__c', whereClause, patronIdSet);
    }
    
    // Method to get only revoked records
    public static List<Status__c> getStatusUsingCodeRevoked(Set<string> patronIdSet, string typeStr, String codeStr, String descriptionStr) {
        if (patronIdSet.isEmpty()) return new List<Status__c>();
        
        String whereClause = 'Patron_Id__c IN: patronIdSet ';
        whereClause += buildWhereClause('Type__c', typeStr);
        whereClause += buildWhereClause('Code__c', codeStr);
        whereClause += buildWhereClause('Description__c', descriptionStr);          
        
        return executeQuery('Status__c', whereClause, patronIdSet);
    }    
     
    // Helper method to construct WHERE clauses
    private static String buildWhereClause(String field, String value) {
        return value != null && !string.isBlank(value) ? ' AND ' + field + ' = \'' + String.escapeSingleQuotes(value) + '\'' : '';
    }
    
    // Method to execute the query
    private static List<Status__c> executeQuery(String objectAPI, String whereClause, Set<string> patronIdSet) {
        String queryString = buildQueryString(objectAPI, whereClause);
        system.debug('Final Query '+queryString);
        return Database.query(queryString);
    }
    
}