force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Booking Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Cost_Centre__c.field-meta.xml
<CustomField>
    <fullName>Cost_Centre__c</fullName>
    <label>Cost Centre</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sydney - 1111</fullName>
            </value>
            <value>
                <fullName>Gold Coast - 1111</fullName>
            </value>
            <value>
                <fullName>Brisbane - 1111</fullName>
            </value>
            <value>
                <fullName>Interstate - 1712</fullName>
            </value>
            <value>
                <fullName>International - 1132</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Limo</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/VIP_Booking__c.field-meta.xml
<CustomField>
    <fullName>VIP_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIP Booking</label>
    <referenceTo>VIP_Booking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/VIP_Booking__c.object-meta.xml
<CustomObject>
    <label>VIP Booking</label>
    <nameField>
        <displayFormat>VIPB-{0000}</displayFormat>
        <label>VIP Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIP Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIP_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VIP Bookings</relationshipLabel>
    <relationshipName>VIP_Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/fields/Cost_Centre__c.field-meta.xml
<CustomField>
    <fullName>Cost_Centre__c</fullName>
    <label>Cost Centre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interstate – 1133</fullName>
            </value>
            <value>
                <fullName>International Rebate – 1121</fullName>
            </value>
            <value>
                <fullName>International Premium Mass &amp; Slots – 1132</fullName>
            </value>
            <value>
                <fullName>NSW &amp; QLD  – 1111</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIPBookingMigrationBatch.cls
/**
* @File Name          : VIPBookingMigrationBatch
* @Description        : Migrate VIP Booking records to Service records
* @Author             : JPalmero
* @Group              : Simplus
* @Last Modified By   : JPalmero
* @Last Modified On   : 17/01/23
**/
global class VIPBookingMigrationBatch implements Database.Batchable<sObject>{
    List<Service__c> updateServiceRecordList = new List<Service__c>();
    List<Id> vipBookingIdList = new List<Id>();
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Cost_Centre__c, VIP_Booking__c, Property__c, VIP_Booking__r.Property__c, 
                                         VIP_Booking__r.Cost_Centre__c, VIP_Booking__r.Contact__c, Contact__c FROM Service__c
                                         WHERE VIP_Booking__c != NULL]);
    }
    global void execute(Database.BatchableContext BC, List<Service__c> serviceList){
        for(Service__c serviceObj : serviceList){
            vipBookingIdList.add(serviceObj.VIP_Booking__c);
            serviceObj.Cost_Centre__c = serviceObj.VIP_Booking__r.Cost_Centre__c;
            serviceObj.Property__c = serviceObj.VIP_Booking__r.Property__c;
            serviceObj.Contact__c = serviceObj.VIP_Booking__r.Contact__c;
            if(serviceObj.VIP_Booking__r.Cost_Centre__c != NULL && serviceObj.VIP_Booking__r.Cost_Centre__c.contains('NSW & QLD')){
               serviceObj.Cost_Centre__c = 'NSW & QLD  – 1111';
                System.debug('@@@serviceObj.Cost_Centre__c ' + serviceObj.Cost_Centre__c);
            }
            updateServiceRecordList.add(serviceObj);
        }
        System.debug('@@@updateServiceRecordList ' + updateServiceRecordList);
        Database.update(updateServiceRecordList, true);
        
    }
    global void finish(Database.BatchableContext BC){
        
    }

}