force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Booking Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Depart_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Depart_Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Depart Date and Time (User Timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Limo</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/VIP_Booking__c.field-meta.xml
<CustomField>
    <fullName>VIP_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIP Booking</label>
    <referenceTo>VIP_Booking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/VIP_Booking__c.object-meta.xml
<CustomObject>
    <label>VIP Booking</label>
    <nameField>
        <displayFormat>VIPB-{0000}</displayFormat>
        <label>VIP Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIP Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIP_Booking__c/fields/Booking_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Booking Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VIP Bookings</relationshipLabel>
    <relationshipName>VIP_Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlightServiceExtractTest.cls
@isTest
public class FlightServiceExtractTest {
    @testSetup
    static void testDataFactory(){
        Contact testContact = TestDataFactory.createSingleContact('TestClass');
        
        VIP_Booking__c testVipBooking = new VIP_Booking__c();
        testVipBooking.Contact__c = testContact.Id;
        testVipBooking.Property__c = 'Sydney';
        INSERT testVipBooking;
        
    }
    static testmethod void callFlightServiceExtract(){
        VIP_Booking__c testBooking = [SELECT Id, Booking_Start_Date__c FROM VIP_Booking__c LIMIT 1];
        
        Service__c testServiceFl = new Service__c();
        testServiceFl.VIP_Booking__c = testBooking.Id;
        testServiceFl.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Flight Booking');
        testServiceFl.Property__c = 'Sydney';
        testServiceFl.Depart_Date_and_Time__c = System.today();
        INSERT testServiceFl;
        
        
        Test.StartTest(); 
        ApexPages.currentPage().getParameters().put('id',testServiceFl.Id);  
        ApexPages.StandardController sc = new ApexPages.StandardController(testServiceFl);
        FlightServiceExtract flightserviceRec = new FlightServiceExtract(sc);
        flightserviceRec.getOtherTraveller();
        flightserviceRec.getPatronDetails();
        flightserviceRec.getDevice();
        
        Test.StopTest();
        
    }
}