force-app/main/default/objects/Comp_Room_Nights_Detail__mdt/Comp_Room_Nights_Detail__mdt.object-meta.xml
<CustomObject>
    <label>Comp Room Nights Detail</label>
    <pluralLabel>Comp Room Nights Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/Comp_Room_Nights_Detail__mdt/fields/Comp_Room_Nights_Cust_Subscription_Key__c.field-meta.xml
<CustomField>
    <fullName>Comp_Room_Nights_Cust_Subscription_Key__c</fullName>
    <label>Comp Room Nights Cust Subscription Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comp_Room_Nights_Detail__mdt/fields/Comp_Room_Nights_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Comp_Room_Nights_Endpoint__c</fullName>
    <label>Comp Room Nights Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/Comp_Room_Night_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Comp_Room_Night_Entitlement__c</fullName>
    <label>Comp Nights Entitlement</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Comp_Room_Night_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Comp_Room_Night_Remaining__c</fullName>
    <label>Comp Nights for the Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Comp_Room_night_remaining_for_the_Month__c.field-meta.xml
<CustomField>
    <fullName>Comp_Room_night_remaining_for_the_Month__c</fullName>
    <label>Comp Nights for the Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Comp_Room_Night_Used__c.field-meta.xml
<CustomField>
    <fullName>Comp_Room_Night_Used__c</fullName>
    <label>Comp Room Night Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Last_Successful_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Successful Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CompRoomNightDataProvider.cls
public class CompRoomNightDataProvider {
    
    @AuraEnabled(cacheable=true)
    public static JsonResponse runCallOut(String loyaltyId){
        Loyalty__c loyaltyRec = [SELECT Id, Name, Patron__r.Patron_ID__c, Last_Successful_Update__c FROM Loyalty__c WHERE Id = :loyaltyId LIMIT 1];
        Comp_Room_Nights_Detail__mdt compRoomNightsRec= [SELECT Id, Comp_Room_Nights_Cust_Subscription_Key__c, Comp_Room_Nights_Endpoint__c FROM Comp_Room_Nights_Detail__mdt LIMIT 1];
        
        string endpoint = String.valueOf(compRoomNightsRec.Comp_Room_Nights_Endpoint__c);
        string customer_subscription_key = String.valueOf(compRoomNightsRec.Comp_Room_Nights_Cust_Subscription_Key__c);
        string method = 'GET';
        string patronId = loyaltyRec.Patron__r.Patron_ID__c;
        
        http h = new http();
        HttpRequest hr = new HttpRequest();
        
        //set endpoint and method
        hr.setEndpoint(endpoint);
        hr.setHeader('customer-subscription-key', customer_subscription_key);
        hr.setHeader('patronId', patronId);
        hr.setMethod(method);
        
        //send the request
        HttpResponse hResp = new HttpResponse();
        hResp = h.send(hr);
        
        String responseBody = hResp.getBody();
        system.debug('Test: ' + responseBody);
        JsonResponse jr = new JsonResponse();
        if(responseBody != null){
            JsonData jd = (JsonData)Json.deserialize(responseBody, JsonData.class);
            //system.debug('crnEntitlement+crnBalance = ' + jd.responseHeader + ' ' + jd.response);
            //system.debug('monthlyBalances ' + jd.monthlyBalances.month + ', ' + jd.monthlyBalances.year);
            system.debug('Test: ' + jd);
            
            jr = jd.response;	
        }
        return jr;
    }
    
    @AuraEnabled(cacheable=true)
    public static JsonResponse runCallOutSalesConsole(String contactId){
        Loyalty__c loyaltyRec = [SELECT Id, Name, Patron__r.Patron_ID__c, Last_Successful_Update__c FROM Loyalty__c WHERE Patron__c = :contactId LIMIT 1];
        Comp_Room_Nights_Detail__mdt compRoomNightsRec= [SELECT Id, Comp_Room_Nights_Cust_Subscription_Key__c, Comp_Room_Nights_Endpoint__c FROM Comp_Room_Nights_Detail__mdt LIMIT 1];
        
        string endpoint = String.valueOf(compRoomNightsRec.Comp_Room_Nights_Endpoint__c);
        string customer_subscription_key = String.valueOf(compRoomNightsRec.Comp_Room_Nights_Cust_Subscription_Key__c);
        string method = 'GET';
        string patronId = loyaltyRec.Patron__r.Patron_ID__c;
        
        http h = new http();
        HttpRequest hr = new HttpRequest();
        
        //set endpoint and method
        hr.setEndpoint(endpoint);
        hr.setHeader('customer-subscription-key', customer_subscription_key);
        hr.setHeader('patronId', patronId);
        hr.setMethod(method);
        
        //send the request
        HttpResponse hResp = new HttpResponse();
        hResp = h.send(hr);
        
        String responseBody = hResp.getBody();
        system.debug('Test: ' + responseBody);
        JsonResponse jr = new JsonResponse();
        if(responseBody != null){
            JsonData jd = (JsonData)Json.deserialize(responseBody, JsonData.class);
            //system.debug('crnEntitlement+crnBalance = ' + jd.responseHeader + ' ' + jd.response);
            //system.debug('monthlyBalances ' + jd.monthlyBalances.month + ', ' + jd.monthlyBalances.year);
            system.debug('Test: ' + jd);
            
            jr = jd.response;	
        }
        return jr;
    }
    
    @AuraEnabled(cacheable=true)
    public static string getLoyaltyRec(String loyaltyId){
        string formattedDate;
        Loyalty__c loyaltyRec = [SELECT Id, Last_Successful_Update__c, Comp_Room_Night_Entitlement__c, Comp_Room_Night_Used__c, Comp_Room_night_remaining_for_the_Month__c, Comp_Room_Night_Remaining__c FROM Loyalty__c WHERE Id = :loyaltyId LIMIT 1];
        if(loyaltyRec.Last_Successful_Update__c != null){
            if(loyaltyRec.Last_Successful_Update__c.contains('T')){
                formattedDate = DateTime.ValueofGmt(loyaltyRec.Last_Successful_Update__c.replace('T', ' ')).format('dd/MM/yyyy, hh:mm a', + 'Pacific');
            }
            else{
                formattedDate = loyaltyRec.Last_Successful_Update__c;
            }
        }
        
        return formattedDate;
    }
    public class JsonData{
        public JsonResponseHeader responseHeader;
        public JsonResponse response;
    }
    
    public class JsonResponseHeader{
        public string code;
        public string msg;
    }
    
    public class JsonResponse{
        @AuraEnabled
        public string entitlement { get; set; }
        @AuraEnabled
        public string balance { get; set; }
        @AuraEnabled
        public JsonMonthlyBalances[] monthlyBalances { get; set; }
    }
    
    public class JsonMonthlyBalances{
        @AuraEnabled
        public string month;
        @AuraEnabled
        public string year;
        @AuraEnabled
        public string used;
        @AuraEnabled
        public string remaining;
    }
    public static JsonResponse parse(String jsonString) {
        return (JsonResponse)JSON.deserialize(jsonString, JsonResponse.class);
    }
}