force-app/main/default/objects/Sales_Comp__c/Sales_Comp__c.object-meta.xml
<CustomObject>
    <label>Sales Comp</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Comp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Comps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Comp_Type__c.field-meta.xml
<CustomField>
    <fullName>Comp_Type__c</fullName>
    <label>Comp Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SPV</fullName>
            </value>
            <value>
                <fullName>Casino Dollar</fullName>
            </value>
            <value>
                <fullName>Comp Dollar</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Soft Cost</fullName>
            </value>
            <value>
                <fullName>MPV</fullName>
                <isActive>false</isActive>
                <label>MPV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Comps</relationshipLabel>
    <relationshipName>Sales_Comps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/recordTypes/CD_CP.recordType-meta.xml
<RecordType>
    <fullName>CD_CP</fullName>
    <active>true</active>
    <label>CD/CP</label>
</RecordType>

force-app/main/default/classes/SalesCompPrintableViewExtensionTest.cls
/**
 * @description       : Test class for SalesCompPrintableViewExtension
 * @author            : Simplus
 * @group             : Simplus
 * @last modified on  : 22-08-2022
 * @last modified by  : Simplus
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   22-08-2022   Simplus                      Initial Version
 */
@isTest
public class SalesCompPrintableViewExtensionTest {

    @testSetup
    static void testDataFactory() {
        Profile sysAd = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        UserRole testRole = [SELECT Id FROM UserRole WHERE Name = 'PGM Syd'];
        User testAdminUser = new User();
        testAdminUser.FirstName = 'Test Admin';
        testAdminUser.LastName = 'Star User';
        testAdminUser.Email = 'testAdminUser@starTest.com';
        testAdminUser.Alias = 'tasu';
        testAdminUser.Username = 'testAdminUser@starTest.com';
        testAdminUser.CommunityNickname = 'TestUser';
        testAdminUser.ProfileId = sysAd.Id;
        testAdminUser.UserRoleId = testRole.Id;
        testAdminUser.TimeZoneSidKey = 'Australia/Sydney';
        testAdminUser.LocaleSidKey = 'en_AU';
        testAdminUser.EmailEncodingKey = 'ISO-8859-1';
        testAdminUser.LanguageLocaleKey = 'en_US';
        insert testAdminUser;        
    }

    @isTest static void extensionApprovedTest() {
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'testcontact@maildrop.cc'
        );
        insert testContact;

        Id cdCPrtId = Schema.SObjectType.Sales_Comp__c.getRecordTypeInfosByDeveloperName().get('CD_CP').getRecordTypeId();

        Sales_Comp__c scCD = new Sales_Comp__c(
            Amount__c = 100,
            Comp_Type__c = 'Casino Dollar',
            Contact__c = testContact.Id,
            RecordTypeId = cdCPrtId
        );
        insert scCD;

        User adminUser = [SELECT Id FROM User WHERE Username = 'testAdminUser@starTest.com' LIMIT 1];

        // Submit for Approval
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(scCD.Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new List<Id>{ adminUser.Id });
        req1.setProcessDefinitionNameOrId('Sales_Comp_Approval_Process_1');
        Approval.ProcessResult result1 = Approval.process(req1);

        // Approve
        Approval.ProcessWorkitemRequest pwr = new Approval.ProcessWorkitemRequest();
        pwr.setAction('Approve');
        ProcessInstanceWorkitem piwItem = [SELECT Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId = :scCD.Id];
        pwr.setWorkitemId(piwItem.Id);
        Approval.ProcessResult pwrResult = Approval.process(pwr);

        Boolean isCDCP = false;
        Boolean isApproved = false;
        Test.startTest();
            PageReference testPage = Page.SalesCompPrintableView;
            Test.setCurrentPage(testPage);
            testPage.getParameters().put('id', String.valueOf(scCD.Id));

            ApexPages.StandardController sc = new ApexPages.StandardController(scCD);
            SalesCompPrintableViewExtension ext = new SalesCompPrintableViewExtension(sc);

            isCDCP = ext.getRecordType();
            isApproved = ext.getRecordStatus();
            String deviceRenderedAs = ext.getDevice();

            Boolean withSubmitter = ext.getSubmitterName();
            Boolean withAuthoriser = ext.getAuthoriserName();
        Test.stopTest();
    }

    @isTest static void extensionRejectedTest() {
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'testcontact@maildrop.cc'
        );
        insert testContact;

        Id cdCPrtId = Schema.SObjectType.Sales_Comp__c.getRecordTypeInfosByDeveloperName().get('CD_CP').getRecordTypeId();

        Sales_Comp__c scCD = new Sales_Comp__c(
            Amount__c = 100,
            Comp_Type__c = 'Casino Dollar',
            Contact__c = testContact.Id,
            RecordTypeId = cdCPrtId
        );
        insert scCD;

        User adminUser = [SELECT Id FROM User WHERE Username = 'testAdminUser@starTest.com' LIMIT 1];

        // Submit for Approval
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(scCD.Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new List<Id>{ adminUser.Id });
        req1.setProcessDefinitionNameOrId('Sales_Comp_Approval_Process_1');
        Approval.ProcessResult result1 = Approval.process(req1);

        // Reject
        Approval.ProcessWorkitemRequest pwr = new Approval.ProcessWorkitemRequest();
        pwr.setAction('Reject');
        ProcessInstanceWorkitem piwItem = [SELECT Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId = :scCD.Id];
        pwr.setWorkitemId(piwItem.Id);
        Approval.ProcessResult pwrResult = Approval.process(pwr);

        Boolean isCDCP = false;
        Boolean isApproved = false;
        Test.startTest();
            PageReference testPage = Page.SalesCompPrintableView;
            Test.setCurrentPage(testPage);
            testPage.getParameters().put('id', String.valueOf(scCD.Id));

            ApexPages.StandardController sc = new ApexPages.StandardController(scCD);
            SalesCompPrintableViewExtension ext = new SalesCompPrintableViewExtension(sc);

            isCDCP = ext.getRecordType();
            isApproved = ext.getRecordStatus();
            String deviceRenderedAs = ext.getDevice();

            Boolean withSubmitter = ext.getSubmitterName();
            Boolean withAuthoriser = ext.getAuthoriserName();
        Test.stopTest();
    }
}