force-app/main/default/objects/Portal_Client_Credentials__mdt/Portal_Client_Credentials__mdt.object-meta.xml
<CustomObject>
    <label>Portal Client Credentials</label>
    <pluralLabel>Portal Client Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Client_Credentials__mdt/fields/x_seg_clientid__c.field-meta.xml
<CustomField>
    <fullName>x_seg_clientid__c</fullName>
    <label>x-seg-clientid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Portal_LoyaltyConversionInitiated__c.field-meta.xml
<CustomField>
    <fullName>Portal_LoyaltyConversionInitiated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal_LoyaltyConversionInitiated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Portal_ReLoginRequired__c.field-meta.xml
<CustomField>
    <fullName>Portal_ReLoginRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal_ReLoginRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Custom Field created for Member Portal to store the ID_Token passed from Ping One Auth provider for Portal users.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Token_A__c.field-meta.xml
<CustomField>
    <fullName>Token_A__c</fullName>
    <description>Custom Field created for Member Portal to store access token returned from Ping One Auth Provider for Portal User.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token A</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PortalExcludedUserCheckController.cls
public with sharing class PortalExcludedUserCheckController {
    @AuraEnabled
    public static String getUserDetails(){
        Id uId = UserInfo.getUserId();
        String resultStatus = 'FALSE';
        
        try {
            // Query the User object to include Portal_ReLoginRequired__c
            User us = [SELECT Id, token__c, token_a__c, Portal_ReLoginRequired__c,Portal_LoyaltyConversionInitiated__c FROM User WHERE Id = :uId];
            // Check if Portal_ReLoginRequired__c is true
            if(us.Portal_ReLoginRequired__c) {
                // Set Portal_ReLoginRequired__c to false
                us.Portal_ReLoginRequired__c = false;
                update us;
                
                /*
                // Invalidate all sessions (log out from all devices)
                List<AuthSession> sessions = [SELECT Id FROM AuthSession WHERE UsersId = :uId];
                if (!sessions.isEmpty()) {
                delete sessions; // This deletes all sessions for the user, logging them out globally
                }*/
                
                // Return 'RELOGIN_REQUIRED' and exit since user needs to relogin
                return 'RELOGIN_REQUIRED';
            }
            else if(us.Portal_LoyaltyConversionInitiated__c) {
                // Return 'RELOGIN_REQUIRED' and exit since user needs to relogin
                return 'LOYALTY_CONVERSION_INITIATED';
            }
            
            // Proceed with existing logic if Portal_ReLoginRequired__c is false
            AuthProvider authProvider = [SELECT Id, FriendlyName FROM AuthProvider LIMIT 1];
            String accessToken = Auth.AuthToken.getAccessToken(authProvider.Id, authProvider.FriendlyName);
            Portal_Client_Credentials__mdt userinfo = [SELECT Id, Client_ID__c, Client_Secret__c, Endpoint_URL__c, x_seg_clientid__c 
                                                       FROM Portal_Client_Credentials__mdt 
                                                       WHERE MasterLabel = 'Userinfo API'];
            
            // Only mock the refreshToken map for test scenarios
            Map<String, String> refreshToken = new Map<String, String>();
            
            // If running test, set the values manually, otherwise call the actual method
            if (Test.isRunningTest()) {
                refreshToken.put('AccessToken', null);
                refreshToken.put('RefreshError', 'Access token was not returned');
            } else {
                // Actual method call when not in test
                refreshToken = Auth.AuthToken.refreshAccessToken(authProvider.Id, authProvider.FriendlyName, accessToken);
            }
            accessToken = refreshToken.get('AccessToken');
            
            // Setup HTTP request to the user info API
            HttpRequest req = new HttpRequest();
            req.setHeader('Authorization', 'Bearer ' + us.token_a__c);
            req.setEndpoint(userinfo.Endpoint_URL__c);
            req.setHeader('x-seg-clientid', 'Web');
            req.setHeader('x-id-token', us.token__c);
            req.setMethod('GET');
            
            Http http = new Http();
            HTTPResponse res = http.send(req);
            String responseBody = res.getBody();
            system.debug('user info response body-> ' + responseBody);
            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(responseBody);
            
            // Check if user is excluded based on the API response
            String isExcluded = (String) responseMap.get('isExcluded');
            if('TRUE'.equalsIgnoreCase(isExcluded)) {
                resultStatus = 'EXCLUDED';
            }
        } catch (Exception e) {
            // Log any exception for debugging and monitoring purposes
            ErrorLogger.createLog('PortalExcludedUserCheckController', 'getUserDetails', e, '', 'Apex Class');
        }
        
        return resultStatus;
    }
}