force-app/main/default/objects/Exl_Exclusion__c/Exl_Exclusion__c.object-meta.xml
<CustomObject>
    <description>This object serves as the authoritative source for all patron-related restrictions and exclusions.</description>
    <label>Exclusion</label>
    <nameField>
        <displayFormat>1{00000}</displayFormat>
        <label>Exclusion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/fields/ApplyCase__c.field-meta.xml
<CustomField>
    <fullName>ApplyCase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The original case that triggered this exclusion</description>
    <label>Apply Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions_Apply</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Source of the Exclusion</description>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Safer Gambling</fullName>
            </value>
            <value>
                <fullName>Crown</fullName>
            </value>
            <value>
                <fullName>Police Exclusion</fullName>
            </value>
            <value>
                <fullName>Investigations</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>The Reef (Qld)</fullName>
            </value>
            <value>
                <fullName>The Ville (Qld)</fullName>
            </value>
            <value>
                <fullName>Asset Protection</fullName>
            </value>
            <value>
                <fullName>Reg Affairs</fullName>
            </value>
            <value>
                <fullName>AML</fullName>
            </value>
            <value>
                <fullName>NICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/POE_Type__c.field-meta.xml
<CustomField>
    <fullName>POE_Type__c</fullName>
    <description>Type of exclusion</description>
    <label>POE Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External Exclusion - Group Wide</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - Group Wide</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - NSW</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - QLD</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - Group Wide</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - NSW</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - QLD</fullName>
            </value>
            <value>
                <fullName>TP24HR</fullName>
            </value>
            <value>
                <fullName>TP7DAY</fullName>
            </value>
            <value>
                <fullName>Venue - Group Wide</fullName>
            </value>
            <value>
                <fullName>WOL - Property - Group Wide</fullName>
            </value>
            <value>
                <fullName>Interstate - CCA</fullName>
            </value>
            <value>
                <fullName>Interstate – CCA</fullName>
                <isActive>false</isActive>
                <label>Interstate – CCA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/RevokeCase__c.field-meta.xml
<CustomField>
    <fullName>RevokeCase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case  which triggered this revocation</description>
    <label>Revoke Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Exclusions (Revoke Case)</relationshipLabel>
    <relationshipName>Exclusions_Revoke</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExclusionChoiceActionsTest.cls
@IsTest
public class ExclusionChoiceActionsTest {

    
    @TestSetup
    static void setupData() {
        // Create Contact
        Contact c = new Contact(LastName = 'Test Contact');
        insert c;
    
        // Create Case
        Case ca = new Case(ContactId = c.Id, Subject = 'Test Case', Origin = 'Phone', Status = 'New');
        insert ca;
    
        // Create Exclusions for both ApplyCase__c and RevokeCase__c
        List<Exl_Exclusion__c> exclusions = new List<Exl_Exclusion__c>{
            // For GetExclusionGroupChoicesAction
            new Exl_Exclusion__c(ApplyCase__c = ca.Id, POE_Type__c = 'Self Exclusion - NSW', Origin__c = 'Crown'),
    
            // For GetExclusionChoicesAction
            new Exl_Exclusion__c(RevokeCase__c = ca.Id, POE_Type__c = 'Self Exclusion - QLD', Origin__c = 'Crown')
        };
        insert exclusions;
    }


	@IsTest
    static void testGetExclusionGroupChoicesAction() {
        Contact c = [SELECT Id FROM Contact LIMIT 1];
    
        GetExclusionGroupChoicesAction.Input input = new GetExclusionGroupChoicesAction.Input();
        input.contactId = c.Id;
        input.maxItemsInLabel = 5;
    
        List<GetExclusionGroupChoicesAction.Output> result =
            GetExclusionGroupChoicesAction.getChoices(new List<GetExclusionGroupChoicesAction.Input>{ input });
    
        System.assertEquals(1, result.size(), 'Should return one Output');
        System.assert(result[0].entries.size() > 0, 'Should return at least one group entry');
    
        for (ExlExclusionChoiceItem item : result[0].entries) {
            System.debug('Group Label: ' + item.label);
            System.debug('Group Value (CaseId): ' + item.value);
            System.assertNotEquals(null, item.label, 'Label should not be null');
            System.assertNotEquals(null, item.value, 'Value should not be null');
        }
    }


    @IsTest
    static void testGetExclusionChoicesAction() {
        Contact c = [SELECT Id FROM Contact LIMIT 1];
    
        GetExclusionChoicesAction.Input input = new GetExclusionChoicesAction.Input();
        input.contactId = c.Id;
    
        List<GetExclusionChoicesAction.Output> result =
            GetExclusionChoicesAction.getChoices(new List<GetExclusionChoicesAction.Input>{ input });
    
        System.assertEquals(1, result.size(), 'Should return one Output');
        System.assert(result[0].entries.size() > 0, 'Should return individual exclusions');
    
        for (ExlExclusionChoiceItem item : result[0].entries) {
            System.debug('Exclusion Label: ' + item.label);
            System.debug('Exclusion Value (Exclusion Id): ' + item.value);
            System.assertNotEquals(null, item.label, 'Label should not be null');
            System.assertNotEquals(null, item.value, 'Value should not be null');
        }
    }

}