force-app/main/default/objects/Exl_Exclusion__c/Exl_Exclusion__c.object-meta.xml
<CustomObject>
    <description>This object serves as the authoritative source for all patron-related restrictions and exclusions.</description>
    <label>Exclusion</label>
    <nameField>
        <displayFormat>1{00000}</displayFormat>
        <label>Exclusion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related patron</description>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Event_Log__e/Internal_Event_Log__e.object-meta.xml
<CustomObject>
    <label>Internal Event Log</label>
    <pluralLabel>Internal Event Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Internal_Event_Log__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExclusionTriggerService.cls
public class ExclusionTriggerService extends TriggerHandlerBase {
    
    //new method which is required when we extend the TriggerHandlerBase class
    public ExclusionTriggerService(String triggerName) {
        super(triggerName);
    }
    
    public override void afterDelete(List<SObject> oldSObjectList, Map<ID, SObject> oldSObjectMap){
        List<Internal_Event_Log__e> eventsToPublish = new List<Internal_Event_Log__e>();
        Set<Id> contactIds = new Set<Id>();
        
        for(id ExclusionId : oldSObjectMap.keySet()){
            if (oldSObjectMap != null && oldSObjectMap.containsKey(ExclusionId)) {
                SObject sobj = oldSObjectMap.get(ExclusionId);
                if (sobj instanceof Exl_Exclusion__c) {
                    Exl_Exclusion__c oldExclusion = (Exl_Exclusion__c) sobj;
                    contactIds.add(oldExclusion.Contact__c);
                }
            }
        }
        if (contactIds != null && !contactIds.isEmpty()) {
            for(Id conId : contactIds){
                eventsToPublish.add(new Internal_Event_Log__e(
                    Record_Id__c = conId,
                    Source__c = 'ExclusionTrigger'
                ));
            }
        }
        
        if (!eventsToPublish.isEmpty()) {
            List<Database.SaveResult> results = EventBus.publish(eventsToPublish);
        }
    }
    public override void afterUndelete(List<SObject> newRecords, Map<ID, SObject> newRecordMap){
        List<Internal_Event_Log__e> eventsToPublish = new List<Internal_Event_Log__e>();
        Set<Id> contactIds = new Set<Id>();
        
        for(id ExclusionId : newRecordMap.keySet()){
            if (newRecordMap != null && newRecordMap.containsKey(ExclusionId)) {
                SObject sobj = newRecordMap.get(ExclusionId);
                if (sobj instanceof Exl_Exclusion__c) {
                    Exl_Exclusion__c oldExclusion = (Exl_Exclusion__c) sobj;
                    contactIds.add(oldExclusion.Contact__c);
                }
            }
        }
        if (contactIds != null && !contactIds.isEmpty()) {
            for(Id conId : contactIds){
                eventsToPublish.add(new Internal_Event_Log__e(
                    Record_Id__c = conId,
                    Source__c = 'ExclusionTrigger'
                ));
            }
        }
        if (!eventsToPublish.isEmpty()) {
            List<Database.SaveResult> results = EventBus.publish(eventsToPublish);
        }
        
    }
    
    public override void beforeInsert(List<SObject> newSObjectList){
    }
    
    public override void beforeUpdate(List<SObject> oldSObjectList, List<SObject> newSObjectList, Map<ID, SObject> oldSObjectMap, Map<ID, SObject> newSObjectMap){
    }
    
    public override void afterInsert(List<SObject> newSObjectList, Map<ID, SObject> newSObjectMap){
    }
    
    public override void afterUpdate(List<SObject> oldSObjectList, List<SObject> newSObjectList, Map<ID, SObject> oldSObjectMap, Map<ID, SObject> newSObjectMap){
    }
    
}