force-app/main/default/objects/Exl_Exclusion__c/Exl_Exclusion__c.object-meta.xml
<CustomObject>
    <description>This object serves as the authoritative source for all patron-related restrictions and exclusions.</description>
    <label>Exclusion</label>
    <nameField>
        <displayFormat>1{00000}</displayFormat>
        <label>Exclusion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related patron</description>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/RecalculateDLRS__c.field-meta.xml
<CustomField>
    <fullName>RecalculateDLRS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RecalculateDLRS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date the exclusion was recorded</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Internal_Event_Log__e/Internal_Event_Log__e.object-meta.xml
<CustomObject>
    <label>Internal Event Log</label>
    <pluralLabel>Internal Event Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Internal_Event_Log__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExclusionRollupBatch.cls
global class ExclusionRollupBatch implements Database.Batchable<SObject>, Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, RecalculateDLRS__c, Contact__c, Start_Date__c
            FROM Exl_Exclusion__c 
            WHERE Start_Date__c >= LAST_N_DAYS:39 OR RecalculateDLRS__c = true
        ]);
    }
    
    global void execute(Database.BatchableContext bc, List<exl_exclusion__c> scope) {
        List<Internal_Event_Log__e> eventsToPublish = new List<Internal_Event_Log__e>();
        
        Set<Id> contactIds = new Set<Id>();
        List<exl_exclusion__c> exlToBeUpdated = new List<exl_exclusion__c>();
        
        for(exl_exclusion__c rec : scope) {
            contactIds.add(rec.Contact__c);
            if(rec.RecalculateDLRS__c == true){
                rec.RecalculateDLRS__c = false;
            	exlToBeUpdated.add(rec);
            }
        }
        if (contactIds != null && !contactIds.isEmpty()) {
            for(Id conId : contactIds){
                eventsToPublish.add(new Internal_Event_Log__e(
                    Record_Id__c = conId,
                    Source__c = 'ExclusionRollupBatch'
                ));
            }
        }
        
        if (!eventsToPublish.isEmpty()) {
            List<Database.SaveResult> results = EventBus.publish(eventsToPublish);
        }
        
        if(!exlToBeUpdated.isEmpty()){
            update exlToBeUpdated;
        }
        
    }
    
    public void finish(Database.BatchableContext bc){
    }
}