force-app/main/default/objects/Exl_Exclusion__c/Exl_Exclusion__c.object-meta.xml
<CustomObject>
    <description>This object serves as the authoritative source for all patron-related restrictions and exclusions.</description>
    <label>Exclusion</label>
    <nameField>
        <displayFormat>1{00000}</displayFormat>
        <label>Exclusion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related patron</description>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/RecalculateDLRS__c.field-meta.xml
<CustomField>
    <fullName>RecalculateDLRS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RecalculateDLRS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExclusionRollupSchedulerTest.cls
@isTest
private class ExclusionRollupSchedulerTest {

    private static List<exl_exclusion__c> setupTestData() {
        List<exl_exclusion__c> exclusions = new List<exl_exclusion__c>();
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert testContact;

        for (Integer i = 0; i < 10; i++) {
            exclusions.add(new exl_exclusion__c(
                RecalculateDLRS__c = true,
                Contact__c = testContact.Id
            ));
        }
        insert exclusions;
        return exclusions;
    }

    @isTest
    static void testSchedulerExecution() {
        // Setup test data
        List<exl_exclusion__c> exclusions = setupTestData();

        // Schedule the job
        Test.startTest();
        String jobId = System.schedule('Test Exclusion Rollup Scheduler', '0 0 0 * * ?', new ExclusionRollupScheduler());
        Test.stopTest();

    }
}