force-app/main/default/objects/Exl_Exclusion__c/Exl_Exclusion__c.object-meta.xml
<CustomObject>
    <description>This object serves as the authoritative source for all patron-related restrictions and exclusions.</description>
    <label>Exclusion</label>
    <nameField>
        <displayFormat>1{00000}</displayFormat>
        <label>Exclusion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/fields/Behaviour__c.field-meta.xml
<CustomField>
    <fullName>Behaviour__c</fullName>
    <description>Behaviour leading to exclusion</description>
    <label>Behaviour</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Behaviour</fullName>
            </value>
            <value>
                <fullName>Cheating</fullName>
            </value>
            <value>
                <fullName>CLAGCA Ban</fullName>
            </value>
            <value>
                <fullName>CLAGCA Exclusion</fullName>
            </value>
            <value>
                <fullName>Exec. Exclusion Comm</fullName>
            </value>
            <value>
                <fullName>External-External</fullName>
            </value>
            <value>
                <fullName>Gaming Incident</fullName>
            </value>
            <value>
                <fullName>Illegal/Undesirable</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Problem-Responsible Gaming</fullName>
            </value>
            <value>
                <fullName>Responsible Gaming</fullName>
            </value>
            <value>
                <fullName>RSA Non Vol Accord</fullName>
            </value>
            <value>
                <fullName>RSA Non Vol Casino</fullName>
            </value>
            <value>
                <fullName>Section 81</fullName>
            </value>
            <value>
                <fullName>Self- Voluntary Exclusion</fullName>
            </value>
            <value>
                <fullName>Self-Liquor Exclusion</fullName>
            </value>
            <value>
                <fullName>Theft</fullName>
            </value>
            <value>
                <fullName>Unattended Children</fullName>
            </value>
            <value>
                <fullName>Venue-AML</fullName>
            </value>
            <value>
                <fullName>Venue-Behaviour</fullName>
            </value>
            <value>
                <fullName>Venue-Cheating</fullName>
            </value>
            <value>
                <fullName>Venue-Exec. ExclusionCommittee</fullName>
            </value>
            <value>
                <fullName>Venue-Gaming Incident</fullName>
            </value>
            <value>
                <fullName>Venue-Gamng-Dishonest Act</fullName>
            </value>
            <value>
                <fullName>Venue-Illegal/Undesirable</fullName>
            </value>
            <value>
                <fullName>Venue-Other</fullName>
            </value>
            <value>
                <fullName>Venue-Police Direction Sect 81</fullName>
            </value>
            <value>
                <fullName>Venue-Theft</fullName>
            </value>
            <value>
                <fullName>Venue-Unattended Children</fullName>
            </value>
            <value>
                <fullName>Venue-Unlawful Conduct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related patron</description>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Jurisdiction</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/POE_Length__c.field-meta.xml
<CustomField>
    <fullName>POE_Length__c</fullName>
    <description>Duration of the Exclusion</description>
    <label>POE Length</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24h</fullName>
            </value>
            <value>
                <fullName>7d</fullName>
            </value>
            <value>
                <fullName>3m</fullName>
            </value>
            <value>
                <fullName>6m</fullName>
            </value>
            <value>
                <fullName>1y</fullName>
            </value>
            <value>
                <fullName>2y</fullName>
            </value>
            <value>
                <fullName>3y</fullName>
            </value>
            <value>
                <fullName>4y</fullName>
            </value>
            <value>
                <fullName>5y</fullName>
            </value>
            <value>
                <fullName>Indefinite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/POE_Type__c.field-meta.xml
<CustomField>
    <fullName>POE_Type__c</fullName>
    <description>Type of exclusion</description>
    <label>POE Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External Exclusion - Group Wide</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - Group Wide</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - NSW</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - QLD</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - Group Wide</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - NSW</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - QLD</fullName>
            </value>
            <value>
                <fullName>TP24HR</fullName>
            </value>
            <value>
                <fullName>TP7DAY</fullName>
            </value>
            <value>
                <fullName>Venue - Group Wide</fullName>
            </value>
            <value>
                <fullName>WOL - Property - Group Wide</fullName>
            </value>
            <value>
                <fullName>Interstate - CCA</fullName>
            </value>
            <value>
                <fullName>Interstate – CCA</fullName>
                <isActive>false</isActive>
                <label>Interstate – CCA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Originating venue</description>
    <label>POE Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>The Star Sydney</fullName>
            </value>
            <value>
                <fullName>The Star Brisbane</fullName>
            </value>
            <value>
                <fullName>The Star Gold Coast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Revocation_Date__c.field-meta.xml
<CustomField>
    <fullName>Revocation_Date__c</fullName>
    <description>The date the exclusion is revoked</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Revocation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date the exclusion was recorded</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of exclusion restriction</description>
    <label>Restriction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Exclusion Draft</fullName>
            </value>
            <value>
                <fullName>Revocation Draft</fullName>
            </value>
            <value>
                <fullName>Activation Failed</fullName>
            </value>
            <value>
                <fullName>Revocation Failed</fullName>
            </value>
            <value>
                <fullName>Exclusion Pending</fullName>
            </value>
            <value>
                <fullName>Revocation Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_POE_Type__mdt/Exl_POE_Type__mdt.object-meta.xml
<CustomObject>
    <label>POE Type</label>
    <pluralLabel>POE Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Exl_POEType_ID_Mapping__mdt/Exl_POEType_ID_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>POEType Vs ID Mapping</label>
    <pluralLabel>POETypes Vs IDs Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Exl_POEType_ID_Mapping__mdt/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>Qld</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_POEType_ID_Mapping__mdt/fields/POE_Type__c.field-meta.xml
<CustomField>
    <fullName>POE_Type__c</fullName>
    <label>POE Type</label>
    <referenceTo>Exl_POE_Type__mdt</referenceTo>
    <relationshipLabel>POETypes Vs IDs Mapping</relationshipLabel>
    <relationshipName>POETypes_Vs_IDs_Mapping</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Exl_POEType_ID_Mapping__mdt/fields/POEType_Id__c.field-meta.xml
<CustomField>
    <fullName>POEType_Id__c</fullName>
    <label>POEType_Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Statuses</relationshipLabel>
    <relationshipName>Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Exl_SFEventToAzureService_PEBody.cls
public with sharing class Exl_SFEventToAzureService_PEBody {
    public class FlowInputWrapper {
        @InvocableVariable(required=true) public Exl_Exclusion__c exclusionRecord;
    }

    public class FlowOutputWrapper {
        @InvocableVariable public List<String> serialised_PE_PayLoads;
        @InvocableVariable public String error;
    }

    @InvocableMethod(
        label='returnPlatformEventBody'
        description='returnPlatformEventBody'
    )
    public static List<FlowOutputWrapper> returnPlatformEventBody(List<FlowInputWrapper> reqs) {
        List<FlowOutputWrapper> outs = new List<FlowOutputWrapper>();
        Map<String, String> sourceNameMap = new Map<String, String>{
            'The Star Sydney' => 'SC',
            'The Star Brisbane' => 'CT',
            'The Star Gold Coast' => 'CJ'
        };

        for (FlowInputWrapper req : reqs) {
            FlowOutputWrapper out = new FlowOutputWrapper();
            out.serialised_PE_PayLoads = new List<String>();

            try {
                Exl_Exclusion__c exclusionRecord = req.exclusionRecord;
                system.debug('exclusionRecord:: ' + exclusionRecord);

                // Fetch the linked patron
                Contact exlPatron = getExlPatron(exclusionRecord.Contact__c);
                if (exlPatron != null) {
                    Exl_PlatformEvent_JSONBody bodyWrapper = new Exl_PlatformEvent_JSONBody();
                    populateBodyWrapper(bodyWrapper, exclusionRecord, exlPatron, sourceNameMap);

                    // Serialize the payload and add to the list
                    out.serialised_PE_PayLoads.add(JSON.serialize(bodyWrapper));
                } else {
                    // Handle missing patron
                    out.error = 'Unexpected error: No Linked Patron Found';
                }
            } catch (Exception ex) {
                // Log the exception and return a generic error
                System.debug(LoggingLevel.ERROR, 'Error in processing exclusion record: ' + ex.getMessage());
                out.error = 'Unexpected error: ' + ex.getMessage();
            }

            outs.add(out);
        }

        return outs;
    }

    private static void populateBodyWrapper(
        Exl_PlatformEvent_JSONBody bodyWrapper,
        Exl_Exclusion__c exclusionRecord,
        Contact exlPatron,
        Map<String, String> sourceNameMap
    ) {
        bodyWrapper.surname = exlPatron.LastName;
        bodyWrapper.firstName = exlPatron.FirstName;
        bodyWrapper.dob = exlPatron.Date_of_Birth__c;

        bodyWrapper.exclusionNumber = exclusionRecord.Name;
        bodyWrapper.exclusionReason = exclusionRecord.Behaviour__c;

        bodyWrapper.poeType = exclusionRecord.POE_Type__c;
        bodyWrapper.poeTypeID = getPOETypeId(exclusionRecord.POE_Type__c, exclusionRecord.Jurisdiction__c);
        bodyWrapper.poeLength = exclusionRecord.POE_Length__c;

        bodyWrapper.isExcluded = isExclusionPendingOrFailed(exclusionRecord.Status__c);
        bodyWrapper.sourceName = sourceNameMap.get(exclusionRecord.Property__c);

        bodyWrapper.issuedDate = exclusionRecord.Start_Date__c;
        bodyWrapper.accountIssuedDate = exclusionRecord.Start_Date__c;

        bodyWrapper.revocationDate = exclusionRecord.Revocation_Date__c;
        bodyWrapper.accountRevocationDate = exclusionRecord.Revocation_Date__c;

        bodyWrapper.excBySourceName = exlPatron.Id; // Repurposed to use for sourceSystemId i.e. Patron Salesforce Record Id.
    }

    private static Boolean isExclusionPendingOrFailed(String status) {
        return status == 'Exclusion Pending' || status == 'Activation Failed';
    }

    private static String getPOETypeId(String pOETypeStr, String stateStr) {
        if (String.isBlank(pOETypeStr)) {
            return null;
        }
        String POETypeIDstr = '';

        List<Exl_POEType_ID_Mapping__mdt> pOEIdMdts = [
            SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, SystemModstamp,
                   POE_Type__c, POEType_Id__c, Jurisdiction__c, POE_Type__r.Label
            FROM Exl_POEType_ID_Mapping__mdt
        ];

        if (!pOEIdMdts.isEmpty()) {
            for (Exl_POEType_ID_Mapping__mdt poeMdtRec : pOEIdMdts) {
                if (poeMdtRec.POE_Type__c != null
                    && !String.isBlank(poeMdtRec.POE_Type__r.Label) && poeMdtRec.POE_Type__r.Label == pOETypeStr
                    && !String.isBlank(poeMdtRec.Jurisdiction__c) && poeMdtRec.Jurisdiction__c == stateStr) {
                    POETypeIDstr = poeMdtRec.POEType_Id__c;
                }
            }
        }

        return POETypeIDstr;
    }

    private static Contact getExlPatron(Id patronId) {
        return [SELECT Id, FirstName, LastName, Date_of_Birth__c FROM Contact WHERE Id = :patronId];
    }
}