force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Event hosts, each name separated by commas</inlineHelpText>
    <label>Event Main Host</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Record Type to hold TSEG event related information</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Event_Allocation__c/Event_Allocation__c.object-meta.xml
<CustomObject>
    <label>Event Allocation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Allocation__c/fields/Actual__c.field-meta.xml
<CustomField>
    <fullName>Actual__c</fullName>
    <label>Expected Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Allocation</label>
    <referenceTo>Allocation__c</referenceTo>
    <relationshipLabel>Event Allocations</relationshipLabel>
    <relationshipName>Event_Allocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budgeted Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Total Seat Allocation</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Actual Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.RecordType.Name</field>
            <operation>equals</operation>
            <value>Event</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Allocations</relationshipLabel>
    <relationshipName>Event_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Host__c/Host__c.object-meta.xml
<CustomObject>
    <label>Host</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Host Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hosts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAllocationController.cls
/**
 * Class Name  : EventAllocationController
 * Summary     : Controller class for 'EventAllocationController' aura component 
 * Methods     : getCampaignDetails
                 saveEventAllocationTest
 * @author       Fritz Gerald Moran
   @Description: This class fetches the list of campaigns and saves the event allocation

 * @version      $Revision: 1.0 $, $Date: 5/Aug/2020 
 */

/*parent class that holds the methods for testing the apex controller of EventAllocationController*/
public with sharing class EventAllocationController {
    
    //Wrapper class for event allocation json
    public class EventAllocationWrapperClass {
        public Integer Id;
        public String Allocation;
        public Integer Capacity;
        public Double Budget;
        public Integer Host_Allocated;
        public Double Cost;
        public Double Actual;
    }
    
    //fetches the campaign details from the record page
    @AuraEnabled
    public static List<Campaign> getCampaignDetails(String recordId) {
        return [SELECT Id, Name, Status, StartDate, EndDate, Type, Host__c FROM Campaign WHERE Id = :recordId];
    } 
    
    //creates event allocation for domestic, international, interstate, local allocations
    @AuraEnabled
    public static String saveEventAllocation(String eventAllocationList, String recordId) {
        List<Event_Allocation__c> eventAllocToAdd = new  List<Event_Allocation__c>();
        List<Allocation__c> allocList = [SELECT Id, Name FROM Allocation__c];
        boolean isSuccess = FALSE;
        
        List<EventAllocationWrapperClass> ObjList = new List<EventAllocationWrapperClass>();
        ObjList = (List<EventAllocationWrapperClass>)System.JSON.deserialize(eventAllocationList, List<EventAllocationWrapperClass>.class);
        
        if(!ObjList.isEmpty() && ObjList != NULL) {
            for(EventAllocationWrapperClass obj: ObjList) {
                for(Allocation__c alloc: allocList) {
                    if(obj.Allocation.equals(alloc.Name)) {
                        eventAllocToAdd.add(new Event_Allocation__c(
                            Allocation__c = alloc.Id,
                            Event__c = recordId,
                            Budget__c = obj.Budget,
                            Cost__c = obj.Cost,
                            Capacity__c = obj.Capacity,
                            Actual__c = obj.Actual
                        ));
                    }   
                }
            }
        }
        
        if(!eventAllocToAdd.isEmpty()) {
            try {
                insert eventAllocToAdd;
                system.debug(eventAllocToAdd);
                system.debug(eventAllocToAdd.isEmpty());
                isSuccess = TRUE;
            } catch(Exception ex) {
                isSuccess = FALSE;
                ErrorLogger.createLog('EventAllocationController', 'saveEventAllocation', ex, recordId, 'Apex Class');
            }
        }
        return isSuccess ? 'SUCCESS': 'ERROR';
    }
}