force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event End Date/Time (user timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Start Date/Time (user timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Seats_Available__c.field-meta.xml
<CustomField>
    <fullName>Seats_Available__c</fullName>
    <formula>Total_Seat_Capacity__c  -  Seats_Reserved__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seats Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Record Type to hold TSEG event related information</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Event_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Event_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Allocation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CampaignId</field>
            <operation>equals</operation>
            <valueField>Event_Allocation__c.Event__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Allocation__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/No_of_guests__c.field-meta.xml
<CustomField>
    <fullName>No_of_guests__c</fullName>
    <label>No. of guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RSVP_Status__c.field-meta.xml
<CustomField>
    <fullName>RSVP_Status__c</fullName>
    <label>RSVP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/Event_Allocation__c.object-meta.xml
<CustomObject>
    <label>Event Allocation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Allocation__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Allocation</label>
    <referenceTo>Allocation__c</referenceTo>
    <relationshipLabel>Event Allocations</relationshipLabel>
    <relationshipName>Event_Allocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Total Seat Allocation</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.RecordType.Name</field>
            <operation>equals</operation>
            <value>Event</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Allocations</relationshipLabel>
    <relationshipName>Event_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/No_of_host__c.field-meta.xml
<CustomField>
    <fullName>No_of_host__c</fullName>
    <label>No. of host</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Seat_Reserved__c.field-meta.xml
<CustomField>
    <fullName>Seat_Reserved__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Seats Reserved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Allocation__c/fields/Seats_Available__c.field-meta.xml
<CustomField>
    <fullName>Seats_Available__c</fullName>
    <description>Current seats available</description>
    <formula>IF((Capacity__c -  Seats_Reserved_All__c  )&lt; 0 , 0, (Capacity__c -  Seats_Reserved_All__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seats Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static Contact createSingleContact (String name )
    {
        Contact con = new Contact(FirstName = name , LastName = 'Simplus', Email = 'none@testsimplus.com');
        insert con;
        return con;
    }
    public static Campaign createSingleCampaign(String RecordType)
    {
        Datetime dateTimeNow = Datetime.now();
        Datetime StartDate = dateTimeNow.addDays(2);
        Datetime EndDate = dateTimeNow.addDays(7);
        
        String rtID = Schema.Sobjecttype.Campaign.getRecordTypeInfosByName().get(RecordType).getRecordTypeId();
        Campaign c = new Campaign(Name='Test',Event_Start_Date_Time__c = StartDate, Event_End_Date_Time__c = EndDate, Description = 'Test Data Campaign', RecordTypeId = rtID );
        insert c;
        return c;
    }
    public static Event_Allocation__c createSingleEventAllocation(integer capacity, Campaign c )
    {
        Allocation__c a = new Allocation__c(Name = 'Local');
        insert a;

        Event_Allocation__c al = new Event_Allocation__c();
        al.Name = 'Event Allocation Test ';
        al.Capacity__c = capacity; 
        al.No_of_host__c = 1;
        al.Event__c = c.Id;
        al.Allocation__c =a.id;
        al.Seat_Reserved__c = 0;
        system.debug('Seats Available >>> '+        al.Seats_Available__c);
        insert al;
        return al;
    }
    public static CampaignMember createCampaingMember(Contact con, Event_Allocation__c Al,Campaign c, String rsvpStatus, Integer noOfGuest)
    {
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = c.Id;
        cm.Event_Allocation__c = al.Id;
        cm.RSVP_Status__c =  rsvpStatus ; 
        cm.No_of_guests__c = noOfGuest; 
        cm.Status = 'Invited';
        cm.ContactId = con.id;
        
        system.debug('Campaign Member >> ' +cm);
        
        insert cm;
        return cm;
        
    }
    
    @future
    public static void createUser(String profileName, String roleName){
        Profile userProfile = [SELECT Id FROM Profile WHERE Name = :profileName];
        UserRole userRole = [SELECT Id FROM UserRole WHERE Name = :roleName];
        User testUser = new User(
            FirstName = 'Test First',
            LastName = 'Test Last',
            Email = 'testUser@starTest.com',
            Alias = 'tasu',
            Username = 'testAdminUser@starTest.com',
            CommunityNickname = 'TestUser',
            ProfileId = userProfile.Id,
            UserRoleId = userRole.Id,
            TimeZoneSidKey = 'Australia/Sydney',
            LocaleSidKey = 'en_AU',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        
        insert testUser;
    }
}