force-app/main/default/objects/ContactLightningURIEvent__b/ContactLightningURIEvent__b.object-meta.xml
<CustomObject>
    <label>ContactLightningURIEvent</label>
    <pluralLabel>ContactLightningURIEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <label>EventDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/EventIdentifier__c.field-meta.xml
<CustomField>
    <fullName>EventIdentifier__c</fullName>
    <label>EventIdentifier</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/IPAddress__c.field-meta.xml
<CustomField>
    <fullName>IPAddress__c</fullName>
    <label>IPAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/OperatingSystem__c.field-meta.xml
<CustomField>
    <fullName>OperatingSystem__c</fullName>
    <label>OperatingSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/QueriedEntities__c.field-meta.xml
<CustomField>
    <fullName>QueriedEntities__c</fullName>
    <label>QueriedEntities</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <label>UserType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/highProfileTestBatch.cls
global class highProfileTestBatch implements Database.Batchable<sObject>{
    global highProfileTestBatch() {

    }

    global Iterable<SObject> start(Database.BatchableContext BC){
        return [SELECT EventDate,EventIdentifier,Operation,QueriedEntities,RecordId,SourceIp,Username,DevicePlatform,OsName,UserType FROM LightningUriEvent WHERE EventDate = LAST_N_DAYS:30 LIMIT 5];
    }

    global void execute(Database.BatchableContext BC, List<LightningUriEvent> lightningURIList){

        List<ContactLightningURIEvent__b> contURIEventList = new List<ContactLightningURIEvent__b>();

        for(LightningUriEvent lEvent : lightningURIList){

            ContactLightningURIEvent__b contURIEvent = new ContactLightningURIEvent__b();
            contURIEvent.EventDate__c = lEvent.EventDate;
            contURIEvent.Operation__c = lEvent.Operation;
            contURIEvent.EventIdentifier__c = lEvent.EventIdentifier;
            contURIEvent.QueriedEntities__c = lEvent.QueriedEntities;
            contURIEvent.RecordId__c = lEvent.RecordId;
            contURIEvent.IPAddress__c = 'TESTING OF BATCH';
            contURIEvent.User__c = lEvent.Username;
            contURIEvent.Platform__c = lEvent.DevicePlatform;
            contURIEvent.OperatingSystem__c = lEvent.OsName;
            contURIEvent.UserType__c = lEvent.UserType;
            contURIEventList.add(contURIEvent);
        }

        if(!contURIEventList.isEmpty()){

            Database.insertImmediate(contURIEventList);
        }
    }

    global void finish(Database.BatchableContext BC){
        
    }
}