force-app/main/default/objects/ContactLightningURIEvent__b/ContactLightningURIEvent__b.object-meta.xml
<CustomObject>
    <label>ContactLightningURIEvent</label>
    <pluralLabel>ContactLightningURIEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <label>EventDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/EventIdentifier__c.field-meta.xml
<CustomField>
    <fullName>EventIdentifier__c</fullName>
    <label>EventIdentifier</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/IPAddress__c.field-meta.xml
<CustomField>
    <fullName>IPAddress__c</fullName>
    <label>IPAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/OperatingSystem__c.field-meta.xml
<CustomField>
    <fullName>OperatingSystem__c</fullName>
    <label>OperatingSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/QueriedEntities__c.field-meta.xml
<CustomField>
    <fullName>QueriedEntities__c</fullName>
    <label>QueriedEntities</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <label>UserType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HighProfileSyncSetting__c/HighProfileSyncSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>High Profile Sync Setting</label>
</CustomObject>

force-app/main/default/objects/HighProfileSyncSetting__c/fields/Num_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Days__c</fullName>
    <label>Num of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleHighProfileSyncBatch.cls
public class ScheduleHighProfileSyncBatch implements Database.Batchable<sObject>, Schedulable {
    private String dynamicDateLiteral;
    @TestVisible List<LightningUriEvent> lightningURIListTest;
    @TestVisible private static Boolean runOriginalConstructor = true;

    public ScheduleHighProfileSyncBatch() {
        HighProfileSyncSetting__c hpsSetting = HighProfileSyncSetting__c.getOrgDefaults();
        Integer numberOfDays = (hpsSetting.Num_of_Days__c == null) ? 90 : (Integer) hpsSetting.Num_of_Days__c;
        this.dynamicDateLiteral = 'LAST_N_DAYS:' + String.valueOf(numberOfDays);
    }

    @TestVisible public ScheduleHighProfileSyncBatch(List<LightningUriEvent> lightningURIList){

        lightningURIListTest = lightningURIList;
    }

    /* Schedulable */
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new ScheduleHighProfileSyncBatch());
    }

    /* Batch Apex */
    public Iterable<sObject> start(Database.BatchableContext bc) {
    
        if(runOriginalConstructor){

            String queryString = 'SELECT EventDate, Operation, EventIdentifier, QueriedEntities, RecordId, SourceIp, Username, DevicePlatform, OsName, UserType FROM LightningUriEvent WHERE (EventDate = ' + this.dynamicDateLiteral + ')';

            return Database.query(queryString);
        }
        else{

            return lightningURIListTest;
        }
    }

    public void execute(Database.BatchableContext bc, List<LightningUriEvent> lightningURIList) {
        System.debug('lightningURIList: ' + lightningURIList);

        List<ContactLightningURIEvent__b> conURIEventList = new List<ContactLightningURIEvent__b>();
        for (LightningUriEvent lUriEvent: lightningURIList) {
            if (lUriEvent.QueriedEntities != null && lUriEvent.QueriedEntities.contains('Contact')) {
                ContactLightningURIEvent__b conURIEvent = new ContactLightningURIEvent__b();
                conURIEvent.EventDate__c = lUriEvent.EventDate;
                conURIEvent.Operation__c = lUriEvent.Operation;
                conURIEvent.EventIdentifier__c = lUriEvent.EventIdentifier;
                conURIEvent.QueriedEntities__c = lUriEvent.QueriedEntities;
                conURIEvent.RecordId__c = lUriEvent.RecordId;
                conURIEvent.IPAddress__c = lUriEvent.SourceIp;
                conURIEvent.User__c = lUriEvent.Username;
                conURIEvent.Platform__c = lUriEvent.DevicePlatform;
                conURIEvent.OperatingSystem__c = lUriEvent.OsName;
                conURIEvent.UserType__c = lUriEvent.UserType;
                conURIEventList.add(conURIEvent);
            }
        }

        System.debug('conURIEventList: ' + conURIEventList);

        try {
            if(!Test.isRunningTest()){
                Database.insertImmediate(conURIEventList);
            }
        } catch (Exception e) {
            ErrorLogger.createLog('ScheduleHighProfileSyncBatch', 'scheduleHighProfileSyncBatch', e, null, 'Apex Class'); 
        }
    }

    public void finish(Database.BatchableContext bc) {
        ScheduledDeleteBigObjectBatch deleteBigObjectBatch = new ScheduledDeleteBigObjectBatch();
        Database.executeBatch(deleteBigObjectBatch);
    }
}