force-app/main/default/objects/Relationships__c/Relationships__c.object-meta.xml
<CustomObject>
    <label>Relationships</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationships__c/fields/From_Patron__c.field-meta.xml
<CustomField>
    <fullName>From_Patron__c</fullName>
    <label>From Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related To</relationshipLabel>
    <relationshipName>RelatedTo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Relationships__c/fields/Non_Player_Name__c.field-meta.xml
<CustomField>
    <fullName>Non_Player_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Non-Player Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relationships__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationships__c/fields/To_Patron__c.field-meta.xml
<CustomField>
    <fullName>To_Patron__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related From</relationshipLabel>
    <relationshipName>RelatedFrom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationships__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Funder</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Travelling Companion</fullName>
            </value>
            <value>
                <fullName>Nominated Loyalty Partner</fullName>
            </value>
            <value>
                <fullName>Loyalty Benefit Sharer</fullName>
                <isActive>false</isActive>
                <label>Loyalty Benefit Sharer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PatronProspectRelationshipController.cls
/**
 * Class Name  : PatronProspectRelationshipController
 * Summary     : Controller class for 'PatronProspectRelationship' aura component 
 * Methods     : getRelationships
                 isDeletableObject
                 isUpdateableObject
                 getRecordTypes
                 deleteRelationship
 * @author       Fritz Gerald Moran
   @Description: This class fetches the list of active relationships, checks the user access permissions for the object,
				 gets the record types, and deletes relationship
 * @version      $Revision: 1.0 $, $Date: 24/Jul/2020 
 */

//with sharing used with class definition to enforce user access restrictions 
public with sharing class PatronProspectRelationshipController {
    
    //method for fetching active Relationships that is associated with the Patron and is Limit to 10.
    @AuraEnabled
    public static List<Relationships__c> getRelationships(String recordId, boolean hasLimit) {
        String objLimit = '';
        List<Relationships__c> relationshipsList = new List<Relationships__c>(); 
        if(hasLimit) {
             objLimit = 'LIMIT 10';
        } else {
             objLimit = '';
        }
        try {
            String relList = 'SELECT Id, Non_Player_Name__c, To_Patron__r.Name, To_Patron__c, Type__c, Active__c, From_Patron__r.Name, Prospect__r.Name, Prospect__c, From_Patron__c, RecordType.Name, RecordTypeId, Name FROM Relationships__c WHERE Active__c = TRUE AND (To_Patron__c != null OR Prospect__c != null OR Non_Player_Name__c != null)  AND (To_Patron__r.Id =: recordId OR From_Patron__r.Id =: recordId) ORDER BY ACTIVE__C DESC, Name DESC, TYPE__c DESC ' +objLimit; 
            relationshipsList = Database.query(relList);
        } catch (Exception ex) {
            system.debug(ex.getMessage());
        }
       
        system.debug(relationshipsList);
        return relationshipsList;
    }
    
    //method for checking if the logged-in user has delete permissions on the object
    @AuraEnabled
    public static Boolean isDeletableObject(String objectAPIName) {
        Boolean returnValue = false;
        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();
        Schema.SObjectType sobjectType = globalDescribeMap.get(objectAPIName);
        // Retrieve the object type from global describe and verify if user has delete permission for the object
        if (sobjectType != null) {
            returnValue = sobjectType.getDescribe().isDeletable();
        }
        return returnValue;
    }
    
    //method for checking if the logged-in user has create permissions on the object
    @AuraEnabled
    public static Boolean isCreatable(String objectAPIName) {
        Boolean returnValue = false;
        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();
        Schema.SObjectType sobjectType = globalDescribeMap.get(objectAPIName);
        // Retrieve the object type from global describe and verify if user has delete permission for the object
        if (sobjectType != null) {
            returnValue = sobjectType.getDescribe().isCreateable();
        }
        return returnValue;
    }
  
    //method for checking if the logged-in user has update permissions on the object
    @AuraEnabled
    public static Boolean isUpdateableObject(String objectAPIName) {
        Boolean returnValue = false;
        Map<String, Schema.SObjectType> globalDescribeMap = Schema.getGlobalDescribe();
        Schema.SObjectType sobjectType = globalDescribeMap.get(objectAPIName);
        // Retrieve the object type from global describe and verify if user has update permission for the object
        if (sobjectType != null) {
            returnValue = sobjectType.getDescribe().isUpdateable();
        }
        return returnValue;
    }
   
    @AuraEnabled
    public String defaultRecordTypeId {get; set;} //initialize variable that will hold the default record type
    
    @AuraEnabled
    public Map<Id, String> relationRecordTypes {get; set;} //initialize map to append the recordTypeId and record type info
    
    //method for getting the record types of Relationships Object
    @AuraEnabled
    public static PatronProspectRelationshipController getRecordTypes() {
        PatronProspectRelationshipController obj = new PatronProspectRelationshipController();
        Map<Id, String> recordtypeMap = new Map<Id, String>();
        //Get all record types of Contact object
        List<Schema.RecordTypeInfo> recordTypeInfoList = Relationships__c.SObjectType.getDescribe().getRecordTypeInfos();
        for(RecordTypeInfo info: recordTypeInfoList) {
            //Check record type is available for current user profile
            if(info.isAvailable()) {
                //Check master record type
                if(info.getName() != 'Master' && info.getName().trim() != ''){
                    recordtypeMap.put(info.getRecordTypeId(), info.getName());
                }
                //Get the default record type for current user profile
                if(info.isDefaultRecordTypeMapping()){
                    obj.defaultRecordTypeId = info.getRecordTypeId();
                }
            }
        }    
        obj.relationRecordTypes = recordtypeMap;
        return obj;
    }
    
    //method for deleting Relationships record that corresponds to the passed ID
    @AuraEnabled
    public static void deleteRelationship(String recordId) {
        List<Relationships__c> relationshipRec = [SELECT Id, Name FROM Relationships__c WHERE ID =: recordId];
        
        if(!relationshipRec.isEmpty() && relationshipRec != NULL) {
            try {
                delete relationshipRec;   
            } catch(Exception ex) {
                ErrorLogger.createLog('Relationships__c','deleteRelationship', ex, recordId, 'Apex Class');
            }   
        }
    }
}