force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERROR-{00000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLoggingSettings__c/ErrorLoggingSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Error Logging Settings</label>
</CustomObject>

force-app/main/default/objects/ErrorLoggingSettings__c/fields/Enable_Error_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Error_Logging__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Error Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ErrorLoggerTest.cls
/**
 * Class Name  : ErrorLoggerTest
 * Summary     : Test Class for validating the test coverage of the Error Logger Class 
 * Method     :  testSingleValueEvent     
 * @author       Simplus
   @Description: This class contains the logic for the insertion of record for Error_Event__e Platform Event
 * @version      $Revision: 1.0 $, $Date: 21/July/2020 
 */
@isTest
public class ErrorLoggerTest {
    @isTest static void testValidEvent(){
        //Ensure that the Enable Error Logging Custom Setting is checked
  		ErrorLoggingSettings__c getCustSetting = ErrorLoggingSettings__c.getOrgDefaults();
        getCustSetting.Enable_Error_Logging__c = true;
        insert getCustSetting;
        
        List<Error_Event__e> errs = new List<Error_Event__e>();
        System.assertEquals(true, getCustSetting.Enable_Error_Logging__c);
        
        Test.startTest();
        	//Failed account which leads to the catch method
            try{
                List<Account> testAcc = new List<Account>();
                testAcc.add(new Account(Id = '09123456789',
                                        Name = 'Test Account'));
                insert testAcc;
            } catch (Exception e){
                //execute the Error Logger object
                ErrorLogger.createLog('Test Apex Class', 'Test Method Name', e, '', 'Apex Class');
            }
        Test.stopTest();
        //Check if an error log record is created
        List<ErrorLog__c> errLogs = [SELECT Id FROM ErrorLog__c];
        System.assertEquals(1, errLogs.size());
    }
    @isTest static void testValidEventWithNullException(){
        //Ensure that the Enable Error Logging Custom Setting is checked
  		ErrorLoggingSettings__c getCustSetting = ErrorLoggingSettings__c.getOrgDefaults();
        getCustSetting.Enable_Error_Logging__c = true;
        insert getCustSetting;
        
        List<Error_Event__e> errs = new List<Error_Event__e>();
        System.assertEquals(true, getCustSetting.Enable_Error_Logging__c);
        
        Test.startTest();
        	//Failed account which leads to the catch method
            try{
                List<Account> testAcc = new List<Account>();
                testAcc.add(new Account(Id = '09123456789',
                                        Name = 'Test Account'));
                insert testAcc;
            } catch (Exception e){
                //execute the Error Logger object
                ErrorLogger.createLog('Test Apex Class', 'Test Method Name', null, '', 'Apex Class');
            }
        Test.stopTest();
        //Check if an error log record is created
        List<ErrorLog__c> errLogs = [SELECT Id FROM ErrorLog__c];
        //System.assertEquals(1, errLogs.size());
    }
}