force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERROR-{00000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogDeleteBatchTest.cls
@isTest
public class ErrorLogDeleteBatchTest {

    @TestSetup
    private static void testDataSetup(){

        ErrorLog__c err = new ErrorLog__c();
        err.Apex_Class__c = 'Test';
        insert err;

        Test.setCreatedDate(err.Id, Date.valueOf('2025-01-01'));
    }
    
    @isTest
    static void testErrorLogBatch_Schedule() {
        
        test.startTest();
        ErrorLogDeleteBatch errLogSched = new ErrorLogDeleteBatch ();   
        String chron = '0 0 23 * * ?';        
        system.schedule('Test Sched', chron, errLogSched);
        test.stopTest();
    }
}