force-app/main/default/objects/Exl_CaseTypePicklistConfig__mdt/Exl_CaseTypePicklistConfig__mdt.object-meta.xml
<CustomObject>
    <label>CaseTypePicklistConfig</label>
    <pluralLabel>CaseTypePicklistConfigs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/Exl_Exclusion__c.object-meta.xml
<CustomObject>
    <description>This object serves as the authoritative source for all patron-related restrictions and exclusions.</description>
    <label>Exclusion</label>
    <nameField>
        <displayFormat>1{00000}</displayFormat>
        <label>Exclusion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Resent</fullName>
            </value>
            <value>
                <fullName>Requires Hand Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered Successfully</fullName>
            </value>
            <value>
                <fullName>Handed Successfully</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetDeliveryStatusChoicesAction.cls
public class GetDeliveryStatusChoicesAction {
	
    // ONLY used in tests
    @TestVisible static Boolean TEST_MODE = false;
    @TestVisible static List<Exl_CaseTypePicklistConfig__mdt> TEST_MAPPINGS; 
    
    public class Output {
        @InvocableVariable public PicklistEntryValue[] entries = new PicklistEntryValue[0];
    }
    public class Input {
        //@InvocableVariable public String caseType;
        //@InvocableVariable public String state;
    }
    
    @InvocableMethod(
        label='Get Delivery Status Choices'
        description='Returns picklist-ready label/value pairs (Delivery Status) for Exclusion Record field.'
    )
    
    public static List<Output> getChoices() {
        List<Output> results = new List<Output>();
        Output out = new Output();
        List<String> activeValues = new List<String>();
        
        String excludedEntriesString = System.Label.Excluded_Delivery_Status;
        List<String> excludedEntriesList = excludedEntriesString.split(',');
        Schema.DescribeFieldResult fieldDetail = Exl_Exclusion__c.Delivery_Status__c.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldDetail.getPicklistValues();
        
        for (Schema.PicklistEntry entry : picklistEntries) {
            if(!excludedEntriesList.contains(entry.getValue())) {
                if (entry.isActive()) {
                    activeValues.add(entry.getValue());
                }
            }
        }
        // build picklist entries
        for (String rec : activeValues) {
            out.entries.add(new PicklistEntryValue(rec, rec));
        }
        results.add(out);
        return results;
    }
}