force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Booking Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Booking_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Booking Date and Time (User Timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Depart_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Depart_Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Depart Date and Time (User Timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Flight_Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Flight_Booking_Status__c</fullName>
    <label>Flight Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Booking</fullName>
                <default>true</default>
                <label>New Booking</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
                <isActive>false</isActive>
                <label>Cancellation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Flight_Region__c.field-meta.xml
<CustomField>
    <fullName>Flight_Region__c</fullName>
    <label>Flight Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Flying_from__c.field-meta.xml
<CustomField>
    <fullName>Flying_from__c</fullName>
    <label>Flying from</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Flight_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Melbourne</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
            <value>
                <fullName>Perth</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Macau</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Bangkok</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Guangzhou</fullName>
            </value>
            <value>
                <fullName>Chengdu</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Flying_to__c.field-meta.xml
<CustomField>
    <fullName>Flying_to__c</fullName>
    <label>Flying to</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Flight_Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Melbourne</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
            <value>
                <fullName>Perth</fullName>
            </value>
            <value>
                <fullName>Auckland</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Macau</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Bangkok</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Guangzhou</fullName>
            </value>
            <value>
                <fullName>Chengdu</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <label>Hotel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Property__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SYD - The Star Grand</fullName>
            </value>
            <value>
                <fullName>SYD - The Star Residences</fullName>
            </value>
            <value>
                <fullName>SYD - The Darling</fullName>
            </value>
            <value>
                <fullName>GC - The Star Grand</fullName>
            </value>
            <value>
                <fullName>GC - The Darling</fullName>
            </value>
            <value>
                <fullName>BNE - Treasury</fullName>
            </value>
            <value>
                <fullName>BNE - The Star Grand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Hotel_Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Booking_Status__c</fullName>
    <label>Hotel Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Booking</fullName>
                <default>true</default>
                <label>New Booking</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Hotel_Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Confirmation_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Hotel Booking Reference - Admin Only</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/MOP_Status__c.field-meta.xml
<CustomField>
    <fullName>MOP_Status__c</fullName>
    <label>MOP Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Property__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RO – Room only</fullName>
            </value>
            <value>
                <fullName>RB – Room &amp; Breakfast</fullName>
            </value>
            <value>
                <fullName>POA – Pay on Arrival</fullName>
            </value>
            <value>
                <fullName>$1CC - $1Credit Card in-Print</fullName>
            </value>
            <value>
                <fullName>ATP – Adjust to play</fullName>
            </value>
            <value>
                <fullName>NGC – Non-gaming Comp</fullName>
            </value>
            <value>
                <fullName>WM – Waive Monies</fullName>
            </value>
            <value>
                <fullName>DNWM – Do not waive monies</fullName>
            </value>
            <value>
                <fullName>CALL REP</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/One_way_OR_Return__c.field-meta.xml
<CustomField>
    <fullName>One_way_OR_Return__c</fullName>
    <label>One-way OR Return?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-way</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Pax__c.field-meta.xml
<CustomField>
    <fullName>Pax__c</fullName>
    <label>Pax</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Pick_Up_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Pick_Up_Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pick Up Date and Time (User Timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Brisbane</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Restaurant_Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Booking_Status__c</fullName>
    <label>Restaurant Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Booking</fullName>
                <default>true</default>
                <label>New Booking</label>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Returning_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Returning_Date_and_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Returning Date and Time (User Timezone)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Limo</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Special_Request__c.field-meta.xml
<CustomField>
    <fullName>Special_Request__c</fullName>
    <label>Special Request</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Hotel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADP – International Adaptors</fullName>
            </value>
            <value>
                <fullName>B3 – 2 Water, Shaving Kit, Dental Kit, Slippers</fullName>
            </value>
            <value>
                <fullName>COT – Baby Cot</fullName>
            </value>
            <value>
                <fullName>ROL – Roll away bed</fullName>
            </value>
            <value>
                <fullName>SACRN - Special offer request</fullName>
            </value>
            <value>
                <fullName>SHARE - Allow sharer to check in, approved by management</fullName>
            </value>
            <value>
                <fullName>VVIP Gesture - Check-in Sharer, approved by Paul Monaghan</fullName>
            </value>
            <value>
                <fullName>SHARE - Allow sharer to check in, approved by Paul Monaghan</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingServiceTriggerHandlerTest.cls
/*
 * @Class Name  : BookingServiceTriggerHandler
 * @Summary     : Helper class for the 'BookingServiceTrigger' trigger 
 * @author      : Simplus
 * @Description : This class contains the logic when creating Service Records
 * @version     : $Revision: 1.0 $, $Date: 2022-02-28
 *                2.0 1/18/2023 - Commented out methods since VIP Booking will not be used anymore
*/
@isTest
public class BookingServiceTriggerHandlerTest {
    @testSetup
    static void testDataFactory(){
        Contact testContact = TestDataFactory.createSingleContact('TestClass');   
        
        Service__c limoService = new Service__c();
        limoService.Property__c = 'Sydney';
        limoService.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Limo Booking');
        limoService.Booking_Date_and_Time__c = System.today();
        INSERT limoService;   
    }

    @isTest static void testAmendmentUpdate(){
        Service__c testServiceRest = new Service__c();
        testServiceRest.Property__c = 'Sydney';
        testServiceRest.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Restaurant Booking');
        testServiceRest.Booking_Date_and_Time__c = System.today();
        INSERT testServiceRest;
        
        test.startTest();
        
        testServiceRest.Restaurant_Booking_Status__c = 'Confirmed';
        testServiceRest.Pax__c = 15;
        testServiceRest.Booking_Date_and_Time__c = System.today()+1;
        update testServiceRest;
        test.stopTest();
        
        Service__c testServiceRec = [SELECT Id, Restaurant_Booking_Status__c FROM Service__c WHERE Id =: testServiceRest.Id];
        System.assertEquals('Amendment', testServiceRec.Restaurant_Booking_Status__c);
    }

    @isTest static void testAmendmentUpdate2(){
        Service__c testServiceRest = new Service__c();
        testServiceRest.Property__c = 'Sydney';
        testServiceRest.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Flight Booking');
        testServiceRest.Booking_Date_and_Time__c = System.today();
        testServiceRest.Depart_Date_and_Time__c = System.today();
        testServiceRest.Returning_Date_and_Time__c = System.today();
        INSERT testServiceRest;
        
        test.startTest();
        
        testServiceRest.Flight_Booking_Status__c = 'Confirmed';
        testServiceRest.Passport_Number__c = '1234';
        testServiceRest.Depart_Date_and_Time__c = System.today()+1;
        testServiceRest.Returning_Date_and_Time__c = System.today()+1;
        testServiceRest.Flight_Region__c = 'Domestic';
        testServiceRest.Flying_to__c = 'Sydney';
        testServiceRest.Flying_from__c = 'Melbourne';
        testServiceRest.One_way_OR_Return__c = 'One-way';
        update testServiceRest;
        test.stopTest();
        
        Service__c testServiceRec = [SELECT Id, Flight_Booking_Status__c FROM Service__c WHERE Id =: testServiceRest.Id];
        System.assertEquals('Amendment', testServiceRec.Flight_Booking_Status__c);
    }

    @isTest static void testAmendmentUpdate3(){
        Service__c testServiceRest = new Service__c();
        testServiceRest.Property__c = 'Sydney';
        testServiceRest.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Hotel Booking');
        testServiceRest.Booking_Date_and_Time__c = System.today();
        testServiceRest.Arrival_Date__c = Date.today();
        testServiceRest.Departure_Date__c = Date.today()+5;
        INSERT testServiceRest;
        
        test.startTest();
        
        testServiceRest.Hotel_Booking_Status__c = 'Confirmed';
        testServiceRest.Arrival_Date__c = System.today() + 1;
        testServiceRest.Hotel_Confirmation_Number__c = 'TC001';
        testServiceRest.Hotel__c = 'SYD - The Star Grand';
        testServiceRest.Special_Request__c = 'ADP – International Adaptors';
        testServiceRest.MOP_Status__c = 'CALL REP';
        update testServiceRest;
        test.stopTest();
        
        Service__c testServiceRec = [SELECT Id, Hotel_Booking_Status__c FROM Service__c WHERE Id =: testServiceRest.Id];
        System.assertEquals('Amendment', testServiceRec.Hotel_Booking_Status__c);
    }

    @isTest static void testAmendmentUpdate4(){
        Service__c testServiceRest = new Service__c();
        testServiceRest.Property__c = 'Sydney';
        testServiceRest.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Limo Booking');
        testServiceRest.Booking_Date_and_Time__c = System.today();
        testServiceRest.Pick_Up_Date_and_Time__c = System.today();
        INSERT testServiceRest;
        
        test.startTest();
        
        testServiceRest.Limo_Booking_Status__c = 'Confirmed';
        testServiceRest.Pax__c = 10;
        testServiceRest.Pick_Up_Date_and_Time__c = System.today()+1;
        testServiceRest.Pick_Up_Location__c = 'The Star Grand';
        testServiceRest.Drop_Off_Location__c = 'The Star Residences';
        update testServiceRest;
        test.stopTest();
        
        Service__c testServiceRec = [SELECT Id, Limo_Booking_Status__c FROM Service__c WHERE Id =: testServiceRest.Id];
        System.assertEquals('Amendment', testServiceRec.Limo_Booking_Status__c);
    }
    
    @isTest static void testgetServiceRecord(){
        Service__c testServiceRest = new Service__c();
        testServiceRest.Property__c = 'Sydney';
        testServiceRest.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Hotel Booking');
        testServiceRest.Booking_Date_and_Time__c = System.today();
        testServiceRest.Arrival_Date__c = Date.today();
        testServiceRest.Departure_Date__c = Date.today()+5;
        INSERT testServiceRest;
        
        test.startTest();
        
        Service__c testServiceRec = BookingServiceTriggerHandler.getServiceRecord(testServiceRest.Id);
        
        update testServiceRest;
        test.stopTest();
        
        System.assertEquals('Sydney', testServiceRec.Property__c);
    }

    @isTest
    static void testStaticDateInsert(){

        Test.startTest();

        List<Service__c> sList = new List<Service__c>();

        Service__c testServiceLimo = new Service__c();
        testServiceLimo.Property__c = 'Sydney';
        testServiceLimo.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Limo Booking');
        testServiceLimo.Pick_Up_Date_and_Time__c = System.today();
        sList.add(testServiceLimo);

        Service__c testServiceFlight = new Service__c();
        testServiceFlight.Property__c = 'Sydney';
        testServiceFlight.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Flight Booking');
        testServiceFlight.Depart_Date_and_Time__c = System.today();
        testServiceFlight.Arrival_Date__c = System.today()+1;
        sList.add(testServiceFlight);

        Service__c testServiceRest = new Service__c();
        testServiceRest.Property__c = 'Sydney';
        testServiceRest.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Restaurant Booking');
        testServiceRest.Booking_Date_and_Time__c = System.today()+2;
        sList.add(testServiceRest);

        Service__c testServiceLimo2 = new Service__c();
        testServiceLimo2.Property__c = 'Brisbane';
        testServiceLimo2.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Limo Booking');
        testServiceLimo2.Pick_Up_Date_and_Time__c = System.today()+3;
        sList.add(testServiceLimo2);
        //update testServiceLimo2;

        Service__c testServiceLimo3 = new Service__c();
        testServiceLimo3.Property__c = 'Gold Coast';
        testServiceLimo3.RecordTypeId = BookingServiceTriggerHandler.returnRecordTypeId('Limo Booking');
        testServiceLimo3.Pick_Up_Date_and_Time__c = System.today()+4;
        sList.add(testServiceLimo3);
        //update testServiceLimo3;

        insert sList;
        update testServiceFlight;
        update testServiceRest;
        update testServiceLimo2;
        update testServiceLimo3;
        Test.stopTest();
    }
}