force-app/main/default/objects/Portal_Footer_Message__mdt/Portal_Footer_Message__mdt.object-meta.xml
<CustomObject>
    <label>Portal Footer Message</label>
    <pluralLabel>Portal Footer Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Footer_Message__mdt/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_Footer_Message__mdt/fields/Legal_Statement__c.field-meta.xml
<CustomField>
    <fullName>Legal_Statement__c</fullName>
    <label>Legal Statement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_Footer_Message__mdt/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PortalFooterControllerTest.cls
@IsTest
public class PortalFooterControllerTest {
	@IsTest
    static void getFooterMessagesTest(){
        Portal_Footer_Message__mdt pfm = new Portal_Footer_Message__mdt();
        pfm.MasterLabel = 'test';
        pfm.DeveloperName = 'test';
        pfm.Location__c = 'Sydney';
        PortalFooterController.getFooterMessages('Sydney');
        Portal_Footer_Message__mdt message = [Select Id,Location__c,Address__c,Legal_Statement__c from Portal_Footer_Message__mdt where Location__c ='Sydney' LIMIT 1];
        PortalFooterController.getFooterLinks('Sydney');
        System.assertEquals('Sydney', message.Location__c, 'No record is Present');
    }
}