force-app/main/default/objects/Error_Log_Delete_Batch_Setting__mdt/Error_Log_Delete_Batch_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Error Log Delete Batch Setting</label>
    <pluralLabel>Error Log Delete Batch Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log_Delete_Batch_Setting__mdt/fields/Last_N_Days__c.field-meta.xml
<CustomField>
    <fullName>Last_N_Days__c</fullName>
    <label>Last N Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERROR-{00000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ErrorLogDeleteBatch.cls
global class ErrorLogDeleteBatch implements Schedulable, Database.batchable<sObject>{ 
    
    global Database.QueryLocator start(Database.BatchableContext info){ 
        
        Error_Log_Delete_Batch_Setting__mdt errLogBatchSetting = Error_Log_Delete_Batch_Setting__mdt.getInstance('Error_Log_Setting');
        Integer numOfDays = Integer.valueOf(errLogBatchSetting.Last_N_Days__c);
        
        String query = 'SELECT Id FROM ErrorLog__c WHERE CreatedDate < LAST_N_DAYS:' + numOfDays + ' ORDER BY CreatedDate DESC';
        System.debug(query);
        return Database.getQueryLocator(query); 
    }     
    
    global void execute(Database.BatchableContext info, List<sObject> errorLogList){
        
        delete errorLogList;
    }     
    
    global void finish(Database.BatchableContext info){     
    } 
    
    global void execute(SchedulableContext ctx) {
        
        ErrorLogDeleteBatch errLogBatch = new ErrorLogDeleteBatch();
        Database.executeBatch(errLogBatch);
    }
}