force-app/main/default/objects/Internal_Event_Log__e/Internal_Event_Log__e.object-meta.xml
<CustomObject>
    <label>Internal Event Log</label>
    <pluralLabel>Internal Event Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Internal_Event_Log__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Exl_AfterSave_Exclusion_Helper.cls
public class Exl_AfterSave_Exclusion_Helper {
    public class FlowInputWrapper {
        @InvocableVariable(required=true) public String exclusionRecId;
        @InvocableVariable(required=true) public String source;
        @InvocableVariable(required=true) public String status;
    }
    
    public class FlowOutputWrapper {
        @InvocableVariable
        public Boolean isSuccessful;
        
        @InvocableVariable
        public String Error;
    }
    
    @InvocableMethod(label='Call Future Method' description='Calls a future method' category='Exl_OnExclusionInsert/Update')
    public static List<FlowOutputWrapper> invokeFuture(List<FlowInputWrapper> inputs) {
        List<FlowOutputWrapper> results = new List<FlowOutputWrapper>();
        
        // If Flow passed nothing, still return one empty output (Flow safe)
        if (inputs == null || inputs.isEmpty()) {
            FlowOutputWrapper emptyOut = new FlowOutputWrapper();
            emptyOut.isSuccessful = false;
            emptyOut.Error = null;
            results.add(emptyOut);
            return results;
        }
        
        for (FlowInputWrapper inWrap : inputs) {
            FlowOutputWrapper out = new FlowOutputWrapper();
            out.isSuccessful = false;
            out.Error = null;
            
            try {
                String incomingexclusionRecId = (inWrap == null) ? null : inWrap.exclusionRecId;
                if (String.isBlank(incomingexclusionRecId)) {
                    results.add(out);
                    continue;
                }
                out.isSuccessful = True;
                doAsyncOperation(inWrap.exclusionRecId, inWrap.source, inWrap.status);
            } catch (Exception e) {
                out.Error = 'Error while Calling Future Method: ' + e.getMessage();
            }
            results.add(out);
        }
        
        return results;
    }
    
    @future(callout=true)
    public static void doAsyncOperation(
        String exclusionRecId,
        String source,
        String status
    ) {
        System.debug('Exclusion Id: ' + exclusionRecId);
        System.debug('Source: ' + source);
        System.debug('Status: ' + status);
        List<Internal_Event_Log__e> eventsToPublish = new List<Internal_Event_Log__e>();
        
        // Create Platform Event
        eventsToPublish.add(new Internal_Event_Log__e(
            Record_Id__c = exclusionRecId,
            Source__c = source,
            Status__c = status
        ));
        
        if (!eventsToPublish.isEmpty()) {
            List<Database.SaveResult> results = EventBus.publish(eventsToPublish);
        }        
    }
}