force-app/main/default/objects/POE__x/POE__x.object-meta.xml
<CustomObject>
    <description>poe</description>
    <externalDataSource>Cosmos_DB</externalDataSource>
    <externalName>poe</externalName>
    <label>POE</label>
    <pluralLabel>Poe</pluralLabel>
</CustomObject>

force-app/main/default/objects/POE__x/fields/Behavior__c.field-meta.xml
<CustomField>
    <fullName>Behavior__c</fullName>
    <description>Behavior</description>
    <externalDeveloperName>Behavior</externalDeveloperName>
    <label>Behavior</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/CurrentDate__c.field-meta.xml
<CustomField>
    <fullName>CurrentDate__c</fullName>
    <description>CurrentDate</description>
    <externalDeveloperName>CurrentDate</externalDeveloperName>
    <label>CurrentDate</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <description>ExpiryDate</description>
    <externalDeveloperName>ExpiryDate</externalDeveloperName>
    <label>ExpiryDate</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/IssuedDate__c.field-meta.xml
<CustomField>
    <fullName>IssuedDate__c</fullName>
    <description>IssuedDate</description>
    <externalDeveloperName>IssuedDate</externalDeveloperName>
    <label>IssuedDate</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <description>Length</description>
    <externalDeveloperName>Length</externalDeveloperName>
    <label>Length</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/POENumber__c.field-meta.xml
<CustomField>
    <fullName>POENumber__c</fullName>
    <description>POENumber</description>
    <externalDeveloperName>POENumber</externalDeveloperName>
    <label>POENumber</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/POEType__c.field-meta.xml
<CustomField>
    <fullName>POEType__c</fullName>
    <description>POEType</description>
    <externalDeveloperName>POEType</externalDeveloperName>
    <label>POEType</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Property</description>
    <externalDeveloperName>Property</externalDeveloperName>
    <label>Property</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POE__x/fields/SalesforceContactId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SalesforceContactId</description>
    <externalDeveloperName>SalesforceContactId</externalDeveloperName>
    <label>SalesforceContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Poe</relationshipLabel>
    <relationshipName>Poe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ExclusionsDetailsUIDataSelector.cls
/*
 *Description       : 
 *Author            : Simplus
 *Created Date		: 15-08-2023
 *History:
 *15-08-2023		Created
*/
public class ExclusionsDetailsUIDataSelector extends ExternalObjectQuerySelector{
    public override List<Schema.SObjectField> getExternalObjectFieldsList() {
        return new List<Schema.SObjectField> {
            
                POE__x.Behavior__c,
                POE__x.CurrentDate__c,
                POE__x.Description__c,
                POE__x.ExpiryDate__c,
                POE__x.IssuedDate__c,
                POE__x.Length__c,
                POE__x.POENumber__c,
                POE__x.POEType__c,
                POE__x.Property__c,
                POE__x.SalesforceContactId__c
         };
    }

    public override Schema.SObjectType getExternalObjectType() {
        return POE__x.sObjectType;
    }
}