force-app/main/default/objects/Key_Date__c/Key_Date__c.object-meta.xml
<CustomObject>
    <label>Key Date</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Key Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Date__c/fields/Key_Date__c.field-meta.xml
<CustomField>
    <fullName>Key_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Key Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Key_Date__c/fields/Key_Date_Category__c.field-meta.xml
<CustomField>
    <fullName>Key_Date_Category__c</fullName>
    <label>Key Date Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Anniversary</fullName>
            </value>
            <value>
                <fullName>Join date</fullName>
            </value>
            <value>
                <fullName>Approved date</fullName>
            </value>
            <value>
                <fullName>Ceremony</fullName>
            </value>
            <value>
                <fullName>KYC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Key_Date__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Dates</relationshipLabel>
    <relationshipName>Key_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PoP__c/PoP__c.object-meta.xml
<CustomObject>
    <label>PoP</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PoP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PoP</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PoP__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PoP</relationshipLabel>
    <relationshipName>PoP</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ADHOC_KYCBatch.cls
public class ADHOC_KYCBatch implements Database.Batchable<SObject>, Schedulable {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        String keyDateCategory = 'KYC';
        Boolean activeStatus = true;
        String nameCondition1 = ConstantHelper.STRING_KEYDATE_DUEDATE;
        String nameCondition2 = ConstantHelper.STRING_KEYDATE_ATTESTATION;
        string nameCondition3 = ConstantHelper.STRING_KEYDATE_DUEDATE_OVERRIDE;
        Integer lastNDays = 3;
        
        // Query to find eligible Key_Date__c records
        String query = 
			'SELECT Id, Patron__c, Name, Key_Date__c, Key_Date_Category__c ' +
            'FROM Key_Date__c ' +
            'WHERE Key_Date_Category__c = :keyDateCategory ' +
            'AND Active__c = :activeStatus ' +
            'AND (Name = :nameCondition1 OR Name = :nameCondition2 OR Name = :nameCondition3) ' +
            'AND ' + System.Label.ADHOC_DateLabel + ' ' +
            'AND Patron__c NOT IN (SELECT contact__c FROM pop__c) ';

        system.debug('query '+query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope){
        system.debug('scope:: '+scope);
        for(sobject s : scope){
            system.debug('s record:: '+s);
        }
        //Process the batch using KYCUtility
        KYCUtility.segregateKeyDates(scope);
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Batch process completed.');
    }

    // Schedule execution for nightly run
    public void execute(SchedulableContext SC) {
    }
}