force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Residency_Checklist__c/Residency_Checklist__c.object-meta.xml
<CustomObject>
    <label>Residency Checklist</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Residency Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residency Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Residency_Checklist__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Residency Checklists</relationshipLabel>
    <relationshipName>Residency_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Residency_Checklist__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Days in NSW/QLD or AUS</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Residency Checklists</relationshipLabel>
    <relationshipName>Residency_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Days in NSW/QLD or AUS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days in NSW/QLD or AUS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Days in NSW/QLD or AUS</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_State__c.field-meta.xml
<CustomField>
    <fullName>Entry_State__c</fullName>
    <label>Entry State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>Exit_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/is_within_365_days__c.field-meta.xml
<CustomField>
    <fullName>is_within_365_days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is within 365 days?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SendApprovalTest.cls
@isTest
public class SendApprovalTest {
    static testmethod void testGroup(){
        test.startTest();
        List<Group> testGroup = SendApproval.getAllPublicGroups();
        System.assert(testGroup != NULL);
        test.stopTest();
    }
    
    static testmethod void testGroupMembers(){
        List<Group> testGroup = SendApproval.getAllPublicGroups();
        test.startTest();
        List<User> testUsers = SendApproval.getAllGroupMembers(testGroup[0].Id);
		System.assert(testUsers != NULL);
        test.stopTest();
    }
    
    static testmethod void testSendApproval(){
        Contact testContact = TestDataFactory.createSingleContact('TestClass');
        Id testUser = UserInfo.getUserId();
        Date dateToday = System.today();
        List<Trip__c> tripList = new List<Trip__c>();
        
        test.startTest();
        
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        INSERT firstTrip;
        
        Property__c testProperty = new Property__c();
        testProperty.Name = 'Test Property';
        
        INSERT testProperty;
        
        Program__c testProgram = new Program__c();
        testProgram.Property__c = testProperty.Id;
        testProgram.Name = 'Test Program';
        
        INSERT testProgram;
        
        Residency_Checklist__c testRC = new Residency_Checklist__c();
        testRC.Trip__c = firstTrip.Id;
        testRC.Program__c = testProgram.Id;
        
        INSERT testRC;
        
        SendApproval.submitAndProcessApprovalRequest(testRC.Id, testUser, 'Residency_Checklist_Approval');
        test.stopTest();
    }
}