force-app/main/default/objects/Exl_Restriction__c/Exl_Restriction__c.object-meta.xml
<CustomObject>
    <label>Restriction</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Restriction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restrictions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Restriction__c/fields/Enforcement_Status__c.field-meta.xml
<CustomField>
    <fullName>Enforcement_Status__c</fullName>
    <description>Reflects current sync or enforcement outcome.</description>
    <label>Enforcement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Overridden</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Restriction__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Restrictions</relationshipLabel>
    <relationshipName>Restrictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exl_Restriction__c/fields/Restriction_Type__c.field-meta.xml
<CustomField>
    <fullName>Restriction_Type__c</fullName>
    <description>Defines the type of restricted service or benefit.</description>
    <label>Restriction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Funds</fullName>
            </value>
            <value>
                <fullName>Hotel Bookings</fullName>
            </value>
            <value>
                <fullName>Access to Digital Channels</fullName>
            </value>
            <value>
                <fullName>Casino Points</fullName>
            </value>
            <value>
                <fullName>Discounts</fullName>
            </value>
            <value>
                <fullName>Parking benefits</fullName>
            </value>
            <value>
                <fullName>Receive Marketing Communications</fullName>
            </value>
            <value>
                <fullName>Tier Level Lost</fullName>
            </value>
            <value>
                <fullName>Digital Access</fullName>
                <isActive>false</isActive>
                <label>Digital Access</label>
            </value>
            <value>
                <fullName>Draws</fullName>
                <isActive>false</isActive>
                <label>Draws</label>
            </value>
            <value>
                <fullName>Loyalty Points</fullName>
                <isActive>false</isActive>
                <label>Loyalty Points</label>
            </value>
            <value>
                <fullName>Parking</fullName>
                <isActive>false</isActive>
                <label>Parking</label>
            </value>
            <value>
                <fullName>Smart Button</fullName>
                <isActive>false</isActive>
                <label>Smart Button</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/Casino__c.field-meta.xml
<CustomField>
    <fullName>Casino__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/CasinoBalance__c.field-meta.xml
<CustomField>
    <fullName>CasinoBalance__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Comp_Parking_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Comp_Parking_Entitlement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comp Parking Entitlement</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/F_B_Discount_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>F_B_Discount_Entitlement__c</fullName>
    <label>F&amp;B Discount Entitlement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Hotel_Discount_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Discount_Entitlement__c</fullName>
    <label>Hotel Discount Entitlement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoyaltyTriggerHelper.cls
/**
* Class Name  : LoyaltyTriggerHelper
* @author     : Capgemini
* @Description: Utility class to contain the business logic for the Loyalty object trigger
* @version    : Version 1 : 28/10/2025
**/

public class LoyaltyTriggerHelper {

    public static void reconcileRestrictionRecords(List<Loyalty__c> newLoyaltyList, Map<Id, Loyalty__c> oldLoyaltyMap){
        List<Exl_Restriction__c> restrictionUpdateList = new List<Exl_Restriction__c>();
        List<Id> loyaltyPointsList = new List<Id>();
        List<Id> loyaltyDiscountsList = new List<Id>();
        List<Id> loyaltyHotelList = new List<Id>();
        List<Id> loyaltyParkingList = new List<Id>();
        List<Id> loyaltyTierList = new List<Id>();
        List<Id> loyaltyPointsRevList = new List<Id>();
        List<Id> loyaltyDiscountsRevList = new List<Id>();
        List<Id> loyaltyHotelRevList = new List<Id>();
        List<Id> loyaltyParkingRevList = new List<Id>();
        List<Id> loyaltyTierRevList = new List<Id>();        
        
        for(Loyalty__c c : newLoyaltyList){
            
                       
            //Activate path - check if Loyalty CasinoBalance__c / Casino__c field is Less than 1	
            if((c.CasinoBalance__c < 1 && oldLoyaltyMap.get(c.Id).CasinoBalance__c != c.CasinoBalance__c) || (c.Casino__c < 1 &&  oldLoyaltyMap.get(c.Id).Casino__c != c.Casino__c)){
                loyaltyPointsList.add(c.Patron__c);
            }                
            //revoke path - check if Loyalty CasinoBalance__c / Casino__c field is greater than 1	
            else if ((c.CasinoBalance__c >= 1 && oldLoyaltyMap.get(c.Id).CasinoBalance__c != c.CasinoBalance__c) || (c.Casino__c >= 1 && oldLoyaltyMap.get(c.Id).Casino__c != c.Casino__c)) {
                loyaltyPointsRevList.add(c.Patron__c);
            }
            
            //disabling as part of POP-1436, POP-448
            /*
            //Activate path - check if Loyalty F_B_Discount_Entitlement__c or Hotel_Discount_Entitlement__c field is Less than 1
            if(c.F_B_Discount_Entitlement__c < 1 && c.Hotel_Discount_Entitlement__c < 1) {
                loyaltyDiscountsList.add(c.Patron__c);
            }
            //revoke path - check if Loyalty F_B_Discount_Entitlement__c or Hotel_Discount_Entitlement__c field is greater than 1
            else if(c.F_B_Discount_Entitlement__c >= 1 && c.Hotel_Discount_Entitlement__c >= 1){
                loyaltyDiscountsRevList.add(c.Patron__c);
            }
            //Activate path - check if Loyalty Hotel_Discount_Entitlement__c field is Less than 1
            if(c.Hotel_Discount_Entitlement__c < 1){
                loyaltyHotelList.add(c.Patron__c);
            }                 
            //revoke path - check if Loyalty Hotel_Discount_Entitlement__c field is greater than 1
            else if (c.Hotel_Discount_Entitlement__c >= 1){
                loyaltyHotelRevList.add(c.Patron__c);
            }
                
            //Activate path - check if Loyalty Comp_Parking_Entitlement__c field is changed and value is NULL
            if(c.Comp_Parking_Entitlement__c == null){
                loyaltyParkingList.add(c.Patron__c);
            }                
            //revoke path - check if Loyalty Comp_Parking_Entitlement__c field is changed and value is not NULL
            else if(c.Comp_Parking_Entitlement__c != null){
                loyaltyParkingRevList.add(c.Patron__c);
            }
            
            system.debug('%c.Tier__cc.Tier__cc.Tier__cc.Tier__c% '+c.Tier__c);
            system.debug('%c.Name.Name.Name.Name% '+c.Name);
			
			//Removing it based on the confirmation by business that "Tier" information need to be collected from Patron record, rather than Loyalty table
            //Activate path - check if Loyalty Tier__c field is changed and value is Bronze
            if(c.Name == 'Bronze'){
                loyaltyTierList.add(c.Patron__c);
            }
            //revoke path - check if Loyalty Tier__c field is changed and value is not Bronze
            else if(c.Name != 'Bronze' && c.Tier__c != null) {
                loyaltyTierRevList.add(c.Patron__c);
            }*/
        }
        
        if( !loyaltyPointsList.isEmpty() || !loyaltyDiscountsList.isEmpty() || !loyaltyHotelList.isEmpty() 
                 || !loyaltyParkingList.isEmpty() || !loyaltyTierList.isEmpty() ){
                    
            for(Exl_Restriction__c res : [SELECT Id, Restriction_Type__c, Enforcement_Status__c FROM Exl_Restriction__c 
                                          WHERE (
                                            //Restriction records that are for activation 
                                              Enforcement_Status__c != :ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_ACTIVE AND 
                                              ((Patron__c IN :loyaltyPointsList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_CASINO_POINTS ) 
                                            OR (Patron__c IN :loyaltyDiscountsList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_DISCOUNTS) 
                                            OR (Patron__c IN :loyaltyHotelList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_HOTEL) 
                                            OR (Patron__c IN :loyaltyParkingList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_PARKING)
                                            OR (Patron__c IN :loyaltyTierList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_TIER_LEVEL_LOST) ) ) ] ){
                //Update status to Active
                //Check Overridden scenario, if the loyalty values are changed to Active and our Restriction is Revoked, then mark it overridden
                if(res.Enforcement_Status__c == ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_REVOKED){
                    res.Enforcement_Status__c = ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_OVERRIDDEN;
                } else {
                    res.Enforcement_Status__c = ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_ACTIVE;
                }
                restrictionUpdateList.add(res); 
        	}
        }
        
        if(!loyaltyPointsRevList.isEmpty() || !loyaltyDiscountsRevList.isEmpty() || !loyaltyHotelRevList.isEmpty() 
                 || !loyaltyParkingRevList.isEmpty() || !loyaltyTierRevList.isEmpty() ){
            for(Exl_Restriction__c res : [SELECT Id, Restriction_Type__c, Enforcement_Status__c FROM Exl_Restriction__c 
                                          WHERE (Enforcement_Status__c != :ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_REVOKED AND 
                                              ((Patron__c IN :loyaltyPointsRevList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_CASINO_POINTS ) 
                                            OR (Patron__c IN :loyaltyDiscountsRevList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_DISCOUNTS) 
                                            OR (Patron__c IN :loyaltyHotelRevList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_HOTEL) 
                                            OR (Patron__c IN :loyaltyParkingRevList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_PARKING)
                                            OR (Patron__c IN :loyaltyTierRevList AND Restriction_Type__c =: ConstantHelper.STRING_RESTRICTION_TYPE_TIER_LEVEL_LOST) ) ) ] ){
                //Update status to Revoked
                //Check Overridden scenario, if the loyalty values are changed to revoked and our Restriction is Active, then mark it overridden
                if(res.Enforcement_Status__c == ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_ACTIVE){
                    res.Enforcement_Status__c = ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_OVERRIDDEN;
                } else {
                    res.Enforcement_Status__c = ConstantHelper.STRING_RESTRICTION_ENFORCEMENT_STATUS_REVOKED;
                }
                restrictionUpdateList.add(res);                                            
            }
        }

        //Update Restriction record 
        if(!restrictionUpdateList.isEmpty()){
            update restrictionUpdateList;
        }
        
    }
    
}