force-app/main/default/objects/MTDYTD_Trend_Data__c/MTDYTD_Trend_Data__c.object-meta.xml
<CustomObject>
    <description>Creating a custom table to display the dashboard based on the trends.</description>
    <label>MTDYTD Trend Data</label>
    <nameField>
        <displayFormat>Trend-{0000}</displayFormat>
        <label>Trend Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MTDYTD Trends Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Gaming_Days_MTD__c.field-meta.xml
<CustomField>
    <fullName>Gaming_Days_MTD__c</fullName>
    <label>Gaming_Days_MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_Brisbane__c.field-meta.xml
<CustomField>
    <fullName>Host_Brisbane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - Brisbane</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_GC__c.field-meta.xml
<CustomField>
    <fullName>Host_GC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - GC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_International__c.field-meta.xml
<CustomField>
    <fullName>Host_International__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - International</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_Sydney__c.field-meta.xml
<CustomField>
    <fullName>Host_Sydney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - Sydney</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ShareWithHostTriggerTest.cls
@isTest
public class ShareWithHostTriggerTest 
{
    static testMethod void testShareRead()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
        List<User> uu = new List<User>();
        
        while (uu.size() < 5) 
        {
            Blob b = Crypto.GenerateAESKey(128);
            String h = EncodingUtil.ConvertTohex(b);
            String uid = h.SubString(0,8);
            User u = new User(Alias = uid, Email= uid + '@myorg.com', 
                              EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/New_York', UserName= uid + '@myorg.com');      
            uu.add(u);
        }
        insert(uu);
        
        test.startTest();
        
        MTDYTD_Trend_Data__c mtd = new MTDYTD_Trend_Data__c();
        mtd.Host_Sydney__c = uu[0].id;
        mtd.Host_Brisbane__c = uu[1].id;
        mtd.Host_GC__c = uu[2].id;
        mtd.Host_International__c =  uu[3].id;   
        mtd.Gaming_Days_MTD__c = 100;
        insert mtd;
        
        mtd.Host_GC__c = uu[3].id; 
        mtd.Host_Sydney__c = uu[1].id;
        mtd.Host_Brisbane__c = uu[0].id;
        mtd.Host_International__c =  uu[0].id;   
        update mtd;
        
        test.stopTest();
    }
}