force-app/main/default/objects/MTDYTD_Trend_Data__c/MTDYTD_Trend_Data__c.object-meta.xml
<CustomObject>
    <description>Creating a custom table to display the dashboard based on the trends.</description>
    <label>MTDYTD Trend Data</label>
    <nameField>
        <displayFormat>Trend-{0000}</displayFormat>
        <label>Trend Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MTDYTD Trends Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Actual_Win_LYTDComp__c.field-meta.xml
<CustomField>
    <fullName>Actual_Win_LYTDComp__c</fullName>
    <label>Actual_Win_LYTDComp</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Actual_Win_M1to3__c.field-meta.xml
<CustomField>
    <fullName>Actual_Win_M1to3__c</fullName>
    <label>Actual_Win_M1to3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Actual_Win_M4to6__c.field-meta.xml
<CustomField>
    <fullName>Actual_Win_M4to6__c</fullName>
    <label>Actual_Win_M4to6</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Actual_Win_MTD__c.field-meta.xml
<CustomField>
    <fullName>Actual_Win_MTD__c</fullName>
    <label>Actual_Win_MTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Actual_Win_YTD__c.field-meta.xml
<CustomField>
    <fullName>Actual_Win_YTD__c</fullName>
    <label>Actual_Win_YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/CashTheo_MTD__c.field-meta.xml
<CustomField>
    <fullName>CashTheo_MTD__c</fullName>
    <label>CashTheo_MTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/CashTheo_YTD__c.field-meta.xml
<CustomField>
    <fullName>CashTheo_YTD__c</fullName>
    <label>CashTheo_YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Gaming_Days_M1to3__c.field-meta.xml
<CustomField>
    <fullName>Gaming_Days_M1to3__c</fullName>
    <label>Gaming_Days_M1to3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Gaming_Days_M4to6__c.field-meta.xml
<CustomField>
    <fullName>Gaming_Days_M4to6__c</fullName>
    <label>Gaming_Days_M4to6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Gaming_Days_MTD__c.field-meta.xml
<CustomField>
    <fullName>Gaming_Days_MTD__c</fullName>
    <label>Gaming_Days_MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Gaming_Days_YLTDComp__c.field-meta.xml
<CustomField>
    <fullName>Gaming_Days_YLTDComp__c</fullName>
    <label>Gaming_Days_YLTDComp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Gaming_Days_YTD__c.field-meta.xml
<CustomField>
    <fullName>Gaming_Days_YTD__c</fullName>
    <label>Gaming_Days_YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Unique_Patrons_LYTDComp__c.field-meta.xml
<CustomField>
    <fullName>Unique_Patrons_LYTDComp__c</fullName>
    <label>Unique_Patrons_LYTDComp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Unique_Patrons_M1to3__c.field-meta.xml
<CustomField>
    <fullName>Unique_Patrons_M1to3__c</fullName>
    <label>Unique_Patrons_M1to3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Unique_Patrons_M4to6__c.field-meta.xml
<CustomField>
    <fullName>Unique_Patrons_M4to6__c</fullName>
    <label>Unique_Patrons_M4to6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Unique_Patrons_MTD__c.field-meta.xml
<CustomField>
    <fullName>Unique_Patrons_MTD__c</fullName>
    <label>Unique_Patrons_MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Unique_Patrons_YTD__c.field-meta.xml
<CustomField>
    <fullName>Unique_Patrons_YTD__c</fullName>
    <label>Unique_Patrons_YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReportSDataFetchBatch.cls
/**
 * @description       : 
 * @author            : sakshi.chauhan@simplus.com
 * @group             : 
 * @last modified on  : 11-24-2020
 * @last modified by  : sakshi.chauhan@simplus.com
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   11-24-2020   sakshi.chauhan@simplus.com   Initial Version
**/
public with sharing class ReportSDataFetchBatch implements Database.Batchable<sObject>, Database.Stateful {
    String query = 'SELECT Gaming_Days_YTD__c,Unique_Patrons_YTD__c, Actual_Win_YTD__c,Gaming_Days_YLTDComp__c, '
                    + 'Unique_Patrons_LYTDComp__c,Actual_Win_LYTDComp__c,'
                    + 'Gaming_Days_MTD__c,Unique_Patrons_MTD__c, Actual_Win_MTD__c, Actual_Win_M1to3__c, Actual_Win_M4to6__c, '
                    + 'Gaming_Days_M1to3__c,Gaming_Days_M4to6__c,'
                    + 'Unique_Patrons_M1to3__c,Unique_Patrons_M4to6__c, CashTheo_MTD__c, CashTheo_YTD__c'
                    + ' FROM MTDYTD_Trend_Data__c';
    Integer total = 0;
    ReportsDataWrapper dataWrap = new ReportsDataWrapper();
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
 
    public void execute( Database.BatchableContext BC,List<MTDYTD_Trend_Data__c> scope){
        try{
            
            total += scope.size();
            for( MTDYTD_Trend_Data__c loopVar: scope){
               
                dataWrap.UniqueYTD += loopVar.Unique_Patrons_YTD__c;
                dataWrap.ActualYTD += loopVar.Actual_Win_YTD__c;
                dataWrap.TripsYTD += loopVar.Gaming_Days_YTD__c;

                dataWrap.UniqueMTD += loopVar.Unique_Patrons_MTD__c;
                dataWrap.ActualMTD += loopVar.Actual_Win_MTD__c;
                dataWrap.TripsMTD += loopVar.Gaming_Days_MTD__c;

                dataWrap.TripsBaseYTD += loopVar.Gaming_Days_YLTDComp__c;
                dataWrap.UniqueBaseYTD += loopVar.Unique_Patrons_LYTDComp__c;
                

                dataWrap.ActualMTDTop += loopVar.Actual_Win_M1to3__c;
                dataWrap.ActualMTDBase += loopVar.Actual_Win_M4to6__c;

                dataWrap.ActualBaseYTD += loopVar.Actual_Win_LYTDComp__c;

                dataWrap.TripsMTDTop += loopVar.Gaming_Days_M1to3__c;
                dataWrap.TripsMTDBase += loopVar.Gaming_Days_M4to6__c;

                dataWrap.UniqueMTDTop += loopVar.Unique_Patrons_M1to3__c;
                dataWrap.UniqueMTDBase += loopVar.Unique_Patrons_M4to6__c;
                

                dataWrap.MTDTheoCurrent += loopVar.CashTheo_MTD__c;
                dataWrap.YTDTheoCurrent += loopVar.CashTheo_YTD__c;
                

            }
            
        }
        catch(Exception e){
            system.debug(e.getCause() + ' '+ e.getMessage() + ' '+ e.getStackTraceString());
        }
        
        
    }
 
    public void finish(Database.BatchableContext BC){
        system.debug(dataWrap);
        system.debug('total '+ total);
    }
}