force-app/main/default/objects/User/fields/Portal_ReLoginRequired__c.field-meta.xml
<CustomField>
    <fullName>Portal_ReLoginRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal_ReLoginRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Custom Field created for Member Portal to store the ID_Token passed from Ping One Auth provider for Portal users.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Token_A__c.field-meta.xml
<CustomField>
    <fullName>Token_A__c</fullName>
    <description>Custom Field created for Member Portal to store access token returned from Ping One Auth Provider for Portal User.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token A</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PortalExcludedUserCheckControllerTest.cls
@isTest
public class PortalExcludedUserCheckControllerTest {
    @testSetup 
    static void setup() {
        User us = [SELECT Id, token__c, token_a__c FROM User WHERE Id = :UserInfo.getUserId()];
        us.token__c = '1234';
        us.token_a__c = '2345';
        us.Portal_ReLoginRequired__c = true;
        update us;
    }
    
    @isTest 
    static void generatePASTest1() {
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseSuccess());
        Object response1 = PortalExcludedUserCheckController.getUserDetails();
        System.debug('Response for Test1: ' + response1);
        System.assertEquals('RELOGIN_REQUIRED', response1, 'Test1: Expected RELOGIN_REQUIRED');
        Test.StopTest();
    }
    
    @isTest 
    static void generatePASTest2() {
        User us = [SELECT Id, token__c, token_a__c FROM User WHERE Id = :UserInfo.getUserId()];
        us.token__c = '12345';
        us.token_a__c = '23456';
        us.Portal_ReLoginRequired__c = false;
        update us;
        
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseSuccess());
        Object response2 = PortalExcludedUserCheckController.getUserDetails();
        System.debug('Response for Test2: ' + response2);
        Test.StopTest();
    }

    private class MockHttpResponseSuccess implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(202);
            
            if (req.getEndpoint().contains('userinfo')) {
                res.setBody('{"isExcluded": "TRUE"}');
            } else {
                res.setBody('{"AccessToken": "mockAccessToken123", "status": "Success"}');
            }
            
            return res;
        }
    }
}