force-app/main/default/objects/User/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Custom Field created for Member Portal to store the ID_Token passed from Ping One Auth provider for Portal users.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Token_A__c.field-meta.xml
<CustomField>
    <fullName>Token_A__c</fullName>
    <description>Custom Field created for Member Portal to store access token returned from Ping One Auth Provider for Portal User.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token A</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PortalValidatePINCOntrollerTest.cls
@isTest
public class PortalValidatePINCOntrollerTest {
    @testSetup static void setup() {
        // Create common test accounts
        Id uId = UserInfo.getUserId();
        User us = [select Id,ContactId,token__c,token_a__c from User where Id =:uId];
        us.token__c = '1234';
        us.token_a__c = '2345';
        update us;
        
    }
    @isTest static void testValidatePIN() {
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new HttpCallout());
        //Object test = new Object();
        String response = PortalValidatePINController.validatePIN('test');
        System.assertEquals('200', response,'Response not received');
        Test.Stoptest();
    }
    @isTest static void updatePINTest() {
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new HttpCallout()); 
        Integer response1 = PortalValidatePINController.updatePIN('test','test');
        System.assertEquals(200, response1,'Response not received');
        Test.Stoptest();
    }
}