force-app/main/default/objects/Carbon_Comparison__e/Carbon_Comparison__e.object-meta.xml
<CustomObject>
    <label>Carbon Comparison</label>
    <pluralLabel>Carbon Comparisons</pluralLabel>
</CustomObject>

force-app/main/default/objects/Carbon_Comparison__e/fields/Annual_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Annual_Mileage__c</fullName>
    <label>Annual Mileage</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Carbon_Comparison__e/fields/Current_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Current_Vehicle__c</fullName>
    <label>Current Vehicle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carbon_Comparison__e/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <label>Model Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AWSEvent.cls
/*
 * Converts a platform event to a JSON string format representation.
 * Modify this class based on your platform event fields.
 */
global class AWSEvent {
    public String eventToJSON;
    public AWSEvent(Carbon_Comparison__e event) {
        eventToJSON = '{ \"Annual_Mileage__c\": \"' + event.Annual_Mileage__c + '\",';
        eventToJSON += '\"Current_Vehicle__c\": \"' + event.Current_Vehicle__c + '\",';
        eventToJSON += '\"Model_Year__c\": \"' + event.Model_Year__c + '\"}';
    }
    public String getEventToJSON() {
        return this.eventToJSON;
    }
}