force-app/main/default/objects/AgeCalculationSetting__c/AgeCalculationSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Age Calculation Setting</label>
</CustomObject>

force-app/main/default/objects/AgeCalculationSetting__c/fields/Disable_Date_Filter__c.field-meta.xml
<CustomField>
    <fullName>Disable_Date_Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this field is checked batch will not check if today&apos;s date is the same Date of Birth on Record</description>
    <inlineHelpText>When this field is checked batch will not check if today&apos;s date is the same Date of Birth on Record</inlineHelpText>
    <label>Disable Date Filter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AgeCalculationSetting__c/fields/Month_To_Process__c.field-meta.xml
<CustomField>
    <fullName>Month_To_Process__c</fullName>
    <description>If this field is populated and disable date filter is true, the batch will only be processing records for those under that month
Month is number e.g. January = 1, February = 2, etc.</description>
    <inlineHelpText>If this field is populated and disable date filter is true, the batch will only be processing records for those under that month
Month is number e.g. January = 1, February = 2, etc.</inlineHelpText>
    <label>Month To Process</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactAgeCalculationBatchTest.cls
/**
* @File Name          : ContactAgeCalculationBatchTest.apxc
* @Description        : Test Class for ContactAgeCalculationBatch
* @Author             : Rhys Dela Cruz
* @Group              : Simplus
* @Last Modified By   : Rhys Dela Cruz
* @Last Modified On   : 15/03/21
**/
@isTest public class ContactAgeCalculationBatchTest {

    @isTest static void ageCalcTestMethod1(){

        Contact cont = new Contact();
        cont.FirstName = 'First Name Test';
        cont.LastName = 'Last Name Test';
        cont.Date_of_Birth__c = Date.valueOf('1950-'+System.today().month() + '-' + System.today().day());

        insert cont;

        Test.startTest();
        Database.executeBatch(new ContactAgeCalculationBatch());
        Test.stopTest();
    }

    @isTest static void ageCalcTestMethod2(){

        Contact cont = new Contact();
        cont.FirstName = 'First Name Test';
        cont.LastName = 'Last Name Test';
        cont.Date_of_Birth__c = Date.valueOf('1950-'+System.today().month() + '-' + System.today().day());

        insert cont;

        Test.startTest();
        String sch = '0 48 * * * ?'; 
        System.schedule('Test Age Calc Batch', sch, new ContactAgeCalculationBatch());
        Test.stopTest();
    }

    @isTest static void ageCalcTestMethod3(){

        Contact cont = new Contact();
        cont.FirstName = 'First Name Test';
        cont.LastName = 'Last Name Test';
        cont.Date_of_Birth__c = Date.valueOf('1950-'+System.today().month() + '-' + System.today().day());

        insert cont;

        Test.startTest();
        String sch = '0 48 * * * ?'; 
        Database.executeBatch(new ContactAgeCalculationBatch(new Set<String>{cont.Id}));
        Test.stopTest();
    }

    @isTest static void ageCalcTestMethod4(){

        Contact cont = new Contact();
        cont.FirstName = 'First Name Test';
        cont.LastName = 'Last Name Test';
        cont.Date_of_Birth__c = Date.valueOf('1950-'+System.today().month() + '-' + System.today().day());

        insert cont;

        AgeCalculationSetting__c calcSetting = AgeCalculationSetting__c.getOrgDefaults();
        calcSetting.Disable_Date_Filter__c = true;
        calcSetting.Month_to_Process__c = 3;
        upsert calcSetting;

        Test.startTest();
        Database.executeBatch(new ContactAgeCalculationBatch(new Set<String>{cont.Id}));
        Test.stopTest();
    }

    @isTest static void ageCalcTestMethod5(){

        Contact cont = new Contact();
        cont.FirstName = 'First Name Test';
        cont.LastName = 'Last Name Test';
        cont.Date_of_Birth__c = Date.valueOf('1950-'+System.today().month() + '-' + System.today().day()).addDays(1);

        insert cont;

        AgeCalculationSetting__c calcSetting = AgeCalculationSetting__c.getOrgDefaults();
        calcSetting.Disable_Date_Filter__c = true;
        calcSetting.Month_to_Process__c = 3;
        upsert calcSetting;

        Test.startTest();
        Database.executeBatch(new ContactAgeCalculationBatch(new Set<String>{cont.Id}));
        Test.stopTest();
    }
}