force-app/main/default/objects/Contact/fields/Are_they_full_time_part_time_or_casual__c.field-meta.xml
<CustomField>
    <fullName>Are_they_full_time_part_time_or_casual__c</fullName>
    <description>Contains the work timing for Individuals</description>
    <label>Are they full time, part time or casual?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Casual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Australian_Business_Number_ABN__c.field-meta.xml
<CustomField>
    <fullName>Australian_Business_Number_ABN__c</fullName>
    <description>Use to Australian Business Number (ABN) for business</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Australian Business Number (ABN)</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bulk_Update_for_Data_Fix__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Update_for_Data_Fix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bulk Update for Data Fix</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_card__c.field-meta.xml
<CustomField>
    <fullName>Business_card__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Documents_that_prove_their_business__c.field-meta.xml
<CustomField>
    <fullName>Documents_that_prove_their_business__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Documents that prove their business?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/How_long_have_they_worked__c.field-meta.xml
<CustomField>
    <fullName>How_long_have_they_worked__c</fullName>
    <description>Use to store duration</description>
    <encryptionScheme>None</encryptionScheme>
    <label>How long have they worked for business?</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/If_Gov_Law_Enforcement_Dept_Location__c.field-meta.xml
<CustomField>
    <fullName>If_Gov_Law_Enforcement_Dept_Location__c</fullName>
    <description>If in Government or Law Enforcement, which department or body do they work for and where is it located?</description>
    <encryptionScheme>None</encryptionScheme>
    <label>If Gov/Law Enforcement? Dept &amp; Location?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Name_of_business_or_company__c.field-meta.xml
<CustomField>
    <fullName>Name_of_business_or_company__c</fullName>
    <description>Contain the name of a business or company</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of business or company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Other_employment_roles__c.field-meta.xml
<CustomField>
    <fullName>Other_employment_roles__c</fullName>
    <description>Store Employment Roles</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Other employment roles</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Professional_qualifications__c.field-meta.xml
<CustomField>
    <fullName>Professional_qualifications__c</fullName>
    <description>Store Qualifications Details</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Professional qualifications</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Refused_to_provide_SOW__c.field-meta.xml
<CustomField>
    <fullName>Refused_to_provide_SOW__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Reminder to complete the Unusual Activity Referral form</inlineHelpText>
    <label>Refused to provide SOW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Retired_Pre_retirement_employment__c.field-meta.xml
<CustomField>
    <fullName>Retired_Pre_retirement_employment__c</fullName>
    <description>Store the details If Retired, what was their employment prior to retirement?</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Retired? Pre-retirement employment?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Source_of_Wealth__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Wealth__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Source of Wealth for Business</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Present_means_of_support__c.field-meta.xml
<CustomField>
    <fullName>Student_Present_means_of_support__c</fullName>
    <description>Store the Info about If a Student? how do they support themselves?</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Student? Present means of support?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Their_role_in_that_business__c.field-meta.xml
<CustomField>
    <fullName>Their_role_in_that_business__c</fullName>
    <description>Use to store individual role in the business</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Their role in that business</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Their_role_Job_title_within_the_business__c.field-meta.xml
<CustomField>
    <fullName>Their_role_Job_title_within_the_business__c</fullName>
    <description>Contain role or title within the business</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Their role/Job title within the business</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/What_does_the_business_do__c.field-meta.xml
<CustomField>
    <fullName>What_does_the_business_do__c</fullName>
    <description>Use to store Business Work Details</description>
    <encryptionScheme>None</encryptionScheme>
    <label>What does the business do?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Who_do_they_work_for_employer_details__c.field-meta.xml
<CustomField>
    <fullName>Who_do_they_work_for_employer_details__c</fullName>
    <description>use to store employer details</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Who do they work for (employer details)?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source_of_Wealth__c/Source_of_Wealth__c.object-meta.xml
<CustomObject>
    <label>Source of Wealth</label>
    <nameField>
        <displayFormat>SOW-{0}</displayFormat>
        <label>Source of Wealth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source of Wealth</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SOWBatchJob.cls
/**
* @File Name          : SOWBatchJob.apxc
* @Description        : Batch Job that runs everyday to update 'Bulk_Update_for_Data_Fix__c' field of up to 50 Contact records
* @Author             : Gil Panican
* @Group              : Simplus
* @Last Modified By   : Gil Panican
* @Last Modified On   : 03/08/22
**/
global class SOWBatchJob implements Database.Batchable<sObject>,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id,Source_of_Wealth__c,Who_do_they_work_for_employer_details__c,Their_role_in_that_business__c,Are_they_full_time_part_time_or_casual__c,'+
            'How_long_have_they_worked__c,Student_Present_means_of_support__c,Retired_Pre_retirement_employment__c,Other_employment_roles__c,Professional_qualifications__c,'+
            'If_Gov_Law_Enforcement_Dept_Location__c,Name_of_business_or_company__c,Their_role_Job_title_within_the_business__c,What_does_the_business_do__c,'+
            'Australian_Business_Number_ABN__c,Documents_that_prove_their_business__c,Business_card__c '+
            'FROM Contact WHERE (Source_of_Wealth__c <> NULL or Who_do_they_work_for_employer_details__c <> NULL or Their_role_in_that_business__c <> NULL '+ 
            'or Are_they_full_time_part_time_or_casual__c <> NULL or How_long_have_they_worked__c <> NULL or Student_Present_means_of_support__c <> NULL '+
            'or Retired_Pre_retirement_employment__c <> NULL or Other_employment_roles__c <> NULL or Professional_qualifications__c <> NULL '+
            'or If_Gov_Law_Enforcement_Dept_Location__c <> NULL or Name_of_business_or_company__c <> NULL or Their_role_Job_title_within_the_business__c <> NULL '+
            'or What_does_the_business_do__c <> NULL or Australian_Business_Number_ABN__c <> NULL or Documents_that_prove_their_business__c <> NULL or Business_card__c <> NULL) '+
            'AND (Refused_to_provide_SOW__c = false) AND (Bulk_Update_for_Data_Fix__c = false) limit 50';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> contList){
        System.debug('***Batch Started***');
        System.debug('Number of Records included: ' + contList.size());
        for (Contact contRec : contList){
            contRec.Bulk_Update_for_Data_Fix__c = true;
        }
        Database.update(contList, false);
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('***Batch Finished***');
    }
    
    global void execute(SchedulableContext sc) {
        SOWBatchJob b = new SOWBatchJob();
        Database.executebatch(b);
    }
}