force-app/main/default/objects/Contact/fields/Bulk_Update_for_Data_Fix__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Update_for_Data_Fix__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bulk Update for Data Fix</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Name_of_business_or_company__c.field-meta.xml
<CustomField>
    <fullName>Name_of_business_or_company__c</fullName>
    <description>Contain the name of a business or company</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Name of business or company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Refused_to_provide_SOW__c.field-meta.xml
<CustomField>
    <fullName>Refused_to_provide_SOW__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Reminder to complete the Unusual Activity Referral form</inlineHelpText>
    <label>Refused to provide SOW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SOW_Id__c/SOW_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SOW Id</label>
</CustomObject>

force-app/main/default/objects/SOW_Id__c/fields/Is_updated__c.field-meta.xml
<CustomField>
    <fullName>Is_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is updated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SOWBatchJobTest.cls
@isTest()
public class SOWBatchJobTest{
    
    @IsTest
    static void test_LoyaltyObjectUpdate(){
        List<Contact> conList = new List<Contact>();
        date dob = date.newInstance(1990, 11, 21);
        
        //Patron
        for(Integer x = 0 ; x<=10;x++)
            conList.add(new Contact(
                lastName = 'Patron' +x,
                firstName = 'Testing'+x,
                Date_of_Birth__c = dob
            ));
        if(conList.size()>0){
            insert conList;
        }
        
        conList[0].Name_of_business_or_company__c = 'test';
        conList[0].Refused_to_provide_SOW__c = false;
        conList[0].Bulk_Update_for_Data_Fix__c = false;
        update conList;
        
        insert new SOW_Id__c(Is_updated__c = false, Name = 'Test1');

        Test.startTest();
        SOWBatchJob batch1 = new SOWBatchJob();
        SOWBatchJob1700 batch2 = new SOWBatchJob1700();
        String sch = '0 1 * * * ?';
        system.schedule('Test Schedule for SOWBatchJob', sch, batch1);
        system.schedule('Test Schedule for SOWBatchJob1700', sch, batch2);
        Test.stopTest();
        
    }
    
    @IsTest 
    static void test_SOWJobScheduler(){
        Test.startTest();
        SOWJobScheduler.runSOWBatchJob();
        SOWJobScheduler.deleteSOWBatchJob();
        SOWJobScheduler.runSOWBatchJob1700();
        SOWJobScheduler.deleteSOWBatchJob1700();
        Test.stopTest();
        
    }
}