force-app/main/default/objects/Contact/fields/Direct_Mail_Consent__c.field-meta.xml
<CustomField>
    <fullName>Direct_Mail_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Mail Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Consent__c.field-meta.xml
<CustomField>
    <fullName>Email_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Email_Update_Sync_Wait__c.field-meta.xml
<CustomField>
    <fullName>Portal_Email_Update_Sync_Wait__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom Field created for Member Portal to wait for Email Update to be synced from MDM.</description>
    <label>Portal Email Update Sync Wait</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Email_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Portal_Email_Updated_Time__c</fullName>
    <description>Custom Field created for Member Portal to wait for Email Update to be synced from MDM.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Portal Email Updated Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Mobile_Update_Sync_Wait__c.field-meta.xml
<CustomField>
    <fullName>Portal_Mobile_Update_Sync_Wait__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom Field created for Member Portal to sync the Mobile update from MDM to Salesforce.</description>
    <label>Portal Mobile Update Sync Wait</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Mobile_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Portal_Mobile_Updated_Time__c</fullName>
    <description>Custom Field created for Member Portal to sync the Mobile update from MDM to Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Portal Mobile Updated Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Address__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Address__c</fullName>
    <label>Preferred Address</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential Address</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SMS_Consent__c.field-meta.xml
<CustomField>
    <fullName>SMS_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Portal_Client_Credentials__mdt/Portal_Client_Credentials__mdt.object-meta.xml
<CustomObject>
    <label>Portal Client Credentials</label>
    <pluralLabel>Portal Client Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Client_Credentials__mdt/fields/Authorize_URL__c.field-meta.xml
<CustomField>
    <fullName>Authorize_URL__c</fullName>
    <label>Authorize URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Client_Credentials__mdt/fields/Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Policy_ID__c</fullName>
    <label>Policy ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Client_Credentials__mdt/fields/Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URL__c</fullName>
    <label>Redirect URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Client_Credentials__mdt/fields/Target_URL__c.field-meta.xml
<CustomField>
    <fullName>Target_URL__c</fullName>
    <label>Target URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <formula>Contact.Patron_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patron ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Portal_EmailVerified__c.field-meta.xml
<CustomField>
    <fullName>Portal_EmailVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal_emailverified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Portal_LoginMethod__c.field-meta.xml
<CustomField>
    <fullName>Portal_LoginMethod__c</fullName>
    <label>Portal_LoginMethod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pin</fullName>
            </value>
            <value>
                <fullName>pwd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Portal_PhoneNumberVerified__c.field-meta.xml
<CustomField>
    <fullName>Portal_PhoneNumberVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal_PhoneNumberVerified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Portal_ReLoginRequired__c.field-meta.xml
<CustomField>
    <fullName>Portal_ReLoginRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal_ReLoginRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Custom Field created for Member Portal to store the ID_Token passed from Ping One Auth provider for Portal users.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PortalAccountDetailsPageHandler.cls
public class PortalAccountDetailsPageHandler {
    public Static Contact con;
    
    @AuraEnabled
    public static Contact getContactDetails(){
        try{
            Id uId = UserInfo.getUserId();
            User us = [select Id,ContactId,token__c from User where Id =:uId];
            system.debug('id token'+us.token__c);
            con = new Contact();
            Id conId = us.ContactId;
            if(conId != null){
                con = [select Id,Patron_ID__c,FirstName,Name,Email,MobilePhone,HomePhone,MailingStreet,MailingState,MailingCity,MailingCountry,MailingPostalCode,OtherStreet,OtherCity,OtherState,OtherCountry,OtherPostalCode,Direct_Mail_Consent__c,Preferred_Address__c,Email_Consent__c,SMS_Consent__c,Portal_Email_Update_Sync_Wait__c,Portal_Mobile_Update_Sync_Wait__c from Contact where Id=:conId];
            }
        }catch (Exception e){
            //execute the Error Logger object
            ErrorLogger.createLog('PortalAccountDetailsPageHandler', 'getContactDetails', e, '', 'Apex Class');
        }
        return con;
    }
    
    @AuraEnabled
    public static Map<String, Object> getContactAndUserDetails() {
        Map<String, Object> responseMap = new Map<String, Object>();
        
        try {
            Id uId = UserInfo.getUserId();
            // Fetch the User record along with the additional fields from the User object
            User us = [SELECT Id, ContactId, token__c, Portal_EmailVerified__c, Portal_PhoneNumberVerified__c, Portal_LoginMethod__c 
                       FROM User 
                       WHERE Id =: uId];
            
            responseMap.put('userEmailVerified', us.Portal_EmailVerified__c);
            responseMap.put('userPhoneVerified', us.Portal_PhoneNumberVerified__c);
            responseMap.put('loginWithPIN', us.Portal_LoginMethod__c != null && us.Portal_LoginMethod__c.contains('pin'));
            // Fetch Contact details if the User has a related Contact
            if (us.ContactId != null) {
                con = [SELECT Id, Patron_ID__c, FirstName, Name, Email, MobilePhone, HomePhone, 
                       MailingStreet, MailingState, MailingCity, MailingCountry, MailingPostalCode, 
                       OtherStreet, OtherCity, OtherState, OtherCountry, OtherPostalCode, 
                       Direct_Mail_Consent__c, Preferred_Address__c, Email_Consent__c, 
                       SMS_Consent__c, Portal_Email_Update_Sync_Wait__c, Portal_Mobile_Update_Sync_Wait__c 
                       FROM Contact 
                       WHERE Id =: us.ContactId];
                responseMap.put('contact', con);
            }
        } catch (Exception e) {
            // Log the error
            ErrorLogger.createLog('PortalAccountDetailsPageHandler', 'getContactAndUserDetails', e, '', 'Apex Class');
        }
        
        return responseMap;
    }
    
    @AuraEnabled
    public static Contact contactSyncUpdate(String event_type){
        try{
            Id uId = UserInfo.getUserId();
            User us = [select Id,ContactId,token__c from User where Id =:uId];
            con = new Contact();
            Id conId = us.ContactId;
            if(conId != null){
                con = [select Id,Patron_ID__c,FirstName,Name,Email,MobilePhone,HomePhone,MailingStreet,MailingState,MailingCity,MailingCountry,MailingPostalCode,OtherStreet,OtherCity,OtherState,OtherCountry,OtherPostalCode,Direct_Mail_Consent__c,Preferred_Address__c,Email_Consent__c,SMS_Consent__c,Portal_Email_Update_Sync_Wait__c,Portal_Mobile_Update_Sync_Wait__c from Contact where Id=:conId];
            }
            system.debug('event_type'+event_type);
            if(event_type != null){
                if(event_type == 'Email Update'){
                    con.Portal_Email_Update_Sync_Wait__c = true;
                    con.Portal_Email_Updated_Time__c = System.now();
                }else if(event_type == 'Mobile Update'){
                    con.Portal_Mobile_Update_Sync_Wait__c = true;
                    con.Portal_Mobile_Updated_Time__c = System.now();
                }
                update con;
            }
        }catch (Exception e){
            //execute the Error Logger object
            ErrorLogger.createLog('PortalAccountDetailsPageHandler', 'getContactDetails', e, '', 'Apex Class');
        }
        return con;
    }
    @AuraEnabled
    public static void updateContactDetails(Boolean emailConsent, Boolean smsConsent, String prefAdd) {
        Contact con1 = getContactDetails();
        system.debug('con1 :11: ' + con1);
        system.debug('emailConsent :11: ' + emailConsent);
        system.debug('smsConsent :11: ' + smsConsent);
        system.debug('prefAdd :11: ' + prefAdd);

        if (con1.Email_Consent__c != emailConsent) {
            con1.Email_Consent__c = emailConsent;
        }
        if (con1.SMS_Consent__c != smsConsent) {
            con1.SMS_Consent__c = smsConsent;
        }
        
        if (prefAdd != null && !String.isEmpty(prefAdd) && !String.isBlank(prefAdd)) {
            if (con1.Preferred_Address__c != prefAdd || !con1.Direct_Mail_Consent__c) {
                con1.Direct_Mail_Consent__c = true;
                con1.Preferred_Address__c = prefAdd;
            }
        } else {
            // Only set Direct_Mail_Consent__c to false if prefAdd is explicitly an empty string
            con1.Direct_Mail_Consent__c = false;
            con1.Preferred_Address__c = '';
        }

        try {
            system.debug('con1 :22: ' + con1);
            update con1;
        } catch (DmlException e) {
            ErrorLogger.createLog('PortalAccountDetailsPageHandler', 'updateContactDetails', e, '', 'Apex Class');
        }
    }

    @AuraEnabled
    public static Map<String,String> getPingOneURLS(){
        Map<String,String> pingOneMap = new Map<String,String>();
        try{
            List<Portal_Client_Credentials__mdt> urlList = [Select Id,MasterLabel,Client_ID__c,Authorize_URL__c,Policy_ID__c,Redirect_URL__c,Target_URL__c from Portal_Client_Credentials__mdt where MasterLabel LIKE '%PingOne Update'];
            for(Portal_Client_Credentials__mdt url : urlList){
                String pingUrl = url.Authorize_URL__c + '?client_id=' + url.Client_ID__c + '&redirect_uri=' + url.Redirect_URL__c + '&target_link_uri=' + url.Target_URL__c + '&response_type=code&scope=openid%20role&acr_values=' + url.Policy_ID__c;
                pingOneMap.put(url.MasterLabel,pingUrl);
            }
        }catch(DmlException e) {
            ErrorLogger.createLog('PortalAccountDetailsPageHandler', 'getPingOneURLS', e, '', 'Apex Class');
        }
        system.debug('pingOneMap==>'+pingOneMap);
        return pingOneMap;
    }
    
    @AuraEnabled
    public static void updatePortalReLoginRequired() {
        Id userId = UserInfo.getUserId();
        List<User> userRecords = [SELECT Id, Portal_ReLoginRequired__c FROM User WHERE Id = :userId LIMIT 1];
        
        if (!userRecords.isEmpty()) {
            User userRecord = userRecords[0];
            userRecord.Portal_ReLoginRequired__c = true;
            
            try {
                update userRecord;
            } catch (Exception e) {
                System.debug('Error updating Portal_ReLoginRequired: ' + e.getMessage());
                throw new AuraHandledException('Error updating user information');
            }
        } else {
            throw new AuraHandledException('User record not found');
        }
    }
    
}