force-app/main/default/objects/Contact/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loyalty Program</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/CasinoBalance__c.field-meta.xml
<CustomField>
    <fullName>CasinoBalance__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/CompBalance__c.field-meta.xml
<CustomField>
    <fullName>CompBalance__c</fullName>
    <label>Comp $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Last_Successful_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Successful Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Balance__c.field-meta.xml
<CustomField>
    <fullName>Tier_Balance__c</fullName>
    <label>Tier Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Month__c</fullName>
    <label>Tier Points Earned This Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Week__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Week__c</fullName>
    <label>Tier Points Earned This Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_Today__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_Today__c</fullName>
    <label>Tier Points Earned Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/LoyaltyDay__c/LoyaltyDay__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is use for testing Loyalty Batch Class</description>
    <label>Loyalty Day</label>
</CustomObject>

force-app/main/default/objects/LoyaltyDay__c/fields/Add_Day__c.field-meta.xml
<CustomField>
    <fullName>Add_Day__c</fullName>
    <description>Add or subtract days that is to be use in the Loyalty Batch class testing</description>
    <label>Add Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyLastSuccessfulUpdateBatchTest.cls
@isTest
public class LoyaltyLastSuccessfulUpdateBatchTest{
    @TestSetup
    private static void testDataSetup(){
        List<Contact> conList = new List<Contact>();
        List<Loyalty_Program__c> lpList = new List<Loyalty_Program__c>();
        
        date dob = date.newInstance(1990, 11, 21);
        
        //Patron
        for(Integer x = 0 ; x<=10;x++)
            conList.add(new Contact(
                lastName = 'Patron' +x,
                firstName = 'Testing'+x,
                Date_of_Birth__c = dob
            ));
        if(conList.size()>0){insert conList;}
        
        for(Integer x = 0 ; x<=10;x++)
            lpList.add(new Loyalty_Program__c(
                Name = 'Star Gold' +x
            ));
        if(lpList.size()>0){insert lpList;}
        //Loyalty
        System.debug('PATRON LIST : ' +conList);
        System.debug('LOYALTY PROGRAM LIST : ' +lpList);
    }
    
    @IsTest 
    static void test_LoyaltyObjectUpdate(){
        Contact con = [SELECT Id,Name FROM Contact WHERE LastName = 'Patron0' Limit 1];
        Loyalty_Program__c lp = [Select Id,Name From Loyalty_Program__c Where Name = 'Star Gold0' Limit 1];
        List<Loyalty__c> loList = new List<Loyalty__c>();
        
        insert new LoyaltyDay__c(Add_Day__c = 0);
        
        Loyalty__c loy = new Loyalty__c();
        loy.Name ='Test Gold';
        loy.Tier_Points_Earned_Today__c = 10;
        loy.Tier_Points_Earned_This_Week__c=20;
        loy.Tier_Points_Earned_This_Month__c =300;
        loy.External_ID__c = null;
        loy.last_successful_update__C = '';
        loy.CasinoBalance__c = null;
        loy.CompBalance__c = null;
        loy.Tier_Balance__c = null;
        loy.Tier__c = 'Gold';
        loy.Loyalty_Program__c = lp.Id;
        loy.Patron__c = con.id;
        loList.add(loy);
        insert loList;
        
        Test.startTest();
        LoyaltyLastSuccessfulUpdateBatch batch = new LoyaltyLastSuccessfulUpdateBatch();
        String sch = '0 1 * * * ?';
        system.schedule('Test Sched', sch, batch);
        Test.stopTest();
        
        System.assertEquals(true, loList[0].last_successful_update__C != null, 'field is blank');
    }
}