force-app/main/default/objects/Contact/fields/Home_Property__c.field-meta.xml
<CustomField>
    <fullName>Home_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactSelector.cls
public With Sharing class ContactSelector {
    // Define the fields to be queried
    private static final List<String> FIELDS = new List<String>{
        'Id',
            'Name',
            'Patron_ID__c',
            'Home_Property__r.Name',
            'Home_Property__c',
            'createdDate'
            };
                // Method to build the SOQL query string
                private static String buildQueryString(String objectAPI, String whereClause) {
                    return 'SELECT ' + String.join(FIELDS, ', ') + ' FROM ' + objectAPI + ' WHERE ' + whereClause;
                }
    
    public static List<Contact> getContactByIds(Set<Id> sFIdSet) {
        if (sFIdSet.isEmpty()) return new List<Contact>();
        String whereClause = 'Id IN: sFIdSet ';
        return executeQuery('Contact', whereClause, sFIdSet, null);
    }
    
    public static List<Contact> getContactByExtIds(Set<String> extIdSet) {
        if (extIdSet.isEmpty()) return new List<Contact>();
        String whereClause = 'Patron_ID__c IN: extIdSet ';
        return executeQuery('Contact', whereClause, null,extIdSet);
    }
    
    // Helper method to construct WHERE clauses
    private static String buildWhereClause(String field, String value) {
        return value != null && !string.isBlank(value) ? ' AND ' + field + ' = \'' + String.escapeSingleQuotes(value) + '\'' : '';
    }
    
    // Method to execute the query
    private static List<Contact> executeQuery(String objectAPI, String whereClause, Set<Id> sFIdSet, Set<String> extIdSet) {
        String queryString = buildQueryString(objectAPI, whereClause);
        system.debug('Final Query '+queryString);
        return Database.query(queryString);
    }
    
}