force-app/main/default/objects/Contact/fields/Host_Brisbane__c.field-meta.xml
<CustomField>
    <fullName>Host_Brisbane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - Brisbane</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Host_GC__c.field-meta.xml
<CustomField>
    <fullName>Host_GC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - GC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Host_International__c.field-meta.xml
<CustomField>
    <fullName>Host_International__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - International</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Host_Sydney__c.field-meta.xml
<CustomField>
    <fullName>Host_Sydney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - Sydney</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/MTDYTD_Trend_Data__c.object-meta.xml
<CustomObject>
    <description>Creating a custom table to display the dashboard based on the trends.</description>
    <label>MTDYTD Trend Data</label>
    <nameField>
        <displayFormat>Trend-{0000}</displayFormat>
        <label>Trend Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MTDYTD Trends Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MTDYTD Trends Data</relationshipLabel>
    <relationshipName>MTDYTD_Trends_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_Brisbane__c.field-meta.xml
<CustomField>
    <fullName>Host_Brisbane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - Brisbane</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_GC__c.field-meta.xml
<CustomField>
    <fullName>Host_GC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - GC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_International__c.field-meta.xml
<CustomField>
    <fullName>Host_International__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - International</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Host_Sydney__c.field-meta.xml
<CustomField>
    <fullName>Host_Sydney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host - Sydney</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MTDYTD_Trends_Data3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MTDYTD_Trend_Data__c/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patron_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Update_MTDY_ContactHostTriggerHandler.cls
/**
* @File Name          : Update_MTDY_ContactHostTriggerHandler
* @Description        : 
* @Author             : Lawrence Faith Abella
* @Group              : Simplus
* @Last Modified By   : Lawrence Faith Abella
* @Last Modified On   : 12/03/21
* @Description 		  : Field Mapping 
Update ContactId mapping from Contact Host fields into MTD YTD trend object everytime there is a change on the MTDYTD Records.
MTDYTD_Trend_Data__c.Contact__c  
MTDYTD_Trend_Data__c.Host_Brisbane__c
MTDYTD_Trend_Data__c.Host_GC__c
MTDYTD_Trend_Data__c.Host_International__c
MTDYTD_Trend_Data__c.Host_Sydney
FROM 
Contact.Contact__c  
Contact.Host_Brisbane__c
Contact.Host_GC__c
Contact.Host_International__c
Contact.Host_Sydney
*/
public class Update_MTDY_ContactHostTriggerHandler {
    
    public static void updatContactHostMapping(List<MTDYTD_Trend_Data__c>MTDYListNew)
    {
        
        Set<String> patronId = new Set<String>();
        Map<String, Contact> contactPatronMap = new Map<String, Contact>();
        
        for(MTDYTD_Trend_Data__c mt : MTDYListNew)
        {
            if(mt.Patron_ID__c !=null)
            {
                patronId.add(mt.Patron_ID__c);
            }
        }
         for(Contact c : [Select Id,Patron_ID__c,Host_Brisbane__c, Host_International__c,Host_GC__c,Host_Sydney__c 
                         From Contact 
                         Where Patron_ID__c in: patronId])
        {
            system.debug('CONTACTS : ----> ' +c);
            contactPatronMap.put(c.Patron_ID__c,c);
        }
        
        for(MTDYTD_Trend_Data__c mtdy :MTDYListNew )
        {
            if(mtdy.Patron_ID__c != Null)
            {
                if(contactPatronMap.containsKey(mtdy.Patron_ID__c))
                {
                    Contact con = contactPatronMap.get(mtdy.Patron_ID__c);
                    
                    System.debug('CONTACT INSIDE LOOP : -------------------> '+con);
                    if(con != Null)
                    {
                        mtdy.Contact__c 			= con.id;
                        mtdy.Host_Brisbane__c 		= con.Host_Brisbane__c ;
                        mtdy.Host_GC__c         	= con.Host_GC__c ;
                        mtdy.Host_International__c	= con.Host_International__c;
                        mtdy.Host_Sydney__c   		= con.Host_Sydney__c;
                        System.debug('MTDYTD CONTACT -------> '+ mtdy.Contact__c);
                    }
                }
            }
        }
        System.debug('1. Number of Queries used in this Apex code so far: ' + Limits.getQueries());
        System.debug('2. Number of rows queried in this Apex code so far: ' + Limits.getDmlRows());
        System.debug('3. Number of DML statements used so far: ' +  Limits.getDmlStatements());   
        System.debug('4. Amount of CPU time (in ms) used so far: ' + Limits.getCpuTime());
        system.debug('Contact PATRON ID MAP --------> '+contactPatronMap);
        System.debug('Patron ID SET : ---> '+patronId);
     }    
}