force-app/main/default/objects/Contact/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loyalty Program</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Source_of_Wealth__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Wealth__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Source of Wealth for Business</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/currentTierImage__c.field-meta.xml
<CustomField>
    <fullName>currentTierImage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>currentTierImage</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Last_Successful_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Successful Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Next_Tier__c.field-meta.xml
<CustomField>
    <fullName>Next_Tier__c</fullName>
    <description>To store next tier name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Tier</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/NextTierImage__c.field-meta.xml
<CustomField>
    <fullName>NextTierImage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NextTierImage</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_To_Next_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_To_Next_Tier__c</fullName>
    <label>Points To Next Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_to_Retain_Current_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_to_Retain_Current_Tier__c</fullName>
    <label>Points to Retain Current Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Review_CountdownImage__c.field-meta.xml
<CustomField>
    <fullName>Review_CountdownImage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Review Countdown Image</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Review_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Program__c/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Source_of_Wealth__c/Source_of_Wealth__c.object-meta.xml
<CustomObject>
    <label>Source of Wealth</label>
    <nameField>
        <displayFormat>SOW-{0}</displayFormat>
        <label>Source of Wealth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source of Wealth</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CompRoomNightDataProviderTest.cls
@isTest
public class CompRoomNightDataProviderTest implements HttpCalloutMock {
    
	public HTTPResponse respond(HTTPRequest request){

        CompRoomNightDataProvider.JsonData jsonData = new CompRoomNightDataProvider.JsonData();
        CompRoomNightDataProvider.JsonResponseHeader jsonHeader = new CompRoomNightDataProvider.JsonResponseHeader();
        CompRoomNightDataProvider.JsonResponse jsonResponse = new CompRoomNightDataProvider.JsonResponse();
        List<CompRoomNightDataProvider.JsonMonthlyBalances> jsonMonthlyBalancesList = new List<CompRoomNightDataProvider.JsonMonthlyBalances>();
     
        CompRoomNightDataProvider.JsonMonthlyBalances jsonMonthlyBalances06 = new CompRoomNightDataProvider.JsonMonthlyBalances();
        jsonMonthlyBalances06.month = '06';
        jsonMonthlyBalances06.year = '2022';
        jsonMonthlyBalances06.used = '0';
        jsonMonthlyBalances06.remaining = '0';
        jsonMonthlyBalancesList.add(jsonMonthlyBalances06);

        jsonResponse.monthlyBalances = jsonMonthlyBalancesList;
        jsonResponse.balance = '106';
        jsonResponse.entitlement ='';
        
        jsonHeader.code = '0';
        jsonHeader.msg = 'Success';

		jsonData.responseHeader =   jsonHeader;     
        jsonData.response =   jsonResponse;
        
        //req.requestBody = Blob.valueOf(JSON.serialize(jsonData));   
        
        //Set Mock up  data that will be received on callout during testing 
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type','application/json');
        response.setBody(JSON.serialize(jsonData));
		response.setStatusCode(200);
        response.setStatus('OK');
        
        
        return response;
    }
    @TestSetup
    static void setupData(){
        Contact conRec = new Contact();
        conRec.FirstName = 'John';
        conRec.LastName = 'Smith';
        conRec.email='test@gmail.com';
        conRec.Patron_ID__c ='1001';
        conRec.Source_of_Wealth__c='Test';
        insert conRec;

        Loyalty_Program__c prog = new Loyalty_Program__c(Name='Gold Membership');
        insert prog;

        Loyalty__c loyaltyObj = new Loyalty__c();

        loyaltyObj.Points_to_Retain_Current_Tier__c = 90;
        loyaltyObj.Tier_Review_Date__c = System.Today() +30;
        loyaltyObj.Points_To_Next_Tier__c = 800;

        loyaltyObj.Patron__c = conRec.Id;
        loyaltyObj.Tier__c = 'Silver';
        loyaltyObj.Next_Tier__c= 'Gold';
        loyaltyObj.Next_Tier__c= 'Gold';
        loyaltyObj.Loyalty_Program__c= prog.Id;
        loyaltyObj.Last_Successful_Update__c= '2022-05-25T02:04:28.557+0';


        loyaltyObj.currentTierImage__c = 'Silver.png';
        loyaltyObj.NextTierImage__c = 'Gold.png';
        loyaltyObj.Review_CountdownImage__c = 'silverGoldCountDown.png';

        insert loyaltyObj;
    }
	@isTest
    static void runCallOutTest(){
        Contact conRec = [SELECT Id, Name FROM Contact WHERE Patron_ID__c = '1001'  LIMIT 1];
        Loyalty__c loyaltyObj = [SELECT Id, Name, Patron__r.Patron_ID__c, Last_Successful_Update__c FROM Loyalty__c WHERE Patron__c =:conRec.Id LIMIT 1];
        
        Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CompRoomNightDataProviderTest());
        CompRoomNightDataProvider.runCallOut(loyaltyObj.Id);
       
        system.assertEquals(conRec.Id, loyaltyObj.Patron__c, 'Error in Patron');
        Test.stopTest();

    }
    @isTest
    static void runCallOutTestSalesConsole(){
        Contact conRec = [SELECT Id, Name FROM Contact WHERE Patron_ID__c = '1001'  LIMIT 1];
        Loyalty__c loyaltyObj = [SELECT Id, Name, Patron__r.Patron_ID__c, Last_Successful_Update__c FROM Loyalty__c WHERE Patron__c =:conRec.Id LIMIT 1];
        
        Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CompRoomNightDataProviderTest());
        CompRoomNightDataProvider.runCallOutSalesConsole(conRec.Id);
       
        system.assertEquals(conRec.Id, loyaltyObj.Patron__c, 'Error in Patron');
        Test.stopTest();

    }
    @isTest
    static void loyaltyTest(){
        Contact conRec = [SELECT Id, Name FROM Contact WHERE Patron_ID__c = '1001'  LIMIT 1];
        Loyalty__c loyaltyObj = [SELECT Id, Name, Patron__r.Patron_ID__c, Last_Successful_Update__c FROM Loyalty__c WHERE Patron__c =:conRec.Id LIMIT 1];
        
        Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CompRoomNightDataProviderTest());
       CompRoomNightDataProvider.getLoyaltyRec(loyaltyObj.Id);
        system.assertEquals('2022-05-25T02:04:28.557+0', loyaltyObj.Last_Successful_Update__c, 'Error in Last Successful update');
        Test.stopTest();

    }
}