force-app/main/default/objects/Contact/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loyalty Program</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Month__c</fullName>
    <label>Tier Points Earned This Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Week__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Week__c</fullName>
    <label>Tier Points Earned This Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_Today__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_Today__c</fullName>
    <label>Tier Points Earned Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/LoyaltyDay__c/LoyaltyDay__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is use for testing Loyalty Batch Class</description>
    <label>Loyalty Day</label>
</CustomObject>

force-app/main/default/objects/LoyaltyDay__c/fields/Add_Day__c.field-meta.xml
<CustomField>
    <fullName>Add_Day__c</fullName>
    <description>Add or subtract days that is to be use in the Loyalty Batch class testing</description>
    <label>Add Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyBatchJobTest.cls
@isTest
    public class LoyaltyBatchJobTest {
    
    @testSetup static void TestDataSetup()
    {
        //Patron <- Contact
        //Loyalty Program
        //Loyalty 
        // Tier 
        List<Contact> conList = new List<Contact>();
        List<Loyalty_Program__c> lpList = new List<Loyalty_Program__c>();
       
        date dob = date.newInstance(1990, 11, 21);

         //Patron
        for(Integer x = 0 ; x<=10;x++)
            conList.add(new Contact(
                lastName = 'Patron' +x,
                firstName = 'Testing'+x,
                Date_of_Birth__c = dob
            ));
        if(conList.size()>0){insert conList;}
        
        //Loyalty Program
        //Star Gold
        //Star Club
        //Star Club Interstate
        
        for(Integer x = 0 ; x<=10;x++)
            lpList.add(new Loyalty_Program__c(
                Name = 'Star Gold' +x
            ));
        if(lpList.size()>0){insert lpList;}
        //Loyalty
        System.debug('PATRON LIST : ' +conList);
        System.debug('LOYALTY PROGRAM LIST : ' +lpList);
        
    }
    @isTest
    static void LoyaltyResetDaily()
    {
        TestDataSetup();
        Contact con = [SELECT Id,Name FROM Contact WHERE LastName = 'Patron0' Limit 1];
        Loyalty_Program__c lp = [Select Id,Name From Loyalty_Program__c Where Name = 'Star Gold0' Limit 1];
        List<Loyalty__c> loList = new List<Loyalty__c>();
        
        insert new LoyaltyDay__c(Add_Day__c = 0);

         Loyalty__c loy = new Loyalty__c();
                loy.Name ='Test Gold';
                loy.Tier_Points_Earned_Today__c = 10;
                loy.Tier_Points_Earned_This_Week__c=20;
                loy.Tier_Points_Earned_This_Month__c =300;
                loy.Tier__c = 'Gold';
                loy.Loyalty_Program__c = lp.Id;
                loy.Patron__c = con.id;
            loList.add(loy);
        insert loList;
       System.debug('LOYALTY LIST : ' +loList);
       // if(loList.size() > 0){insert loList;}
        System.debug('LOYALTY LIST -----> '+loList);
        Test.startTest();
        
        LoyaltyBatchJob abj = new LoyaltyBatchJob();
        database.executeBatch(abj, 100);
        
        abj.execute(null,loList);
        abj.Finish(null);
        Test.stopTest();
    }
    
     @isTest
    static void LoyaltyResetMonthly()
    {
        TestDataSetup();
        Contact con = [SELECT Id,Name FROM Contact WHERE LastName = 'Patron1' Limit 1];
        Loyalty_Program__c lp = [Select Id,Name From Loyalty_Program__c Where Name = 'Star Gold1' Limit 1];
        List<Loyalty__c> loList = new List<Loyalty__c>();
        
        integer day = 5;
        insert new LoyaltyDay__c(Add_Day__c = day);

         Loyalty__c loy = new Loyalty__c();
                loy.Name ='Test Gold1';
                loy.Tier_Points_Earned_Today__c = 10;
                loy.Tier_Points_Earned_This_Week__c=20;
                loy.Tier_Points_Earned_This_Month__c =300;
                loy.Tier__c = 'Gold';
                loy.Loyalty_Program__c = lp.Id;
                loy.Patron__c = con.id;
            loList.add(loy);
        
        insert loList;
       System.debug('LOYALTY LIST : ' +loList);
       // if(loList.size() > 0){insert loList;}
        System.debug('LOYALTY LIST -----> '+loList);
        Test.startTest();
        
        LoyaltyBatchJob abj = new LoyaltyBatchJob();
        database.executeBatch(abj, 100);
        
        abj.execute(null,loList);
        abj.Finish(null);
        Test.stopTest();
    }
}