force-app/main/default/objects/Contact/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loyalty Program</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Program__c/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/Sales_Comp__c.object-meta.xml
<CustomObject>
    <label>Sales Comp</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Comp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Comps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/fields/Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Additional_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Type__c</fullName>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>add</fullName>
                <label>Add</label>
            </value>
            <value>
                <fullName>deduct</fullName>
                <label>Deduct</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Comp_Type__c.field-meta.xml
<CustomField>
    <fullName>Comp_Type__c</fullName>
    <label>Comp Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SPV</fullName>
            </value>
            <value>
                <fullName>Casino Dollar</fullName>
            </value>
            <value>
                <fullName>Comp Dollar</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Soft Cost</fullName>
            </value>
            <value>
                <fullName>MPV</fullName>
                <isActive>false</isActive>
                <label>MPV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Comps</relationshipLabel>
    <relationshipName>Sales_Comps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>F&amp;B Dining</fullName>
            </value>
            <value>
                <fullName>Guest Reactivation</fullName>
            </value>
            <value>
                <fullName>Guest Service Recovery</fullName>
            </value>
            <value>
                <fullName>In-Market Activity</fullName>
            </value>
            <value>
                <fullName>Loyalty Campaign</fullName>
            </value>
            <value>
                <fullName>Loyalty Recognition</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Prizes for events and draws</fullName>
            </value>
            <value>
                <fullName>Promotions - events and draws</fullName>
            </value>
            <value>
                <fullName>Relationship maintenance</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Service Recovery</fullName>
            </value>
            <value>
                <fullName>Special Occasion</fullName>
            </value>
            <value>
                <fullName>Surprise &amp; Delights (Special Occasion)</fullName>
            </value>
            <value>
                <fullName>Surprise and Delights</fullName>
            </value>
            <value>
                <fullName>Surprise and Delights (Special Occasion)</fullName>
            </value>
            <value>
                <fullName>Welcome / On Boarding / Lapsed</fullName>
            </value>
            <value>
                <fullName>Flights</fullName>
            </value>
            <value>
                <fullName>Room Upgrades</fullName>
            </value>
            <value>
                <fullName>Dinners</fullName>
            </value>
            <value>
                <fullName>Etc.</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Rebate Program</fullName>
                <isActive>false</isActive>
                <label>Rebate Program</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SYD</fullName>
            </value>
            <value>
                <fullName>GC</fullName>
            </value>
            <value>
                <fullName>BNE</fullName>
            </value>
            <value>
                <fullName>MEL</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Statuses</relationshipLabel>
    <relationshipName>Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Patron_Id__c.field-meta.xml
<CustomField>
    <fullName>Patron_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesCompReportController.cls
public class SalesCompReportController {
    
    @AuraEnabled(cacheable=true)
    public static List<Sales_Comp__c> getSalesCompWithApprovalHistory() {
        return [SELECT Id, Name, Adjustment_Type__c, Owner.Name, Comp_Type__c, Contact__r.Tier__c, Contact__r.Loyalty_Program__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Patron_ID__c, 
                Amount__c, Status__c, Property__c, Description__c, Comments__c, Additional_Comments__c, CreatedBy.Name, CreatedDate, LastModifiedBy.Name, LastModifiedDate, 
                (SELECT Id, TargetObjectId, StepStatus, Comments, ProcessInstance.LastActor.Name, ProcessInstance.SubmittedBy.Name FROM ProcessSteps) FROM Sales_Comp__c WHERE Contact__c != null];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Sales_Comp__c> getSalesCompWithApprovalHistoryFiltered(String keyValue) {
        keyValue = '%' + keyValue + '%';
        return [SELECT Id, Name, Adjustment_Type__c, Owner.Name, Comp_Type__c, Contact__r.Tier__c, Contact__r.Loyalty_Program__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Patron_ID__c, 
                Amount__c, Status__c, Property__c, Description__c, Comments__c, Additional_Comments__c, CreatedBy.Name, CreatedDate, LastModifiedBy.Name, LastModifiedDate, 
                (SELECT Id, TargetObjectId, StepStatus, Comments, ProcessInstance.LastActor.Name, ProcessInstance.SubmittedBy.Name 
                 FROM ProcessSteps) 
                FROM Sales_Comp__c 
                Where Contact__c != null AND (Contact__r.Patron_ID__c LIKE :keyValue 
                OR Comp_Type__c LIKE :keyValue 
                OR Status__c LIKE :keyValue 
                OR Property__c LIKE :keyValue
                OR Owner.Name LIKE :keyValue)];
    }
}