force-app/main/default/objects/Contact/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loyalty Program</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Refused_to_provide_SOW__c.field-meta.xml
<CustomField>
    <fullName>Refused_to_provide_SOW__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Reminder to complete the Unusual Activity Referral form</inlineHelpText>
    <label>Refused to provide SOW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/CasinoBalance__c.field-meta.xml
<CustomField>
    <fullName>CasinoBalance__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/CompBalance__c.field-meta.xml
<CustomField>
    <fullName>CompBalance__c</fullName>
    <label>Comp $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Last_Successful_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Successful Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_To_Next_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_To_Next_Tier__c</fullName>
    <label>Points To Next Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_to_Retain_Current_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_to_Retain_Current_Tier__c</fullName>
    <label>Points to Retain Current Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Balance__c.field-meta.xml
<CustomField>
    <fullName>Tier_Balance__c</fullName>
    <label>Tier Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Month__c</fullName>
    <label>Tier Points Earned This Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_This_Week__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_This_Week__c</fullName>
    <label>Tier Points Earned This Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Points_Earned_Today__c.field-meta.xml
<CustomField>
    <fullName>Tier_Points_Earned_Today__c</fullName>
    <label>Tier Points Earned Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/LoyaltyHelperTest.cls
@isTest
public class LoyaltyHelperTest {
	@testSetup
    static void testDataFactory(){
        Contact testContact = new Contact();
        testContact.LastName = 'Class';
        testContact.Refused_to_provide_SOW__c = true;
        
        INSERT testContact;
        
        Loyalty_Program__c testLP = new Loyalty_Program__c();
        testLP.Name = 'Test Class Star';
        INSERT testLP;
        
        Loyalty__c testLoyalty = new Loyalty__c();
        testLoyalty.Name = 'Test Loyalty';
        testLoyalty.Patron__c = testContact.Id;
        testLoyalty.Loyalty_Program__c = testLP.Id;
        testLoyalty.Tier_Balance__c = 50;
        testLoyalty.Points_to_Retain_Current_Tier__c = 5;
        testLoyalty.Points_To_Next_Tier__c = 50;
        testLoyalty.Tier_Points_Earned_Today__c = 5;
        testLoyalty.Tier_Points_Earned_This_Week__c = 15;
        testLoyalty.Tier_Points_Earned_This_Month__c = 35;
        testLoyalty.CasinoBalance__c = 0;
        testLoyalty.CompBalance__c = 0;
        testLoyalty.Last_Successful_Update__c = '2022-05-25T02:04:28.557+0';
        
        INSERT testLoyalty;
    }
    
    static testMethod void testLoyaltyHelper(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];

        test.startTest();
        Loyalty__c assertLoyalty = LoyaltyHelper.getLoyaltyInfo(testContact.Id);
        test.stopTest();
        
        System.assertEquals('Test Loyalty', assertLoyalty.Name);
    }
    
    static testMethod void testLoyaltyHelperNegative(){
        Contact testContact = new Contact();
        testContact.LastName = 'Class';
        testContact.Refused_to_provide_SOW__c = true;
        
        INSERT testContact;

        test.startTest();
        try{
        	Loyalty__c assertLoyalty = LoyaltyHelper.getLoyaltyInfo(testContact.Id);
        }catch(Exception qExcp){
            System.assert(qExcp != NULL);
        }
        test.stopTest();
        
        
    }
}