force-app/main/default/objects/Contact/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loyalty Program</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/CasinoBalance__c.field-meta.xml
<CustomField>
    <fullName>CasinoBalance__c</fullName>
    <label>Casino $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/CompBalance__c.field-meta.xml
<CustomField>
    <fullName>CompBalance__c</fullName>
    <label>Comp $ Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactLookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty (ContactLookup)</relationshipLabel>
    <relationshipName>Loyalty2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/Sales_Comp__c.object-meta.xml
<CustomObject>
    <label>Sales Comp</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Comp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Comps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Comp_Type__c.field-meta.xml
<CustomField>
    <fullName>Comp_Type__c</fullName>
    <label>Comp Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SPV</fullName>
            </value>
            <value>
                <fullName>Casino Dollar</fullName>
            </value>
            <value>
                <fullName>Comp Dollar</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Soft Cost</fullName>
            </value>
            <value>
                <fullName>MPV</fullName>
                <isActive>false</isActive>
                <label>MPV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Comps</relationshipLabel>
    <relationshipName>Sales_Comps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/recordTypes/CD_CP.recordType-meta.xml
<RecordType>
    <fullName>CD_CP</fullName>
    <active>true</active>
    <label>CD/CP</label>
</RecordType>

force-app/main/default/objects/Sales_Comp__c/recordTypes/SPV_MPV.recordType-meta.xml
<RecordType>
    <fullName>SPV_MPV</fullName>
    <active>true</active>
    <label>SPV</label>
</RecordType>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Statuses</relationshipLabel>
    <relationshipName>Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesCompControllerTest.cls
/**
 * @description       : Test class for SalesCompController
 * @author            : Simplus
 * @group             : Simplus
 * @last modified on  : 22-08-2022
 * @last modified by  : Simplus
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   22-08-2022   Simplus                      Initial Version
 */
@isTest
public class SalesCompControllerTest {
    static final String SALES_COMP_RECORD_TYPE_NAME_CD_CP = 'CD_CP';
    static final String SALES_COMP_RECORD_TYPE_NAME_SPV_MPV = 'SPV_MPV';
    static final String SALES_COMP_STATUS_APPROVED = 'Approved';

    @isTest static void getLoyaltyRecordTest() {
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'testcontact@maildrop.cc'
        );
        insert testContact;
        String contactId = testContact.Id;

        Loyalty_Program__c prog = new Loyalty_Program__c(Name = 'Gold Membership');
        insert prog;

        Decimal casinoBalance = 1000;
        Decimal compBalance = 2000;
        Loyalty__c loyalty = new Loyalty__c(
            Patron__c = contactId,
            Loyalty_Program__c = prog.Id,
            CasinoBalance__c = casinoBalance,
            CompBalance__c = compBalance
        );
        insert loyalty;

        Loyalty__c loyaltyRecord = new Loyalty__c();
        Test.startTest();
            loyaltyRecord = SalesCompController.getLoyaltyRecord(contactId);
        Test.stopTest();

        System.assertEquals(casinoBalance, loyaltyRecord.CasinoBalance__c);
        System.assertEquals(compBalance, loyaltyRecord.CompBalance__c);
    }

    @isTest static void getSalesCompsTotalTest() {
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'testcontact@maildrop.cc'
        );
        insert testContact;
        String contactId = testContact.Id;

        Id cdCPrtId = Schema.SObjectType.Sales_Comp__c.getRecordTypeInfosByDeveloperName().get(SALES_COMP_RECORD_TYPE_NAME_CD_CP).getRecordTypeId();
        Id spvMPVrtId = Schema.SObjectType.Sales_Comp__c.getRecordTypeInfosByDeveloperName().get(SALES_COMP_RECORD_TYPE_NAME_SPV_MPV).getRecordTypeId();

        List<Sales_Comp__c> salesComps = new List<Sales_Comp__c>();
        Decimal cdAmount = 100;
        Sales_Comp__c scCD = new Sales_Comp__c(
            Amount__c = cdAmount,
            Comp_Type__c = 'Casino Dollar',
            Contact__c = contactId,
            RecordTypeId = cdCPrtId
        );
        salesComps.add(scCD);

        Decimal spvAmount = 200;
        Sales_Comp__c scSPV = new Sales_Comp__c(
            Amount__c = spvAmount,
            Comp_Type__c = 'SPV',
            Contact__c = contactId,
            RecordTypeId = spvMPVrtId
        );
        salesComps.add(scSPV);
        insert salesComps;

        for (Sales_Comp__c sc: salesComps) {
            sc.Status__c = SALES_COMP_STATUS_APPROVED;
        }
        update salesComps;

        SalesCompController.ContactRecordWrapper wrapper = new SalesCompController.ContactRecordWrapper();
        Test.startTest();
            wrapper = SalesCompController.getSalesCompsTotal(contactId);
        Test.stopTest();

        System.assertEquals(cdAmount, wrapper.cdCPtotal);
        System.assertEquals(spvAmount, wrapper.spvMPVtotal);
    }
}