force-app/main/default/objects/Contact/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loyalty Program</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/Loyalty__c.object-meta.xml
<CustomObject>
    <label>Loyalty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty__c/fields/currentTierImage__c.field-meta.xml
<CustomField>
    <fullName>currentTierImage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>currentTierImage</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Last_Successful_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Update__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Successful Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Loyalty_Program__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program__c</fullName>
    <label>Loyalty Program</label>
    <referenceTo>Loyalty_Program__c</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Next_Tier__c.field-meta.xml
<CustomField>
    <fullName>Next_Tier__c</fullName>
    <description>To store next tier name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Tier</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/NextTierImage__c.field-meta.xml
<CustomField>
    <fullName>NextTierImage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NextTierImage</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty</relationshipLabel>
    <relationshipName>Loyalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_To_Next_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_To_Next_Tier__c</fullName>
    <label>Points To Next Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Points_to_Retain_Current_Tier__c.field-meta.xml
<CustomField>
    <fullName>Points_to_Retain_Current_Tier__c</fullName>
    <label>Points to Retain Current Tier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Review_CountdownImage__c.field-meta.xml
<CustomField>
    <fullName>Review_CountdownImage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Review Countdown Image</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Tier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loyalty__c/fields/Tier_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Review_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loyalty_Program__c/Loyalty_Program__c.object-meta.xml
<CustomObject>
    <label>Loyalty Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loyalty Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Program</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/LoyaltyProgramUIControllerTest.cls
/**
 * @description       : 
 * @author            : sakshi.chauhan@simplus.com
 * @group             : 
 * @last modified on  : 11-05-2020
 * @last modified by  : sakshi.chauhan@simplus.com
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   10-01-2020   sakshi.chauhan@simplus.com   Initial Version
**/
@isTest
public class LoyaltyProgramUIControllerTest {

    //Positive Scenario
    @isTest
    public static void testGetLoyaltyInfo(){
        Contact patron = new Contact();
        patron.FirstName = 'John';
        patron.LastName = 'Smith';
        patron.email='test@gmail.com';
        insert patron;

        Loyalty_Program__c prog = new Loyalty_Program__c(Name='Gold Membership');
        insert prog;

        Loyalty__c loyaltyObj = new Loyalty__c();

        loyaltyObj.Points_to_Retain_Current_Tier__c = 90;
        loyaltyObj.Tier_Review_Date__c = System.Today() +30;
        loyaltyObj.Points_To_Next_Tier__c = 800;

        loyaltyObj.Patron__c = patron.Id;
        loyaltyObj.Tier__c = 'Silver';
        loyaltyObj.Next_Tier__c= 'Gold';
        loyaltyObj.Next_Tier__c= 'Gold';
        loyaltyObj.Loyalty_Program__c= prog.Id;
        loyaltyObj.Last_Successful_Update__c= '2022-05-25T02:04:28.557+0';


        loyaltyObj.currentTierImage__c = 'Silver.png';
        loyaltyObj.NextTierImage__c = 'Gold.png';
        loyaltyObj.Review_CountdownImage__c = 'silverGoldCountDown.png';

        insert loyaltyObj;

        LoyaltyProgramUIController.LoyaltyInfoWrapper  wrapObj;
        Test.startTest();
             wrapObj = LoyaltyProgramUIController.getLoyaltyInfo(patron.Id);
        Test.stopTest();

        system.assert(wrapObj.pointToMaintainCurrentTier!= null);
        system.assert(wrapObj.pointToGetToNextTier != null);
        system.assert(wrapObj.reviewCountDown!= null);

        system.assert(wrapObj.currentTierImageName!= null);
        system.assert(wrapObj.nextTierImageName!= null);
        system.assert(wrapObj.countdownImage!= null);

        system.assert(wrapObj.currentTierName!= null);
        system.assert(wrapObj.nextTierName!= null);

    }

    //Negative Scenario
    @isTest
    public static void testGetLoyaltyInfoNoDataExists(){
        Contact patron = new Contact();
        patron.FirstName = 'John';
        patron.LastName = 'Smith';
        patron.email='test@gmail.com';
        insert patron;

        LoyaltyProgramUIController.LoyaltyInfoWrapper  wrapObj;
        Test.startTest();
             wrapObj = LoyaltyProgramUIController.getLoyaltyInfo(patron.Id);
        Test.stopTest();

        system.assert(wrapObj == null);

    }
}