force-app/main/default/objects/Contact/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Occupation_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>111</fullName>
                <label>Chief Executives, General Managers and Legislators</label>
            </value>
            <value>
                <fullName>121</fullName>
                <label>Farmers and Farm Managers</label>
            </value>
            <value>
                <fullName>131</fullName>
                <label>Advertising, Public Relations and Sales Managers</label>
            </value>
            <value>
                <fullName>132</fullName>
                <label>Business Administration Managers</label>
            </value>
            <value>
                <fullName>133</fullName>
                <label>Construction, Distribution and Production Managers</label>
            </value>
            <value>
                <fullName>134</fullName>
                <label>Education, Health and Welfare Services Managers</label>
            </value>
            <value>
                <fullName>135</fullName>
                <label>ICT Managers</label>
            </value>
            <value>
                <fullName>139</fullName>
                <label>Miscellaneous Specialist Managers</label>
            </value>
            <value>
                <fullName>141</fullName>
                <label>Accommodation and Hospitality Managers</label>
            </value>
            <value>
                <fullName>142</fullName>
                <label>Retail Managers</label>
            </value>
            <value>
                <fullName>149</fullName>
                <label>Miscellaneous Hospitality, Retail and Service Managers</label>
            </value>
            <value>
                <fullName>211</fullName>
                <label>Arts Professionals</label>
            </value>
            <value>
                <fullName>212</fullName>
                <label>Media Professionals</label>
            </value>
            <value>
                <fullName>221</fullName>
                <label>Accountants, Auditors and Company Secretaries</label>
            </value>
            <value>
                <fullName>222</fullName>
                <label>Financial Brokers and Dealers, and Investment Advisers</label>
            </value>
            <value>
                <fullName>223</fullName>
                <label>Human Resource and Training Professionals</label>
            </value>
            <value>
                <fullName>224</fullName>
                <label>Information and Organisation Professionals</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>Sales, Marketing and Public Relations Professionals</label>
            </value>
            <value>
                <fullName>231</fullName>
                <label>Air and Marine Transport Professionals</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>Architects, Designers, Planners and Surveyors</label>
            </value>
            <value>
                <fullName>233</fullName>
                <label>Engineering Professionals</label>
            </value>
            <value>
                <fullName>234</fullName>
                <label>Natural and Physical Science Professionals</label>
            </value>
            <value>
                <fullName>241</fullName>
                <label>School Teachers</label>
            </value>
            <value>
                <fullName>242</fullName>
                <label>Tertiary Education Teachers</label>
            </value>
            <value>
                <fullName>249</fullName>
                <label>Miscellaneous Education Professionals</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>Health Diagnostic and Promotion Professionals</label>
            </value>
            <value>
                <fullName>252</fullName>
                <label>Health Therapy Professionals</label>
            </value>
            <value>
                <fullName>253</fullName>
                <label>Medical Practitioners</label>
            </value>
            <value>
                <fullName>254</fullName>
                <label>Midwifery and Nursing Professionals</label>
            </value>
            <value>
                <fullName>261</fullName>
                <label>Business and Systems Analysts, and Programmers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationships__c/Relationships__c.object-meta.xml
<CustomObject>
    <label>Relationships</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationships__c/fields/From_Patron__c.field-meta.xml
<CustomField>
    <fullName>From_Patron__c</fullName>
    <label>From Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related To</relationshipLabel>
    <relationshipName>RelatedTo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Relationships__c/fields/To_Patron__c.field-meta.xml
<CustomField>
    <fullName>To_Patron__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related From</relationshipLabel>
    <relationshipName>RelatedFrom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PatronProspectRelationshipTest.cls
/**
 * Class Name  : PatronProspectRelationshipTest
 * Summary     : Controller class for 'PatronProspectRelationshipTest' aura component 
 * Methods     : testGetRelationships
                 testIsDeletableObject
                 testIsUpdateableObject
                 testGetRecordTypes
                 testDeleteRelationship
 * @author       Fritz Gerald Moran
   @Description: This class tests the list of active relationships, checks the user access permissions for the object,
                 gets the record types, and deletes relationship
 * @version      $Revision: 1.0 $, $Date: 25/Jul/2020 
 */

/*parent class that holds the methods for testing the apex controller of PatronProspectRelationshipController*/
@isTest
public class PatronProspectRelationshipTest {
    
    /*testing fetch relationships with and without limit*/
    @isTest static void testGetRelationships() {
        List<Relationships__c> relationshipsList;
        List<Relationships__c> relationshipsListWithLimit;
        
        Contact conRecParent = new Contact();
        conRecParent.LastName = 'Parent Patron';
        //conRecParent.Occupation__c = 'Parent Patron';
        conRecParent.Email = 'star@yopmail.com';
        conRecParent.HomePhone='+61439217734';
        conRecParent.OtherPhone='+61488886666';
        conRecParent.MobilePhone='+86130888866665555';
        
        insert conRecParent;
        
        Contact conRecChild = new Contact();
        conRecChild.LastName = 'Child Patron';
        //conRecChild.Occupation__c = 'Child Patron';
        conRecChild.Email = 'starchild@yopmail.com';
        conRecChild.HomePhone='+61439217734';
        conRecChild.OtherPhone='+61488886666';
        conRecChild.MobilePhone='+86130888866665555';
        
        insert conRecChild;
        
        Relationships__c relRec = new Relationships__c();
        relRec.Name = 'Relationship Name';
        relRec.From_Patron__c = conRecParent.Id;
        relRec.To_Patron__c = conRecChild.Id;
        relRec.Active__c = TRUE;
        
        insert relRec;
        
        Test.startTest();
        try {
            relationshipsList = PatronProspectRelationshipController.getRelationships(conRecParent.Id, TRUE);
            relationshipsListWithLimit = PatronProspectRelationshipController.getRelationships(conRecParent.Id, FALSE);
        } catch(Exception ex) {
            system.debug(ex.getMessage());  
        }
        Test.stopTest();
        
        system.assert(!relationshipsList.isEmpty());
        system.assert(!relationshipsListWithLimit.isEmpty());
    }
    
    /*test user permissions if is has a delete access on the record*/
    @isTest static void testIsDeletableObject() {
        String sObjectName = 'Relationships__c';
        Boolean isDeletable;
        Test.startTest();
        try {
            isDeletable = PatronProspectRelationshipController.isDeletableObject(sObjectName);
        } catch(Exception ex) {
            system.debug(ex.getMessage()); 
        }
        Test.stopTest();
        
        system.assert(isDeletable);
    }

    /*test user permissions if is has a create access on the record*/
    @isTest static void testIsCreateableObject() {
        String sObjectName = 'Relationships__c';
        Boolean isCreateable;
        Test.startTest();
        try {
            isCreateable = PatronProspectRelationshipController.isCreatable(sObjectName);
        } catch(Exception ex) {
            system.debug(ex.getMessage()); 
        }
        Test.stopTest();
        
        system.assert(isCreateable);
    }    
    
    /*test user permissions if is has a update access on the record*/
    @isTest static void testIsUpdateableObject() {
        String sObjectName = 'Relationships__c';
        Boolean isUpdatable;
        Test.startTest();
        try {
            isUpdatable = PatronProspectRelationshipController.isUpdateableObject(sObjectName);
        } catch(Exception ex) {
            system.debug(ex.getMessage()); 
        }
        Test.stopTest();
        
        system.assert(isUpdatable);
    }
    
    
    /*test fetching of record types*/
    @isTest static void testGetRecordTypes() {
        PatronProspectRelationshipController obj;
        Test.startTest();
        try {
            obj = PatronProspectRelationshipController.getRecordTypes();
        } catch(Exception ex) {
            system.debug(ex.getMessage()); 
        }
        Test.stopTest();
        
        system.assert(obj != NULL);
    }
     
    
    /*test for deleting a relationship record by Id*/
    @isTest static void testDeleteRelationship() {
        Contact conRecParent = new Contact();
        conRecParent.LastName = 'Parent Patron';
        //conRecParent.Occupation__c = 'Parent Patron';
        conRecParent.Email = 'star@yopmail.com';
        conRecParent.HomePhone='+61439217734';
        conRecParent.OtherPhone='+61488886666';
        conRecParent.MobilePhone='+86130888866665555';
        
        insert conRecParent;
        
        Contact conRecChild = new Contact();
        conRecChild.LastName = 'Child Patron';
        //conRecChild.Occupation__c = 'Child Patron';
        conRecChild.Email = 'starchild@yopmail.com';
        conRecChild.HomePhone='+61439217734';
        conRecChild.OtherPhone='+61488886666';
        conRecChild.MobilePhone='+86130888866665555';
        
        insert conRecChild;
        
        Relationships__c relRec = new Relationships__c();
        relRec.Name = 'Relationship Name';
        relRec.From_Patron__c = conRecParent.Id;
        relRec.To_Patron__c = conRecChild.Id;
        relRec.Active__c = TRUE;
        
        insert relRec;
        
        Test.startTest();
        try {
            PatronProspectRelationshipController.deleteRelationship(relRec.Id);
        } catch(Exception ex) {
            system.debug(ex.getMessage()); 
        }
        Test.stopTest();
        
        system.debug(relRec == NULL);
    }
}