force-app/main/default/objects/Contact/fields/Overlapping_Days__c.field-meta.xml
<CustomField>
    <fullName>Overlapping_Days__c</fullName>
    <label>Overlapping Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Residency_Checklist__c/Residency_Checklist__c.object-meta.xml
<CustomObject>
    <label>Residency Checklist</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Residency Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residency Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Residency_Checklist__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Manually Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Residency_Checklist__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Days in NSW/QLD or AUS</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Residency Checklists</relationshipLabel>
    <relationshipName>Residency_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Days in NSW/QLD or AUS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days in NSW/QLD or AUS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Days in NSW/QLD or AUS</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_State__c.field-meta.xml
<CustomField>
    <fullName>Entry_State__c</fullName>
    <label>Entry State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>Exit_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/is_within_365_days__c.field-meta.xml
<CustomField>
    <fullName>is_within_365_days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is within 365 days?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TripServiceTest.cls
@isTest
public class TripServiceTest {
    @testSetup
    static void testDataFactory(){
        Contact testContact = TestDataFactory.createSingleContact('TestClass');
        TestDataFactory.createUser('TSEG CRM Manager', 'Management');
    }
    
    static testmethod void countTripDurationInsertTest(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Date dateToday = System.today();
        List<Trip__c> tripList = new List<Trip__c>();
        
        test.startTest();
        
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        tripList.add(firstTrip);
        
        Trip__c secondTrip = new Trip__c();
        secondTrip.Contact__c = testContact.Id;
        secondTrip.Entry_State__c = 'QLD';
        secondTrip.Entry_Date__c = firstTrip.Exit_Date__c;
        secondTrip.Exit_Date__c = secondTrip.Entry_Date__c.addDays(14);
        secondTrip.Cancelled__c = FALSE;
        secondTrip.is_within_365_days__c = TRUE;
        
        tripList.add(secondTrip);
        
        INSERT tripList;
        
        test.stopTest();
        System.assertEquals(secondTrip.Entry_Date__c, firstTrip.Exit_Date__c);
        Contact assertContact = [SELECT Id, Overlapping_Days__c FROM Contact WHERE Id =: testContact.Id];
        System.assertEquals(assertContact.Id, testContact.Id);
        System.assertEquals(assertContact.Overlapping_Days__c, 1);
    }
    
    static testmethod void countTripDurationUpdateTest(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        User testUser = [SELECT Id FROM User WHERE Email = 'testUser@starTest.com' LIMIT 1];
        Date dateToday = System.today();
        List<Trip__c> tripList = new List<Trip__c>();
        
        testContact.OwnerId = testUser.Id;
        update testContact; 
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        tripList.add(firstTrip);
        
        Trip__c secondTrip = new Trip__c();
        secondTrip.Contact__c = testContact.Id;
        secondTrip.Entry_State__c = 'QLD';
        secondTrip.Entry_Date__c = dateToday;
        secondTrip.Exit_Date__c = secondTrip.Entry_Date__c.addDays(14);
        secondTrip.Cancelled__c = FALSE;
        secondTrip.is_within_365_days__c = TRUE;
        
        tripList.add(secondTrip);
        
        INSERT tripList;
        
        Trip__c updateTrip = [SELECT Id, Entry_Date__c FROM Trip__c WHERE Id =: secondTrip.Id];
        
        test.startTest();
            System.runAs(testUser){
                updateTrip.Entry_Date__c = firstTrip.Exit_Date__c;
                UPDATE updateTrip;
            }
        test.stopTest();
        
        System.assertEquals(updateTrip.Entry_Date__c, firstTrip.Exit_Date__c);
        Contact assertContact = [SELECT Id, Overlapping_Days__c FROM Contact WHERE Id =: testContact.Id];
        System.assertEquals(assertContact.Id, testContact.Id);
        System.assertEquals(assertContact.Overlapping_Days__c, 1);
    }
    
    static testmethod void validateDuplicateTripRecord(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Date dateToday = System.today();
        
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        INSERT firstTrip;
        
        test.startTest();
        
        try{ 
            Trip__c secondTrip = new Trip__c();
            secondTrip.Contact__c = testContact.Id;
            secondTrip.Entry_State__c = 'NSW';
            secondTrip.Entry_Date__c = dateToday;
            secondTrip.Exit_Date__c = secondTrip.Entry_Date__c.addDays(14);
            secondTrip.Cancelled__c = FALSE;
            secondTrip.is_within_365_days__c = TRUE;
            
            INSERT secondTrip;    
        }catch(Exception e){
            System.assert(e.getMessage().contains('Duplicate or overlap trip with the same entry state and entry date'));
        }

        test.stopTest();
    }
    
    static testmethod void validateDuplicateTripRecordUpdate(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Date dateToday = System.today();
        
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        INSERT firstTrip;
        
        Trip__c secondTrip = new Trip__c();
        secondTrip.Contact__c = testContact.Id;
        secondTrip.Entry_State__c = 'QLD';
        secondTrip.Entry_Date__c = dateToday;
        secondTrip.Exit_Date__c = secondTrip.Entry_Date__c.addDays(14);
        secondTrip.Cancelled__c = FALSE;
        secondTrip.is_within_365_days__c = TRUE;
        
        INSERT secondTrip;   
        
        test.startTest();
        
        try{ 
            Trip__c dupeTrip = [SELECT Id, Entry_State__c FROM Trip__c WHERE Entry_State__c = 'QLD' AND Contact__c =: testContact.Id];
            dupeTrip.Entry_State__c = 'NSW';
            UPDATE dupeTrip;
        }catch(Exception e){
            System.assert(e.getMessage().contains('Duplicate or overlap trip with the same entry state and entry date'));
        }

        test.stopTest();
    }
    
    static testmethod void tripCancellationValidation(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        
        Date dateToday = System.today();
        
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        INSERT firstTrip;
        
        Residency_Checklist__c testRC = new Residency_Checklist__c();
        testRC.Trip__c = firstTrip.Id;
        testRC.Approval_Status__c = 'Rejected';
        
        INSERT testRC;
        
        test.startTest();
        Trip__c testTrip = [SELECT Id, Cancelled__c FROM Trip__c WHERE Entry_State__c = 'NSW' AND Contact__c =: testContact.Id];
        testTrip.Cancelled__c = TRUE;
        
        UPDATE testTrip;
        System.assert(testTrip.Cancelled__c);
        test.stopTest();
    }
    
    static testmethod void countTripDurationDeleteTest(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        User testUser = [SELECT Id FROM User WHERE Email = 'testUser@starTest.com' LIMIT 1];
        Date dateToday = System.today();
        List<Trip__c> tripList = new List<Trip__c>();
        
        testContact.OwnerId = testUser.Id;
        update testContact; 
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        tripList.add(firstTrip);
        
        Trip__c secondTrip = new Trip__c();
        secondTrip.Contact__c = testContact.Id;
        secondTrip.Entry_State__c = 'QLD';
        secondTrip.Entry_Date__c = dateToday;
        secondTrip.Exit_Date__c = dateToday.addDays(7);
        secondTrip.Cancelled__c = FALSE;
        secondTrip.is_within_365_days__c = TRUE;
        
        tripList.add(secondTrip);
        
        INSERT tripList;
        
        test.startTest();
            System.runAs(testUser){
                DELETE secondTrip;
            }
        test.stopTest();
        
        Contact assertContact = [SELECT Id, Overlapping_Days__c FROM Contact WHERE Id =: testContact.Id];
        System.assertEquals(assertContact.Id, testContact.Id);
        System.assertEquals(assertContact.Overlapping_Days__c, 0);
    }
}