force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PoP__c/PoP__c.object-meta.xml
<CustomObject>
    <label>PoP</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PoP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PoP</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PoP__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PoP</relationshipLabel>
    <relationshipName>PoP</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PoP__c/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PoP__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Pending Application(ready to be pickup by Azure logic app)

Pending Revocation(ready to be pickup by Azure logic app)

Application Successful(PoP status is applied for the user)

Revocation Successful(PoP status is revoked for the user)

Error</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Application</fullName>
            </value>
            <value>
                <fullName>Pending Revocation</fullName>
            </value>
            <value>
                <fullName>Application Successful</fullName>
            </value>
            <value>
                <fullName>Revocation Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PoP__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PingOne Action</fullName>
            </value>
            <value>
                <fullName>Private Gaming Room Access Revoke</fullName>
            </value>
            <value>
                <fullName>Stop Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PoP__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Statuses</relationshipLabel>
    <relationshipName>Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Patron_Id__c.field-meta.xml
<CustomField>
    <fullName>Patron_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POPSelector.cls
public With Sharing class POPSelector {
    // Define the fields to be queried
    private static final List<String> FIELDS = new List<String>{
        'Id',
            'Name',
            'Patron_ID__c',
            'Contact__c',
            'Type__c',
            'Value__c',
            'Status__c'
            };
                
                // Method to build the SOQL query string
                private static String buildQueryString(String objectAPI, String whereClause) {
                    return 'SELECT ' + String.join(FIELDS, ', ') + ' FROM ' + objectAPI + ' WHERE ' + whereClause + ' ORDER BY CreatedDate DESC ';
                }
    
    // Method to select records by a set of IDs
    public static List<PoP__c> getPoPById(Set<ID> idSet) {
        if (idSet.isEmpty()) return new List<PoP__c>();
        
        String whereClause = 'Id IN :idSet';
        return executeQuery('PoP__c', whereClause, null);
    }

    // Method to select records by a set of contact IDs
    public static List<PoP__c> getPoPByContactId(Set<ID> idSet) {
        if (idSet.isEmpty()) return new List<PoP__c>();
        
        String whereClause = 'Contact__c IN :patronSFIdSet';
        return executeQuery('PoP__c', whereClause, idSet);
    }    
    
    // Method to select records by a custom where clause
    public static List<PoP__c> getPoPByCustomClause(String clauseStr) {
        if (String.isBlank(clauseStr)) return new List<PoP__c>();
        
        return executeQuery('PoP__c', clauseStr, null);
    }
    
    // Method to get records using status, type, and stop code
    public static List<PoP__c> getPoPUsingStatusTypeCode(Set<Id> patronSFIdSet, String statusStr, String typeStr, String stopCodeStr) {
        if (patronSFIdSet.isEmpty()) return new List<PoP__c>();
        system.debug('patronSFIdSet:: '+patronSFIdSet);
        String whereClause = 'Contact__c IN: patronSFIdSet ';
        // If statusStr contains multiple values, add an OR condition
        if (statusStr != null && !string.isBlank(statusStr)) {
            // Check if there are multiple values separated by commas
            List<String> statusList = statusStr.split(', ');
            if (statusList.size() > 1) {
                whereClause += ' AND (' + buildWhereClauseWithOR('Status__c', statusList) + ')';
            } else {
                // If there's just one value, use the buildWhereClause method
                whereClause += buildWhereClause('Status__c', statusStr);
            }
        }
        whereClause += buildWhereClause('Type__c', typeStr);
        whereClause += buildWhereClause('Value__c', stopCodeStr);
        return executeQuery('PoP__c', whereClause, patronSFIdSet);
    }
    
    // Helper method to construct WHERE clauses
    private static String buildWhereClause(String field, String value) {
        return value != null && !string.isBlank(value) ? ' AND ' + field + ' = \'' + String.escapeSingleQuotes(value) + '\'' : '';
    }
    
    // Helper method to build OR condition for multiple status values
    private static String buildWhereClauseWithOR(String field, List<String> values) {
        String condition = '';
        for (String value : values) {
            if (!string.isBlank(condition)) {
                condition += ' OR ';
            }
            condition += field + ' = \'' + String.escapeSingleQuotes(value.trim()) + '\'';
        }
        return condition;
    }
    
    // Method to execute the query
    private static List<PoP__c> executeQuery(String objectAPI, String whereClause, Set<Id> patronSFIdSet) {
        String queryString = buildQueryString(objectAPI, whereClause);
        system.debug('Final Query '+queryString);
        return Database.query(queryString);
    }
    
}