force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/Exl_Exclusion__c.object-meta.xml
<CustomObject>
    <description>This object serves as the authoritative source for all patron-related restrictions and exclusions.</description>
    <label>Exclusion</label>
    <nameField>
        <displayFormat>1{00000}</displayFormat>
        <label>Exclusion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related patron</description>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/POE_Type__c.field-meta.xml
<CustomField>
    <fullName>POE_Type__c</fullName>
    <description>Type of exclusion</description>
    <label>POE Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External Exclusion - Group Wide</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - Group Wide</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - NSW</fullName>
            </value>
            <value>
                <fullName>Problem Gambling - QLD</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - Group Wide</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - NSW</fullName>
            </value>
            <value>
                <fullName>Self Exclusion - QLD</fullName>
            </value>
            <value>
                <fullName>TP24HR</fullName>
            </value>
            <value>
                <fullName>TP7DAY</fullName>
            </value>
            <value>
                <fullName>Venue - Group Wide</fullName>
            </value>
            <value>
                <fullName>WOL - Property - Group Wide</fullName>
            </value>
            <value>
                <fullName>Interstate - CCA</fullName>
            </value>
            <value>
                <fullName>Interstate – CCA</fullName>
                <isActive>false</isActive>
                <label>Interstate – CCA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Exclusion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of exclusion restriction</description>
    <label>Restriction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Exclusion Draft</fullName>
            </value>
            <value>
                <fullName>Revocation Draft</fullName>
            </value>
            <value>
                <fullName>Activation Failed</fullName>
            </value>
            <value>
                <fullName>Revocation Failed</fullName>
            </value>
            <value>
                <fullName>Exclusion Pending</fullName>
            </value>
            <value>
                <fullName>Revocation Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exl_Restriction__c/Exl_Restriction__c.object-meta.xml
<CustomObject>
    <label>Restriction</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Restriction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restrictions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exl_Restriction__c/fields/Patron__c.field-meta.xml
<CustomField>
    <fullName>Patron__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Restrictions</relationshipLabel>
    <relationshipName>Restrictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Statuses</relationshipLabel>
    <relationshipName>Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Patron_Id__c.field-meta.xml
<CustomField>
    <fullName>Patron_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Exl_RestrictionCreation_Test.cls
@isTest
private class Exl_RestrictionCreation_Test {

    // Utility: create a Contact and return Id
    private static Id createContact() {
        Contact c = new Contact(LastName = 'Test Contact', Patron_ID__c = '4565608');
        insert c;
        return c.Id;
    }    
    
    @IsTest
    static void testInsertExclusion() {
        Id conId = createContact();
        Exl_Exclusion__c ex = new Exl_Exclusion__c(
            Contact__c = conId,
            POE_Type__c = 'Interstate - CCA',
            Status__c = 'Exclusion Pending'
        );
        Test.startTest();
        insert ex;
        //insert another Exclusion
        Exl_Exclusion__c ex1 = new Exl_Exclusion__c(
            Contact__c = conId,
            POE_Type__c = 'Interstate - CCA',
            Status__c = 'Exclusion Pending'
        );        
        insert ex1;
        Test.stopTest();
        // assert
        List<Exl_Restriction__c> res = new List<Exl_Restriction__c>([SELECT Id FROM Exl_Restriction__c WHERE Patron__c = :conId]);
		System.assert(res != null, 'Restriction records are created');
        
    }
    
    @IsTest
    static void testInsertExclusion_blankPOE() {
        Id conId = createContact();
        Exl_Exclusion__c ex = new Exl_Exclusion__c(
            Contact__c = conId,
            POE_Type__c = '',
            Status__c = 'Exclusion Pending'
        );
        Test.startTest();
        insert ex;
        Test.stopTest();
        // assert
        List<Exl_Restriction__c> res = new List<Exl_Restriction__c>([SELECT Id FROM Exl_Restriction__c WHERE Patron__c = :conId]);
		System.assert(res != null, 'Restriction records are created');
    }
}