force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/Sales_Comp__c.object-meta.xml
<CustomObject>
    <label>Sales Comp</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Sales Comp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Comps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Comp__c/fields/Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Type__c</fullName>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>add</fullName>
                <label>Add</label>
            </value>
            <value>
                <fullName>deduct</fullName>
                <label>Deduct</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Comp_Type__c.field-meta.xml
<CustomField>
    <fullName>Comp_Type__c</fullName>
    <label>Comp Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SPV</fullName>
            </value>
            <value>
                <fullName>Casino Dollar</fullName>
            </value>
            <value>
                <fullName>Comp Dollar</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Soft Cost</fullName>
            </value>
            <value>
                <fullName>MPV</fullName>
                <isActive>false</isActive>
                <label>MPV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Comps</relationshipLabel>
    <relationshipName>Sales_Comps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>F&amp;B Dining</fullName>
            </value>
            <value>
                <fullName>Guest Reactivation</fullName>
            </value>
            <value>
                <fullName>Guest Service Recovery</fullName>
            </value>
            <value>
                <fullName>In-Market Activity</fullName>
            </value>
            <value>
                <fullName>Loyalty Campaign</fullName>
            </value>
            <value>
                <fullName>Loyalty Recognition</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Prizes for events and draws</fullName>
            </value>
            <value>
                <fullName>Promotions - events and draws</fullName>
            </value>
            <value>
                <fullName>Relationship maintenance</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Service Recovery</fullName>
            </value>
            <value>
                <fullName>Special Occasion</fullName>
            </value>
            <value>
                <fullName>Surprise &amp; Delights (Special Occasion)</fullName>
            </value>
            <value>
                <fullName>Surprise and Delights</fullName>
            </value>
            <value>
                <fullName>Surprise and Delights (Special Occasion)</fullName>
            </value>
            <value>
                <fullName>Welcome / On Boarding / Lapsed</fullName>
            </value>
            <value>
                <fullName>Flights</fullName>
            </value>
            <value>
                <fullName>Room Upgrades</fullName>
            </value>
            <value>
                <fullName>Dinners</fullName>
            </value>
            <value>
                <fullName>Etc.</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Rebate Program</fullName>
                <isActive>false</isActive>
                <label>Rebate Program</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/isForVoid__c.field-meta.xml
<CustomField>
    <fullName>isForVoid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isForVoid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Justification__c.field-meta.xml
<CustomField>
    <fullName>Justification__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Justification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SYD</fullName>
            </value>
            <value>
                <fullName>GC</fullName>
            </value>
            <value>
                <fullName>BNE</fullName>
            </value>
            <value>
                <fullName>MEL</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales - Currency Load</fullName>
            </value>
            <value>
                <fullName>Sales – Currency Load Reversal</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Comp__c/recordTypes/CD_CP.recordType-meta.xml
<RecordType>
    <fullName>CD_CP</fullName>
    <active>true</active>
    <label>CD/CP</label>
</RecordType>

force-app/main/default/objects/Sales_Comp__c/recordTypes/Gift.recordType-meta.xml
<RecordType>
    <fullName>Gift</fullName>
    <active>true</active>
    <label>Gift</label>
</RecordType>

force-app/main/default/objects/Sales_Comp__c/recordTypes/SPV_MPV.recordType-meta.xml
<RecordType>
    <fullName>SPV_MPV</fullName>
    <active>true</active>
    <label>SPV</label>
</RecordType>

force-app/main/default/objects/Sales_Comp_Setting__mdt/Sales_Comp_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Sales Comp Setting</label>
    <pluralLabel>Sales Comp Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sales_Comp_Setting__mdt/fields/Sales_Comp_Sub_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Comp_Sub_Key__c</fullName>
    <label>Sales Comp Sub Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Comp_Setting__mdt/fields/Sales_Comp_URL__c.field-meta.xml
<CustomField>
    <fullName>Sales_Comp_URL__c</fullName>
    <label>Sales Comp URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <label>Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Statuses</relationshipLabel>
    <relationshipName>Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Status__c/fields/Patron_Id__c.field-meta.xml
<CustomField>
    <fullName>Patron_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <formula>Contact.Patron_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patron ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesCompTriggerHandler.cls
/**
 * @description       : Trigger handler class for SalesCompTrigger
 * @author            : Simplus
 * @group             : Simplus
 * @last modified on  : 22-08-2022
 * @last modified by  : Simplus
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   22-08-2022   Simplus                      Initial Version
 */
public class SalesCompTriggerHandler
extends TriggerHandlerBase //extending the trigger framework
{
    static final String APEXCLASSNAME = 'SalesCompTriggerHandler';
    static final String COMPONENTTYPE = 'Apex Class';
    static final String SALES_COMP_RECORD_TYPE_NAME_CD_CP = 'CD_CP';
    static final String SALES_COMP_RECORD_TYPE_NAME_SPV_MPV = 'SPV_MPV';
    static final String SALES_COMP_RECORD_TYPE_NAME_GIFT = 'GIFT';
    static final String SALES_COMP_STATUS_APPROVED = 'Approved';
    static final String SALES_COMP_STATUS_DECLINED = 'Declined';
    static final String SALES_COMP_STATUS_VOIDED = 'Voided';
    static final String SALES_COMP_STATUS_INVALID = 'Invalid';
    static final String SALES_COMP_STATUS_PENDING = 'Pending';
    static final String INITIAL_APPROVAL_PROCESS = 'Sales_Comp_Approval_Process_1';
    static final String FINAL_APPROVAL_PROCESS = 'Sales_Comp_Approval_Process_2';
    static final String FINAL_APPROVER = 'Paul Monaghan';

    static Map<Id, RecordType> salesCompRecTypeMap = new Map<Id, RecordType>([SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Sales_Comp__c']);

    //new method which is required when we extend the TriggerHandlerBase class
    public SalesCompTriggerHandler(String triggerName) {
    	super(triggerName);
    }    
    
    //codes below are commented to follow trigger framework requirement. see replacement code in next blocks
    /*
    public static void beforeInsert(List<Sales_Comp__c> newSalesComp){
        updateSCFields(newSalesComp);
    }
    public static void beforeUpdate(List<Sales_Comp__c> newSalesComp, Map<Id, Sales_Comp__c> oldSalesCompMap){
        validateApprover(newSalesComp, oldSalesCompMap);
        populateJustification(newSalesComp);
        calloutApprovedComp(newSalesComp, oldSalesCompMap);
    }
	*/
    
    //overriden methods from trigger framework base class
    public override void beforeInsert(List<SObject> newSalesComp){
        updateSCFields(newSalesComp);
    }
    public override  void beforeUpdate(List<SObject> oldRecords, List<SObject> newSalesComp, Map<ID, SObject> oldSalesCompMap, Map<ID, SObject> newRecordMap){
        validateApprover(newSalesComp, (Map<Id, Sales_Comp__c>) oldSalesCompMap);
        populateJustification(newSalesComp);
        calloutApprovedComp(newSalesComp, (Map<Id, Sales_Comp__c>) oldSalesCompMap);
    }    
    
    public static void updateSCFields(List<Sales_Comp__c> newSalesComp){
        for(Sales_Comp__c salesCompObj : newSalesComp){
            salesCompObj.Status__c = 'Draft';
            if(salesCompRecTypeMap.get(salesCompObj.RecordTypeID).DeveloperName == SALES_COMP_RECORD_TYPE_NAME_SPV_MPV){
                salesCompObj.Adjustment_Type__c = 'add';
                salesCompObj.Reason_Code__c = 'N/A';
            }
            if(salesCompRecTypeMap.get(salesCompObj.RecordTypeID).DeveloperName == SALES_COMP_RECORD_TYPE_NAME_GIFT){
                /* CRM2-1974 - Start */
                // salesCompObj.Adjustment_Type__c = 'N/A';
                salesCompObj.Adjustment_Type__c = 'add';
                /* CRM2-1974 - End */
                salesCompObj.Reason_Code__c = 'N/A';
                /* CRM-2536 - Start */
                salesCompObj.Comp_Type__c = 'Gift';
                /* CRM-2536 - End */
                /* CRM2-2316  - Start */
                //salesCompObj.Property__c = 'N/A';
                /* CRM2-2316  - End */
            }
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<User> getAllUsers(String roleName, Boolean isRole){
        List<User> approverList = new List<User>();
        List<String> filterString = roleName.split('-');
        
        if(String.isNotBlank(roleName)){
            if(isRole){
                approverList = [SELECT Id, Name FROM User WHERE UserRole.Name =: filterString[0] AND isActive = TRUE ORDER BY Name];
            }else{
                approverList = [SELECT Id, Name FROM User WHERE Name =: filterString[0] AND isActive = TRUE ORDER BY Name];
            }
        }
        
        return approverList;
    }
    
    public static void populateJustification(List<Sales_Comp__c> newSalesCompList){
        Set<Id> salesCompIdSet = new Set<Id>();
        Map<Id, String> recordCommentMap = new Map<Id, String>();
        try{
            for(Sales_Comp__c salesCompObj : newSalesCompList){
                if(SALES_COMP_STATUS_APPROVED.equalsIgnoreCase(salesCompObj.Status__c) ||
                   SALES_COMP_STATUS_DECLINED.equalsIgnoreCase(salesCompObj.Status__c) ||
                   SALES_COMP_STATUS_PENDING.equalsIgnoreCase(salesCompObj.Status__c) ||
                   SALES_COMP_STATUS_VOIDED.equalsIgnoreCase(salesCompObj.Status__c)){
                       salesCompIdSet.add(salesCompObj.Id);
                }
            }
            
            if(!salesCompIdSet.isEmpty()){

                List<ProcessInstanceStep> currentApproval = [SELECT Id, ProcessInstance.TargetObjectId, ProcessInstance.Status, Comments, ProcessInstance.CompletedDate, ProcessInstance.LastActorId, ProcessInstance.LastActor.Name, ProcessInstance.LastModifiedDate
                                                        FROM ProcessInstanceStep 
                                                        WHERE ProcessInstance.TargetObjectId IN : salesCompIdSet ORDER BY CreatedDate DESC LIMIT 1];
                if(!currentApproval.isEmpty()){
                    recordCommentMap.put(currentApproval[0].ProcessInstance.TargetObjectId, currentApproval[0].Comments);
                }
                
                for(Sales_Comp__c salesCompRec : newSalesCompList){
                    salesCompRec.Justification__c = recordCommentMap.get(salesCompRec.Id);
                }
            }
        }catch(Exception e){
            ErrorLogger.createLog(APEXCLASSNAME, 'populateJustification', e, null, COMPONENTTYPE);
        }
    }
    
    public static void validateApprover(List<Sales_Comp__c> newSalesCompList, Map<Id, Sales_Comp__c> oldSalesCompMap){
        String approvalsString;
        Sales_Comp__c oldSalesComp = new Sales_Comp__c();
        String userApproversString = System.Label.Sales_Comp_Approvers_75000;
        Set<Id> salesCompIdSet = new Set<Id>();
        Map<Id, Id> salesCompIdApproverMap = new Map<Id, Id>();
        Map<Id, String> userIdRoleMap = new Map<Id, String>();

        String invalidSalesCompId = '';

        try{
            for(Sales_Comp__c salesCompObj : newSalesCompList){
                oldSalesComp = oldSalesCompMap.containsKey(salesCompObj.Id) ? oldSalesCompMap.get(salesCompObj.Id) : new Sales_Comp__c();
                if((SALES_COMP_STATUS_APPROVED.equalsIgnoreCase(salesCompObj.Status__c) && salesCompObj.isForVoid__c == oldSalesComp.isForVoid__c) ||
                   SALES_COMP_STATUS_DECLINED.equalsIgnoreCase(salesCompObj.Status__c) ||
                   SALES_COMP_STATUS_VOIDED.equalsIgnoreCase(salesCompObj.Status__c) ||
                   (SALES_COMP_STATUS_PENDING.equalsIgnoreCase(salesCompObj.Status__c) && oldSalesComp.Status__c != 'Draft') 
                   ){
                       salesCompIdSet.add(salesCompObj.Id);
                   }
            }
            List<ProcessInstanceStep> currentApproval = [SELECT Id, ProcessInstance.TargetObjectId, ProcessInstance.Status, Comments, ProcessInstance.CompletedDate, ProcessInstance.LastActorId, StepStatus, ActorId,
                                                       ProcessInstance.LastActor.Name, ProcessInstance.LastModifiedDate, OriginalActorId
                                                       FROM ProcessInstanceStep 
                                                       WHERE ProcessInstance.TargetObjectId IN : salesCompIdSet ORDER BY CreatedDate DESC LIMIT 1];

            if(!currentApproval.isEmpty()){
                Id tempId = null;

                salesCompIdApproverMap.put(currentApproval[0].ProcessInstance.TargetObjectId, currentApproval[0].ActorId);
            
                for(User userObj : [SELECT Id, Name, UserRole.Name FROM User WHERE Id IN : salesCompIdApproverMap.values()]){
                    if(userApproversString.contains(userObj.Name)){
                        userIdRoleMap.put(userObj.Id, userObj.Name);
                    }else{
                        userIdRoleMap.put(userObj.Id, userObj.UserRole.Name);
                    }
                }

                for(Sales_Comp__c salesCompBuff : newSalesCompList){
                    oldSalesComp = oldSalesCompMap.containsKey(salesCompBuff.Id) ? oldSalesCompMap.get(salesCompBuff.Id) : new Sales_Comp__c();
                    if(salesCompBuff.Amount__c < 501){
                        approvalsString = System.Label.Sales_Comp_Approvers_500 + ',' +
                            System.Label.Sales_Comp_Approvers_1000 + ',' +
                            System.Label.Sales_Comp_Approvers_2000 + ',' +
                            System.Label.Sales_Comp_Approvers_5000 + ',' +
                            System.Label.Sales_Comp_Approvers_75000;
                    }else if(salesCompBuff.Amount__c < 1001){
                        approvalsString = System.Label.Sales_Comp_Approvers_1000 + ',' +
                            System.Label.Sales_Comp_Approvers_2000 + ',' +
                            System.Label.Sales_Comp_Approvers_5000 + ',' +
                            System.Label.Sales_Comp_Approvers_75000;
                    }else if(salesCompBuff.Amount__c < 2001){
                        approvalsString = System.Label.Sales_Comp_Approvers_2000 + ',' +
                            System.Label.Sales_Comp_Approvers_5000 + ',' +
                            System.Label.Sales_Comp_Approvers_75000;
                    }else if(salesCompBuff.Amount__c < 5001){
                        approvalsString = System.Label.Sales_Comp_Approvers_5000 + ',' +
                            System.Label.Sales_Comp_Approvers_75000;
                    }else if(salesCompBuff.Amount__c < 75001){
                        approvalsString = System.Label.Sales_Comp_Approvers_75000;
                    }

                    if(!approvalsString.contains(userIdRoleMap.get(salesCompIdApproverMap.get(salesCompBuff.Id)))){
                        salesCompBuff.Status__c = SALES_COMP_STATUS_INVALID;
                        invalidSalesCompId = salesCompBuff.Id;
                    }
                    else{ //If 1st Approval and only for add adjustment type, is done and not invalid, send to next approval
                        if(currentApproval[0].ProcessInstance.LastActor.Name != FINAL_APPROVER && SALES_COMP_STATUS_APPROVED.equalsIgnoreCase(salesCompBuff.Status__c) 
                           && salesCompBuff.Adjustment_Type__c != 'deduct'){
                            salesCompBuff.Status__c = SALES_COMP_STATUS_PENDING; //Set Status to Approval, other methods will also be checked as Status = Pending
                            sendForSecondApproval(salesCompBuff.Id, null, FINAL_APPROVAL_PROCESS);
                        }
                    }
                }

                if (!String.isEmpty(invalidSalesCompId)) {
                    sendEmailToInvalidComp(invalidSalesCompId);
                }
            }
        }catch(Exception e){
            ErrorLogger.createLog(APEXCLASSNAME, 'validateApprover', e, null, COMPONENTTYPE);
        }
    }

    public static void sendEmailToInvalidComp(String invalidSalesCompId) {
        List<Messaging.SingleEmailMessage> msgs = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();

        Sales_Comp__c sc = [SELECT Id, Contact__c, Owner.Name, Owner.Email FROM Sales_Comp__c WHERE Id = :invalidSalesCompId];
        msg.setTargetObjectId(sc.Contact__c);
        msg.setWhatId(sc.Id);
        msg.setToAddresses(new List<String>{ sc.Owner.Email });

        EmailTemplate et = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'Sales_Comp_Invalid_Approver_Email_Template'];
        msg.setTemplateId(et.Id);

        msg.setSenderDisplayName('The Star Entertainment Group');
        msg.setTreatTargetObjectAsRecipient(false);
        msg.setSaveAsActivity(false);

        msgs.add(msg);
        Messaging.sendEmail(msgs);
    }

    public static void calloutApprovedComp(List<Sales_Comp__c> newSalesCompList, Map<Id, Sales_Comp__c> oldSalesCompMap){
        Set<Id> salesCompIdSet = new Set<Id>();
        
        try{
            for(Sales_Comp__c salesComp : newSalesCompList){
                String salesCompRT = salesCompRecTypeMap.get(salesComp.RecordTypeID).DeveloperName;
                if((SALES_COMP_STATUS_APPROVED.equalsIgnoreCase(salesComp.Status__c) || SALES_COMP_STATUS_VOIDED.equalsIgnoreCase(salesComp.Status__c)) && 
                   salesComp.Status__c != oldSalesCompMap.get(salesComp.Id).Status__c && 
                   salesCompRT == SALES_COMP_RECORD_TYPE_NAME_CD_CP){
                       salesCompIdSet.add(salesComp.Id);
                   }
            }
            
            if(!salesCompIdSet.isEmpty()){
                doCallout(salesCompIdSet);
            }
        }catch (Exception e){
            ErrorLogger.createLog(APEXCLASSNAME, 'calloutApprovedComp', e, null, COMPONENTTYPE);
        }
    }
    
    @future(callout=true)
    public static void doCallout(Set<Id> salesCompIdSet){
        Sales_Comp_Setting__mdt salesCompMdt = Sales_Comp_Setting__mdt.getInstance('Sales_Comp');

        Sales_Comp__c salesComp = new Sales_Comp__c();
        
        try{
            salesComp = [SELECT Id, Contact__c, Status__c, Comp_Type__c, Description__c, Property__c, Amount__c, Adjustment_Type__c,
                                       Reason_Code__c, CreatedById, CreatedBy.Name, Justification__c, Contact__r.Patron_ID__c, Comments__c 
                                       FROM Sales_Comp__c 
                                       WHERE Id IN : salesCompIdSet LIMIT 1];
            
            Boolean isVoid = SALES_COMP_STATUS_APPROVED.equalsIgnoreCase(salesComp.Status__c) ? TRUE : FALSE;
            
            List<ProcessInstanceStep> currentApproval = [SELECT Id, ProcessInstance.TargetObjectId, ProcessInstance.Status, Comments, ProcessInstance.CompletedDate, 
                                                         ProcessInstance.LastActorId, ProcessInstance.LastModifiedDate, ProcessInstance.SubmittedById
                                                         FROM ProcessInstanceStep 
                                                         WHERE ProcessInstance.TargetObjectId =: salesComp.Id ORDER BY CreatedDate DESC LIMIT 1];
            
            User approverUser = [SELECT Id, Name FROM User WHERE Id =: currentApproval[0].ProcessInstance.LastActorId];
            User submittedUser = [SELECT Id, Name FROM User WHERE Id =: currentApproval[0].ProcessInstance.SubmittedById];
            
            SalesCompDataProvider.SalesCompJSON scJson = new SalesCompDataProvider.SalesCompJSON();
            scJson.userId = salesComp.CreatedBy.Name;
            scJson.source = 'Salesforce';
            scJson.host = String.valueOf(URL.getSalesforceBaseUrl().toExternalForm());
            scJson.contextId = salesComp.Id;
            scJson.patronId = salesComp.Contact__r.Patron_ID__c;
            scJson.reasonCode = salesComp.Reason_Code__c;
            scjson.staffUser = submittedUser.Name;
            scJson.approverNotes = String.isBlank(salesComp.Justification__c) ? 'N/A' : salesComp.Justification__c;
            scjson.originalTransactionId = salesComp.Id;
            scJson.pointValue = String.valueOf(salesComp.Amount__c);
            scJson.pointTypeIndicator = salesComp.Comp_Type__c;
            scJson.pointValueType = salesComp.Adjustment_Type__c;
            scJson.propertyId = salesComp.Property__c;
            scJson.approverUserId = approverUser.Name;
            scJson.reasonDescription = salesComp.Description__c;
            scJson.comments = salesComp.Comments__c;

            String jsonBody = json.serialize(scJson);
            
            Httprequest req = new HttpRequest();
            req.setMethod('POST');
            req.setEndpoint(salesCompMdt.Sales_Comp_URL__c);
            req.setHeader('customer-subscription-key', salesCompMdt.Sales_Comp_Sub_Key__c);
            req.setBody(jsonBody);

            Http http = new Http();        
            HttpResponse response = http.send(req);
            System.debug(response.getBody());
            System.debug('Status Code: ' + response.getStatusCode());
			
            if(response.getStatusCode() != 200){
                ErrorLogger.createLog(APEXCLASSNAME, response.getStatusCode() + ' ' + response.getStatus(), null, salesComp.Id, COMPONENTTYPE);
            }
            
        }catch(Exception e){
            ErrorLogger.createLog(APEXCLASSNAME, 'doCallout', e, salesComp.Id, COMPONENTTYPE);
        }
    }

    @future
    public static void sendForSecondApproval(Id checklistId, Id approverId, String approvalProcessName){

        List<ProcessInstanceStep> initialApproval = [SELECT Id, ProcessInstance.ProcessDefinition.DeveloperName, OriginalActor.Id
                                                       FROM ProcessInstanceStep 
                                                       WHERE ProcessInstance.TargetObjectId =: checklistId AND ProcessInstance.ProcessDefinition.DeveloperName =: INITIAL_APPROVAL_PROCESS AND (ProcessInstance.Status = 'Approved' OR ProcessInstance.Status = 'Pending')  ORDER BY CreatedDate ASC LIMIT 1];

        try{
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval.');
            req1.setObjectId(checklistId);
            req1.setProcessDefinitionNameOrId(approvalProcessName);
            req1.setNextApproverIds(new List<Id>{approverId});
            req1.setSkipEntryCriteria(false);
            req1.setSubmitterId(initialApproval[0].OriginalActor.Id);
            Approval.ProcessResult result = Approval.process(req1);
        }
        catch (Exception e){
            ErrorLogger.createLog(APEXCLASSNAME, 'sendForSecondApproval', e, null, COMPONENTTYPE);
        }
    }
}