force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/financialsummary__x/financialsummary__x.object-meta.xml
<CustomObject>
    <description>financialsummary</description>
    <externalDataSource>Cosmos_DB</externalDataSource>
    <externalName>financialsummary</externalName>
    <label>financialsummary</label>
    <pluralLabel>financialsummary</pluralLabel>
</CustomObject>

force-app/main/default/objects/financialsummary__x/fields/ActualTrend__c.field-meta.xml
<CustomField>
    <fullName>ActualTrend__c</fullName>
    <description>ActualTrend</description>
    <externalDeveloperName>ActualTrend_ExclFreePlay</externalDeveloperName>
    <label>Actual Trend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/ADT__c.field-meta.xml
<CustomField>
    <fullName>ADT__c</fullName>
    <description>ADT</description>
    <externalDeveloperName>ADT</externalDeveloperName>
    <label>ADT</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/ADTTrend__c.field-meta.xml
<CustomField>
    <fullName>ADTTrend__c</fullName>
    <description>ADTTrend</description>
    <externalDeveloperName>ADTTrend</externalDeveloperName>
    <label>ADTTrend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/HeaderLabel__c.field-meta.xml
<CustomField>
    <fullName>HeaderLabel__c</fullName>
    <description>HeaderLabel</description>
    <externalDeveloperName>HeaderLabel</externalDeveloperName>
    <label>HeaderLabel</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/SalesforceContactId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceContactId__c</fullName>
    <description>SalesforceContactId</description>
    <externalDeveloperName>SalesforceContactId</externalDeveloperName>
    <label>SalesforceContactId</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TheoTrend__c.field-meta.xml
<CustomField>
    <fullName>TheoTrend__c</fullName>
    <description>TheoTrend</description>
    <externalDeveloperName>TheoTrend</externalDeveloperName>
    <label>TheoTrend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TotalActual__c.field-meta.xml
<CustomField>
    <fullName>TotalActual__c</fullName>
    <description>TotalActual</description>
    <externalDeveloperName>TotalActual_ExclFreePlay</externalDeveloperName>
    <label>Total Net Actual</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TotalTheo__c.field-meta.xml
<CustomField>
    <fullName>TotalTheo__c</fullName>
    <description>TotalTheo</description>
    <externalDeveloperName>TotalTheo</externalDeveloperName>
    <label>Total Net Theo</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TotalTrips__c.field-meta.xml
<CustomField>
    <fullName>TotalTrips__c</fullName>
    <description>TotalTrips</description>
    <externalDeveloperName>TotalTrips</externalDeveloperName>
    <label>Total Trips</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TripsTrend__c.field-meta.xml
<CustomField>
    <fullName>TripsTrend__c</fullName>
    <description>TripsTrend</description>
    <externalDeveloperName>TripsTrend</externalDeveloperName>
    <label>TripsTrend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FinanceDataProvider.cls
/**
 * @description       : 
 * @author            : sakshi.chauhan@simplus.com
 * @group             : 
 * @last modified on  : 09-24-2020
 * @last modified by  : sakshi.chauhan@simplus.com
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   07-20-2020   sakshi.chauhan@simplus.com   Initial Version
**/
public without sharing class FinanceDataProvider {

    public static String getFinanceDataJSON(Id recordId) {
        List<FinanceObjectWrapper> financeObjWrapList = new List<FinanceObjectWrapper>();
        try{
            
            List<FinancialSummary__x> fdetails = getFinanceRecordsByContactId(recordId);
            FinanceObjectWrapper wrapperObj = new FinanceObjectWrapper();
            wrapperObj = initiliseFinanceUILabels(wrapperObj);

            if(fdetails.size() > 0){
                
                for(FinancialSummary__x detObj : fdetails){
                    wrapperObj = initialiseWrapperObject(wrapperObj,detObj); 
                }
            }      
            financeObjWrapList.add(wrapperObj);       
            return JSON.serialize(financeObjWrapList);
            
           
        }
        catch(Exception e){
            system.debug('cdsdsfds');
            system.debug('Exception happenned '+ e.getMessage() );
            ErrorLogger.createLog('FinanceDataProvider','getFinanceDataJSON',e,recordId,'Apex Class'); 
            return null;
        }
  
    }    

    public static List<FinancialSummary__x> getFinanceRecordsByContactId(Id contactId){
        if(Test.isRunningTest()){
            if( FinancialSummaryUIControllerTest.testException == true ){
                throw new FinanceDataProviderException();
            }
            FinancialSummary__x testFinData = new FinancialSummary__x(SalesforceContactId__c = FinancialSummaryUIControllerTest.ct.Id,ADT__c=2121,TotalTheo__c=129,TotalActual__c=3233,ADTTrend__c='Up',TheoTrend__c='Down',HeaderLabel__c = 'Performance Overview');
            List<FinancialSummary__x> finList= new List<FinancialSummary__x>();
            finList.add(testFinData);
            return finList;
            //return null;
        }
        else{
            FinanceObjectSelector selector = new FinanceObjectSelector();

            String field = '';
            for (Integer i = 0; i < selector.getExternalObjectFieldsList().size(); i++) {
                String currentField = String.valueOf(selector.getExternalObjectFieldsList()[i]);
                field = field + currentField + ',';
            }
            String fields = field.removeEnd(',');

            //String query = 'SELECT ' + fields + ' FROM ' + selector.getExternalObjectType() + ' WHERE SalesforceContactId__c = \'' + contactId + '\' LIMIT 1';
            Contact contRec = [SELECT Patron_ID__c FROM Contact WHERE Id =  :contactId LIMIT 1];
            String query = 'SELECT ' + fields + ' FROM ' + selector.getExternalObjectType() + ' WHERE SalesforceContactId__c LIKE \'%' + contactId + '%\' AND ExternalId = \'' + contRec.Patron_ID__c + '\' LIMIT 1';
            return Database.query(query);
        }
    }

    public static FinanceObjectWrapper initialiseWrapperObject( FinanceObjectWrapper wrapObjTemp,FinancialSummary__x fSummarydetailObj){
        if( wrapObjTemp.dataDetails == null ){
            wrapObjTemp.dataDetails = new FinanceObjectWrapper.Data();
        }
        wrapObjTemp.contactId = fSummarydetailObj.SalesforceContactId__c;
        wrapObjTemp.dataDetails.ADT = fSummarydetailObj.ADT__c;
        wrapObjTemp.dataDetails.theo = fSummarydetailObj.TotalTheo__c; 
        wrapObjTemp.dataDetails.trips = fSummarydetailObj.TotalTrips__c; 
        wrapObjTemp.dataDetails.actual = fSummarydetailObj.TotalActual__c;

        wrapObjTemp.dataDetails.createDt = fSummarydetailObj.CreateDt__c != null?fSummarydetailObj.CreateDt__c.format('dd/MM/yyyy, hh:mm a', + 'Pacific'):null;

        wrapObjTemp.dataDetails.adtTrend = fSummarydetailObj.ADTTrend__c != null?fSummarydetailObj.ADTTrend__c.toUpperCase():null ;
        wrapObjTemp.dataDetails.theoTrend = fSummarydetailObj.TheoTrend__c != null?fSummarydetailObj.TheoTrend__c.toUpperCase():null;
        wrapObjTemp.dataDetails.tripsTrend = fSummarydetailObj.TripsTrend__c != null?fSummarydetailObj.TripsTrend__c.toUpperCase():null;
        wrapObjTemp.dataDetails.headerLabel = fSummarydetailObj.HeaderLabel__c != null ?fSummarydetailObj.HeaderLabel__c.toUpperCase():null;
        wrapObjTemp.dataDetails.actualTrend = fSummarydetailObj.ActualTrend__c != null? fSummarydetailObj.ActualTrend__c.toUpperCase():null;
        return wrapObjTemp;
    }

    public static FinanceObjectWrapper initiliseFinanceUILabels(FinanceObjectWrapper wrapObjTemp){
        Map<String,String> fieldLabelMap = Utility.getFieldsMapByObject('FinancialSummary__x');
        if(wrapObjTemp.labelDetails == null){
            wrapObjTemp.labelDetails = new FinanceObjectWrapper.Labels();
        }
        wrapObjTemp.labelDetails.adtLabel = fieldLabelMap.get('ADT__c');
        wrapObjTemp.labelDetails.theoLabel = fieldLabelMap.get('TotalTheo__c');
        wrapObjTemp.labelDetails.tripsLabel = fieldLabelMap.get('TotalTrips__c');
        wrapObjTemp.labelDetails.actualLabel = fieldLabelMap.get('TotalActual__c');

        return wrapObjTemp;
    }

    public class FinanceDataProviderException extends Exception{}
}