force-app/main/default/objects/Contact/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Other_Traveller__c/Other_Traveller__c.object-meta.xml
<CustomObject>
    <label>Other Traveller</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Other Traveller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Travellers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Other_Traveller__c/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Other_Traveller__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Other_Traveller__c/fields/Patron_ID__c.field-meta.xml
<CustomField>
    <fullName>Patron_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patron ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Other_Traveller__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Other Travellers</relationshipLabel>
    <relationshipName>Other_Travellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Other_Traveller__c/fields/Surname__c.field-meta.xml
<CustomField>
    <fullName>Surname__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Surname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Booking Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Limo</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/VIP_Booking__c.field-meta.xml
<CustomField>
    <fullName>VIP_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIP Booking</label>
    <referenceTo>VIP_Booking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIP_Booking__c/VIP_Booking__c.object-meta.xml
<CustomObject>
    <label>VIP Booking</label>
    <nameField>
        <displayFormat>VIPB-{0000}</displayFormat>
        <label>VIP Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIP Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIP_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VIP Bookings</relationshipLabel>
    <relationshipName>VIP_Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlightServiceExtract.cls
public class FlightServiceExtract {
    public Id RecordId {get;set;}
    private final List <Other_Traveller__c> OtherTraveller;
    private final List <Service__c> PatronDetails;
    
    public FlightServiceExtract(ApexPages.StandardController stdController){
        RecordId  = ApexPages.currentPage().getParameters().get('id');
        this.OtherTraveller = [SELECT Id, Passport_Number__c, DOB__c, Patron_ID__c, First_Name__c, Surname__c, Title__c FROM Other_Traveller__c Where Service__c = :RecordId ORDER BY CreatedDate ASC];
        //List <Service__c> vipBookingId = [SELECT Id,VIP_Booking__c FROM Service__c Where Id = :RecordId ORDER BY CreatedDate DESC];
        
        this.PatronDetails = [SELECT Id, Contact__r.LastName, Contact__r.FirstName, Contact__r.Title FROM Service__c Where Id = :RecordId ORDER BY CreatedDate DESC];
    }
    
    public List <Other_Traveller__c> getOtherTraveller() {
        return OtherTraveller;
    }
    
    public List <Service__c> getPatronDetails() {
        return PatronDetails;
    }
    
    public String getDevice() {
        String extension;
        Boolean isMobile = UserInfo.getUiTheme() == 'Theme4t';
        
        if(isMobile){
            extension = 'html';
        }else{
            extension = 'pdf';
        }
        
        return extension;
    }
}