force-app/main/default/objects/Contact/fields/Portal_Email_Update_Sync_Wait__c.field-meta.xml
<CustomField>
    <fullName>Portal_Email_Update_Sync_Wait__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom Field created for Member Portal to wait for Email Update to be synced from MDM.</description>
    <label>Portal Email Update Sync Wait</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Email_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Portal_Email_Updated_Time__c</fullName>
    <description>Custom Field created for Member Portal to wait for Email Update to be synced from MDM.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Portal Email Updated Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Mobile_Update_Sync_Wait__c.field-meta.xml
<CustomField>
    <fullName>Portal_Mobile_Update_Sync_Wait__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom Field created for Member Portal to sync the Mobile update from MDM to Salesforce.</description>
    <label>Portal Mobile Update Sync Wait</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Mobile_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Portal_Mobile_Updated_Time__c</fullName>
    <description>Custom Field created for Member Portal to sync the Mobile update from MDM to Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Portal Mobile Updated Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PortalUpdateSyncBatchTest.cls
@isTest
private class PortalUpdateSyncBatchTest {
    static testMethod void testme(){
        Contact con = new Contact();
        con.FirstName = 'Test First';
        con.LastName = 'Test last';
        con.Portal_Email_Updated_Time__c = System.now().addHours(-2);
        con.Portal_Mobile_Updated_Time__c = System.now().addHours(-2);
        insert con;
        Test.startTest();
        PortalUpdateSyncBatch ba= new PortalUpdateSyncBatch();
        Id jobid= Database.executeBatch(ba,5);
        Test.stopTest();
        Contact con1 = [select Id,Portal_Email_Update_Sync_Wait__c, Portal_Email_Updated_Time__c, Portal_Mobile_Update_Sync_Wait__c, Portal_Mobile_Updated_Time__c from Contact where id=:con.Id];
        system.assertEquals(null, con1.Portal_Email_Updated_Time__c);
        
        SchedulableContext sc = null;
        PortalUpdateSyncBatchSchedule tsc = new PortalUpdateSyncBatchSchedule();
        tsc.execute(sc);
    }
}