force-app/main/default/objects/Contact/fields/Portal_Email_Update_Sync_Wait__c.field-meta.xml
<CustomField>
    <fullName>Portal_Email_Update_Sync_Wait__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom Field created for Member Portal to wait for Email Update to be synced from MDM.</description>
    <label>Portal Email Update Sync Wait</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Mobile_Update_Sync_Wait__c.field-meta.xml
<CustomField>
    <fullName>Portal_Mobile_Update_Sync_Wait__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom Field created for Member Portal to sync the Mobile update from MDM to Salesforce.</description>
    <label>Portal Mobile Update Sync Wait</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SoW_Update_DateTime__c.field-meta.xml
<CustomField>
    <fullName>SoW_Update_DateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SoW Update DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Their_role_in_that_business__c.field-meta.xml
<CustomField>
    <fullName>Their_role_in_that_business__c</fullName>
    <description>Use to store individual role in the business</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Their role in that business</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHandlerTest.cls
/**
* @description       : Test class for ContactTriggerHandler
* @author            : Simplus
* @group             : Simplus
* @last modified by  : Simplus
* Modifications Log
* Ver   Date         Author                       Modification
* 1.0   11-09-2023   Simplus                      Initial Version
*/
@isTest
public class ContactTriggerHandlerTest {
    
    @isTest
    static void testSowUpdate(){
        
        Contact c = new Contact();
        c.FirstName = 'Test FName';
        c.LastName = 'Test LName';
        insert c;
        
        c.Their_role_in_that_business__c = '123';
        update c;
        
    }
    @isTest
    static void testSowUpdate2(){
        Contact c = new Contact();
        c.FirstName = 'Test FName';
        c.LastName = 'Test LName';
        c.Email = 'Test@test.com';
        c.MobilePhone = '61-457154770';
        c.SoW_Update_DateTime__c = DateTime.now();
        insert c;
        
        Contact con = [select id,MobilePhone,Email,SoW_Update_DateTime__c,Portal_Mobile_Update_Sync_Wait__c,Portal_Email_Update_Sync_Wait__c from contact where FirstName ='Test FName'];
        c.Email = 'Test1@test.com';
        con.MobilePhone = '61-457154771';
        con.SoW_Update_DateTime__c = DateTime.now() +1;
        update c;
        
    }
    @isTest
    static void testSowUpdate3(){
        Contact c = new Contact();
        c.FirstName = 'Test FName';
        c.LastName = 'Test LName';
        c.Email = 'Test@test.com';
        c.MobilePhone = '61-457154770';
        c.SoW_Update_DateTime__c = DateTime.now();
        insert c;
        
        Contact con = [select id,MobilePhone,Email,SoW_Update_DateTime__c,Portal_Mobile_Update_Sync_Wait__c,Portal_Email_Update_Sync_Wait__c from contact where FirstName ='Test FName'];
        c.MobilePhone = '61-457154771';
        con.SoW_Update_DateTime__c = DateTime.now() +1;
        update c;
        
    }
}