force-app/main/default/objects/Contact/fields/Source_of_Wealth__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Wealth__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Source of Wealth for Business</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source_of_Wealth__c/Source_of_Wealth__c.object-meta.xml
<CustomObject>
    <label>Source of Wealth</label>
    <nameField>
        <displayFormat>SOW-{0}</displayFormat>
        <label>Source of Wealth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source of Wealth</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Source_of_Wealth__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patron</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Source of Wealth</relationshipLabel>
    <relationshipName>Source_of_Wealth</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source_of_Wealth__c/fields/fileuploaded_to_trackvia__c.field-meta.xml
<CustomField>
    <fullName>fileuploaded_to_trackvia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>fileuploaded to trackvia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source_of_Wealth__c/fields/isSubmitted__c.field-meta.xml
<CustomField>
    <fullName>isSubmitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be marked once the application is submitted by the the user from form assembly.</description>
    <label>isSubmitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SOWTriggerTest.cls
/**
 * @description       : Test class for SOWTrigger 
 * @author            : CapGemini
 * @group             : CapGemini
 * @last modified by  : CapGemini
 * Modifications Log
 * Ver   Date         Author                       Modification
 * 1.0   21-01-2025   CapGemini                      Initial Version
 * 2.0   10-07-2025   Arth                           Initial Version
 */
@isTest
public class SOWTriggerTest{
    
    @isTest
    static void testSOWExternalUpdate(){

        Contact c = new Contact();
        c.FirstName = 'Test FName';
        c.LastName = 'Test LName';
        insert c;
        Source_of_Wealth__c tObj = new Source_of_Wealth__c();
        tObj.Contact__c = c.id;
        insert tObj;
         
        Test.startTest();
        try{
        
        //Simulating the first update from external system
          tObj.isSubmitted__c = true;
          update tObj;
          
          
        //Simulating the Second update from external system
          tObj.isSubmitted__c = true;
          update tObj;
          
          tObj.fileuploaded_to_trackvia__c = false;
          update tObj;
          
          tObj.fileuploaded_to_trackvia__c = true;
          update tObj;
          
          

          
        }
        Catch(Exception ex)
        {
        
        Boolean expectedExceptionThrown =  (ex.getMessage().contains('error msg')) ? true : false; 
        System.AssertEquals(false, expectedExceptionThrown, ex.getMessage()); 
        }
        Test.stopTest();
        
    }
}