force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Days in NSW/QLD or AUS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days in NSW/QLD or AUS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_State__c.field-meta.xml
<CustomField>
    <fullName>Entry_State__c</fullName>
    <label>Entry State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/is_within_365_days__c.field-meta.xml
<CustomField>
    <fullName>is_within_365_days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is within 365 days?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Update365CheckboxBatch.cls
global class Update365CheckboxBatch implements Database.batchable<sObject>{ 
   global Database.QueryLocator start(Database.BatchableContext info){ 
       String query = 'SELECT Id, is_within_365_days__c, Entry_Date__c, Entry_State__c FROM Trip__c WHERE is_within_365_days__c = TRUE';
       return Database.getQueryLocator(query); 
   }     
   global void execute(Database.BatchableContext info, List<Trip__c> tripList){
       List<Trip__c> newTripList = new List<Trip__c>();
       Date dateToday = Date.today();
       Integer tripDuration;
       for(Trip__c tripObj : tripList){
           tripDuration = tripObj.Entry_Date__c.daysBetween(dateToday);
           if(tripDuration>365){
               tripObj.is_within_365_days__c = FALSE;
               newTripList.add(tripObj);
           }
       }
       
       if(!newTripList.isEmpty()){
           Database.update(newTripList, true);
       }
   }     
   public void finish(Database.BatchableContext info){     
   } 
}