force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Days in NSW/QLD or AUS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days in NSW/QLD or AUS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Days in NSW/QLD or AUS</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_State__c.field-meta.xml
<CustomField>
    <fullName>Entry_State__c</fullName>
    <label>Entry State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>Exit_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/is_within_365_days__c.field-meta.xml
<CustomField>
    <fullName>is_within_365_days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is within 365 days?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Update365CheckboxBatchTest.cls
@isTest
public class Update365CheckboxBatchTest {
    static testmethod void testBatchClass(){
        Contact testContact = TestDataFactory.createSingleContact('Test Class');
        Date dateToday = System.today();
        List<Trip__c> tripList = new List<Trip__c>();
        
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = FALSE;
        
        tripList.add(firstTrip);
        
        Trip__c secondTrip = new Trip__c();
        secondTrip.Contact__c = testContact.Id;
        secondTrip.Entry_State__c = 'QLD';
        secondTrip.Entry_Date__c = dateToday;
        secondTrip.Exit_Date__c = secondTrip.Entry_Date__c.addDays(14);
        secondTrip.Cancelled__c = FALSE;
        secondTrip.is_within_365_days__c = TRUE;
        
        tripList.add(secondTrip);
        
        INSERT tripList;
        
        test.startTest();
        Update365CheckboxBatch myBatchObject = new Update365CheckboxBatch(); 
        Id batchId = Database.executeBatch(myBatchObject);
        test.stopTest();
    }

    static testmethod void testBatchClass2(){

        Test.startTest();
        String CRON_EXP = '0 6 * * * ?';
        String jobId = System.schedule('Test Sched', CRON_EXP, new ScheduleTripsUpdate());
        Test.stopTest();
    }
}