force-app/main/default/objects/Other_Traveller__c/Other_Traveller__c.object-meta.xml
<CustomObject>
    <label>Other Traveller</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Other Traveller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Travellers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Other_Traveller__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Other Travellers</relationshipLabel>
    <relationshipName>Other_Travellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Booking Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Limo</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TravellerTriggerHandler.cls
public with sharing class TravellerTriggerHandler {
   
    public static void onBeforeInsert(List<Other_Traveller__c> travellerList){

        checkLimitOfRecords(travellerList);
    }

    public static void checkLimitOfRecords(List<Other_Traveller__c> travellerList){
        
        Set<Id> tempServiceSet = new Set<Id>();

        for(Other_Traveller__c otherTravRec : travellerList){

            tempServiceSet.add(otherTravRec.Service__c);
        }

        //Map<Id, AggregateResult> aggServMap = new Map<id, AggregateResult>([SELECT Service__c Id, Count(Id) travCount FROM Other_Traveller__c WHERE Service__c IN: tempServiceSet GROUP BY Service__c]);

        Map<Id, Service__c> serviceMap = new Map<Id, Service__c>([SELECT Id, RecordType.Name, (SELECT Id FROM Other_Travellers__r) FROM Service__c WHERE Id IN: tempServiceSet]);

        if(!serviceMap.isEmpty()){

            for(Other_Traveller__c otherTravRec : travellerList){

                if(serviceMap.containsKey(otherTravRec.Service__c)){
                    
                    if(serviceMap.get(otherTravRec.Service__c).Other_Travellers__r.size() >= 5){

                        otherTravRec.addError('You cannot add more than 5 Travellers');
                    }
                }
            }
        }
    }
}