force-app/main/default/objects/BigObjectCriteria__c/BigObjectCriteria__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Criteria for Deletion of Big Object</label>
</CustomObject>

force-app/main/default/objects/BigObjectCriteria__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Event Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/ContactLightningURIEvent__b.object-meta.xml
<CustomObject>
    <label>ContactLightningURIEvent</label>
    <pluralLabel>ContactLightningURIEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <label>EventDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/EventIdentifier__c.field-meta.xml
<CustomField>
    <fullName>EventIdentifier__c</fullName>
    <label>EventIdentifier</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/IPAddress__c.field-meta.xml
<CustomField>
    <fullName>IPAddress__c</fullName>
    <label>IPAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/OperatingSystem__c.field-meta.xml
<CustomField>
    <fullName>OperatingSystem__c</fullName>
    <label>OperatingSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/QueriedEntities__c.field-meta.xml
<CustomField>
    <fullName>QueriedEntities__c</fullName>
    <label>QueriedEntities</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactLightningURIEvent__b/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <label>UserType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduledDeleteBigObjectBatchTest.cls
@IsTest
public class ScheduledDeleteBigObjectBatchTest {
    
    @testSetup
    static void testDataFactory(){
        
        
        //Database.insertImmediate(conURIEventList);
    }

    static testmethod void executeBatchTest() {

        Contact testContact = new Contact();
        testContact.LastName = 'TestClass';
        INSERT testContact;

        BigObjectCriteria__c testCS = new BigObjectCriteria__c();
        testCS.Event_Date__c = 365;
        UPSERT testCS;

        List<ContactLightningURIEvent__b> conURIEventList = new List<ContactLightningURIEvent__b>();

        ContactLightningURIEvent__b conURIEvent = new ContactLightningURIEvent__b();
        conURIEvent.EventDate__c = System.now();
        conURIEvent.Operation__c = 'Read';
        conURIEvent.EventIdentifier__c = '6b3b1419-7c19-4fb5-89d5-521cace58595';
        conURIEvent.QueriedEntities__c = 'Contact';
        conURIEvent.RecordId__c = testContact.Id;
        conURIEvent.IPAddress__c = '192.168.1.1';
        conURIEvent.User__c = 'rhysjohn.delacruz@star.com.au.dev';
        conURIEvent.Platform__c = 'SFX:BROWSER:DESKTOP';
        conURIEvent.OperatingSystem__c = 'WINDOWS';
        conURIEvent.UserType__c = 'Standard';
        conURIEventList.add(conURIEvent);
        
        Test.startTest();
        ScheduledDeleteBigObjectBatch testBatch = new ScheduledDeleteBigObjectBatch(conURIEventList);
        ScheduledDeleteBigObjectBatch.runOriginalConstructor = false;
        Database.executeBatch(testBatch);
        Test.stopTest();
    }
    
    static testmethod void executeTrue(){
        BigObjectCriteria__c testCS = new BigObjectCriteria__c();
        testCS.Event_Date__c = 365;
        UPSERT testCS;
        
        Test.startTest();
        ScheduledDeleteBigObjectBatch.runOriginalConstructor = true;
        Database.executeBatch(new ScheduledDeleteBigObjectBatch());
        Test.stopTest();
    }
}