force-app/main/default/objects/financialsummary__x/financialsummary__x.object-meta.xml
<CustomObject>
    <description>financialsummary</description>
    <externalDataSource>Cosmos_DB</externalDataSource>
    <externalName>financialsummary</externalName>
    <label>financialsummary</label>
    <pluralLabel>financialsummary</pluralLabel>
</CustomObject>

force-app/main/default/objects/financialsummary__x/fields/ActualTrend__c.field-meta.xml
<CustomField>
    <fullName>ActualTrend__c</fullName>
    <description>ActualTrend</description>
    <externalDeveloperName>ActualTrend_ExclFreePlay</externalDeveloperName>
    <label>Actual Trend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/ADT__c.field-meta.xml
<CustomField>
    <fullName>ADT__c</fullName>
    <description>ADT</description>
    <externalDeveloperName>ADT</externalDeveloperName>
    <label>ADT</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/ADTTrend__c.field-meta.xml
<CustomField>
    <fullName>ADTTrend__c</fullName>
    <description>ADTTrend</description>
    <externalDeveloperName>ADTTrend</externalDeveloperName>
    <label>ADTTrend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/HeaderLabel__c.field-meta.xml
<CustomField>
    <fullName>HeaderLabel__c</fullName>
    <description>HeaderLabel</description>
    <externalDeveloperName>HeaderLabel</externalDeveloperName>
    <label>HeaderLabel</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/SalesforceContactId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceContactId__c</fullName>
    <description>SalesforceContactId</description>
    <externalDeveloperName>SalesforceContactId</externalDeveloperName>
    <label>SalesforceContactId</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TheoTrend__c.field-meta.xml
<CustomField>
    <fullName>TheoTrend__c</fullName>
    <description>TheoTrend</description>
    <externalDeveloperName>TheoTrend</externalDeveloperName>
    <label>TheoTrend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TotalActual__c.field-meta.xml
<CustomField>
    <fullName>TotalActual__c</fullName>
    <description>TotalActual</description>
    <externalDeveloperName>TotalActual_ExclFreePlay</externalDeveloperName>
    <label>Total Net Actual</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TotalTheo__c.field-meta.xml
<CustomField>
    <fullName>TotalTheo__c</fullName>
    <description>TotalTheo</description>
    <externalDeveloperName>TotalTheo</externalDeveloperName>
    <label>Total Net Theo</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TotalTrips__c.field-meta.xml
<CustomField>
    <fullName>TotalTrips__c</fullName>
    <description>TotalTrips</description>
    <externalDeveloperName>TotalTrips</externalDeveloperName>
    <label>Total Trips</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/financialsummary__x/fields/TripsTrend__c.field-meta.xml
<CustomField>
    <fullName>TripsTrend__c</fullName>
    <description>TripsTrend</description>
    <externalDeveloperName>TripsTrend</externalDeveloperName>
    <label>TripsTrend</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FinanceObjectSelector.cls
/**
 * @description       : 
 * @author            : sakshi.chauhan@simplus.com
 * @group             : 
 * @last modified on  : 09-01-2020
 * @last modified by  : sakshi.chauhan@simplus.com
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   07-24-2020   sakshi.chauhan@simplus.com   Initial Version
**/
public class FinanceObjectSelector extends ExternalObjectQuerySelector{
    
    public override List<Schema.SObjectField> getExternalObjectFieldsList() {
       return new List<Schema.SObjectField> {
            FinancialSummary__x.HeaderLabel__c,
            FinancialSummary__x.SalesforceContactId__c,

            FinancialSummary__x.CreateDt__c,

            FinancialSummary__x.ADT__c,
            FinancialSummary__x.ADTTrend__c,

            FinancialSummary__x.TotalTheo__c,
            FinancialSummary__x.TheoTrend__c,

            FinancialSummary__x.TotalTrips__c,
            FinancialSummary__x.TripsTrend__c,

            FinancialSummary__x.TotalActual__c,
            FinancialSummary__x.ActualTrend__c
        };
    }

    public override Schema.SObjectType getExternalObjectType() {
        return FinancialSummary__x.sObjectType;
        //return null;
    }

}