force-app/main/default/objects/Residency_Checklist__c/Residency_Checklist__c.object-meta.xml
<CustomObject>
    <label>Residency Checklist</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Residency Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residency Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Residency_Checklist__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Days in NSW/QLD or AUS</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Residency Checklists</relationshipLabel>
    <relationshipName>Residency_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Days in NSW/QLD or AUS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days in NSW/QLD or AUS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Days in NSW/QLD or AUS</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Entry_State__c.field-meta.xml
<CustomField>
    <fullName>Entry_State__c</fullName>
    <label>Entry State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>Exit_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/is_within_365_days__c.field-meta.xml
<CustomField>
    <fullName>is_within_365_days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is within 365 days?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GetQuestionnaireMdtTest.cls
@isTest
public class GetQuestionnaireMdtTest {
    
    @testSetup
    static void TestDataFactory(){
        Contact testContact = TestDataFactory.createSingleContact('TestClass');
    }

    static testmethod void printableViewTest(){

        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Date dateToday = System.today();
        List<Trip__c> tripList = new List<Trip__c>();
    
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        tripList.add(firstTrip);

        insert tripList;

        Residency_Checklist__c res = new Residency_Checklist__c();
        res.Trip__c = tripList[0].Id;

        insert res;

        Test.StartTest(); 

            ApexPages.StandardController sc = new ApexPages.StandardController(res);
			GetQuestionnaireMdt questionnaireMDT = new GetQuestionnaireMdt(sc);
			questionnaireMDT.getQuestionInt();
			questionnaireMDT.getQuestionDom();

		Test.StopTest();
    }

    static testmethod void printableViewTest2(){

        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Date dateToday = System.today();
        List<Trip__c> tripList = new List<Trip__c>();
    
        Trip__c firstTrip = new Trip__c();
        firstTrip.Contact__c = testContact.Id;
        firstTrip.Entry_State__c = 'NSW';
        firstTrip.Entry_Date__c = dateToday;
        firstTrip.Exit_Date__c = dateToday.addDays(7);
        firstTrip.Cancelled__c = FALSE;
        firstTrip.is_within_365_days__c = TRUE;
        
        tripList.add(firstTrip);

        insert tripList;

        Residency_Checklist__c res = new Residency_Checklist__c();
        res.Trip__c = tripList[0].Id;

        insert res;

        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(res.Id);
        req1.setNextApproverIds(new List<Id>{UserInfo.getUserId()});
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);

        Approval.ProcessWorkitemRequest req =
        new Approval.ProcessWorkitemRequest();
        req.setComments('Approving request.');
        req.setAction('Approve');
        
        ProcessInstanceWorkitem pItem = [Select Id from ProcessInstanceWorkitem  where ProcessInstance.TargetObjectId =: res.id];
       	
        req.setWorkitemId(pItem.Id);

        Approval.ProcessResult result2 = Approval.process(req);

        Test.StartTest(); 
            PageReference resPrintableView = Page.ResidencyPrintableView;
            Test.setCurrentPage(resPrintableView);
            
            ApexPages.currentPage().getParameters().put('id',res.Id);

            ApexPages.StandardController sc = new ApexPages.StandardController(res);
			GetQuestionnaireMdt questionnaireMDT = new GetQuestionnaireMdt(sc);
            questionnaireMDT.getApprovalStatus();
			questionnaireMDT.getApprovalDate();
			questionnaireMDT.getCompletedBy();
            questionnaireMDT.getCompletedByDate();
            questionnaireMDT.getContactType();
            questionnaireMDT.getProgramCode();
            questionnaireMDT.getDuration();

		Test.StopTest();
    }
}