force-app/main/default/objects/gamingdata__x/gamingdata__x.object-meta.xml
<CustomObject>
    <description>gamingdata</description>
    <externalDataSource>Cosmos_DB</externalDataSource>
    <externalName>gamingdata</externalName>
    <label>gamingdata</label>
    <pluralLabel>gamingdata</pluralLabel>
</CustomObject>

force-app/main/default/objects/gamingdata__x/fields/AverageBet__c.field-meta.xml
<CustomField>
    <fullName>AverageBet__c</fullName>
    <description>AverageBet</description>
    <externalDeveloperName>AverageBet</externalDeveloperName>
    <label>AverageBet</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/FreePlay__c.field-meta.xml
<CustomField>
    <fullName>FreePlay__c</fullName>
    <description>FreePlay</description>
    <externalDeveloperName>FreePlay</externalDeveloperName>
    <label>FreePlay</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Frequency</description>
    <externalDeveloperName>Frequency</externalDeveloperName>
    <label>Frequency</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/NetTheo__c.field-meta.xml
<CustomField>
    <fullName>NetTheo__c</fullName>
    <description>NetTheo</description>
    <externalDeveloperName>NetTheo</externalDeveloperName>
    <label>NetTheo</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period</description>
    <externalDeveloperName>Period</externalDeveloperName>
    <label>Period</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/PreferredVisitDay__c.field-meta.xml
<CustomField>
    <fullName>PreferredVisitDay__c</fullName>
    <description>PreferredVisitDay</description>
    <externalDeveloperName>PreferredVisitDay</externalDeveloperName>
    <label>PreferredVisitDay</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/SalesforceContactID__c.field-meta.xml
<CustomField>
    <fullName>SalesforceContactID__c</fullName>
    <description>SalesforceContactID</description>
    <externalDeveloperName>SalesforceContactID</externalDeveloperName>
    <label>SalesforceContactID</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/SalesforcePropertyID__c.field-meta.xml
<CustomField>
    <fullName>SalesforcePropertyID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SalesforcePropertyID</description>
    <externalDeveloperName>SalesforcePropertyID</externalDeveloperName>
    <label>SalesforcePropertyID</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>gamingdata</relationshipLabel>
    <relationshipName>gamingdata</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/Trips__c.field-meta.xml
<CustomField>
    <fullName>Trips__c</fullName>
    <description>Trips</description>
    <externalDeveloperName>Trips</externalDeveloperName>
    <label>Trips</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/Turnover__c.field-meta.xml
<CustomField>
    <fullName>Turnover__c</fullName>
    <description>Turnover</description>
    <externalDeveloperName>Turnover_ExclFreePlay</externalDeveloperName>
    <label>Turnover</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/gamingdata__x/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type</description>
    <externalDeveloperName>Type</externalDeveloperName>
    <label>Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GamingDataObjectSelector.cls
/**
 * @description       : Class for getting the fields and type of the External Object (called by the GamingDataProvider.apxc)
 * @author            : dominicjasper.caberoy@simplus.com
 * @group             : 
 * @last modified on  : 08-17-2020
 * @last modified by  : dominicjasper.caberoy@simplus.com
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   08-17-2020   dominicjasper.caberoy@simplus.com   Initial Version
**/
public class GamingDataObjectSelector extends ExternalObjectQuerySelector{
    public override List<Schema.SObjectField> getExternalObjectFieldsList(){
        return new List<Schema.SObjectField>{
            GamingData__x.Actual__c,
            GamingData__x.ADT__c,
            GamingData__x.AverageBet__c,
            GamingData__x.FreePlay__c,
            GamingData__x.Frequency__c,
            GamingData__x.Type__c,
            GamingData__x.NetTheo__c,
            GamingData__x.PreferredVisitDay__c,
            GamingData__x.Trips__c,
            GamingData__x.Turnover__c,
            GamingData__x.Period__c,
            GamingData__x.SalesforceContactID__c,
            GamingData__x.ExternalId,
            GamingData__x.SalesforcePropertyID__c
        };
    }
    public override Schema.SObjectType getExternalObjectType(){
        return GamingData__x.sObjectType;
    }
}